feat: Re-fetch token instance metadata
blockscout/blockscout pull request #10097
Opened 2024-05-20 19:40 UTC by vbaranov

Resolves https://github.com/blockscout/blockscout/issues/9743

## Motivation

*Why we should merge these changes.  If using GitHub keywords to close [issues](https://github.com/poanetwork/blockscout/issues), this is optional as the motivation can be read on the issue page.*

## Changelog

### Enhancements
*Things you added that don't break anything.  Regression tests for Bug Fixes count as Enhancements.*

### Bug Fixes
*Things you changed that fix bugs.  If a fixes a bug, but in so doing adds a new requirement, removes code, or requires a database reset and reindex, the breaking part of the change should be added to Incompatible Changes below also.*

### Incompatible Changes
*Things you broke while doing Enhancements and Bug Fixes.  Breaking changes include (1) adding new requirements and (2) removing code.  Renaming counts as (2) because a rename is a removal followed by an add.*

## Upgrading

*If you have any Incompatible Changes in the above Changelog, outline how users of prior versions can upgrade once this PR lands or when reviewers are testing locally.  A common upgrading step is "Database reset and re-index required".*

## Checklist for your Pull Request (PR)

  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I added new DB indices, I checked, that they are not redundant with PGHero or other tools.
  - [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

2024-05-23 23:57 UTC, Dioliode approved these changes
DioX

2024-06-06 11:13 UTC, sl1depengwyn requested changes

2024-06-06 11:13 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/utility/token_instance_metadata_refetch_attempt.ex
> +  def get_retries_number(token_contract_address_hash, token_id) do
```suggestion
  @spec get_retries_number(Hash.Address.t(), non_neg_integer()) :: {non_neg_integer(), DateTime.t()} | nil
```

2024-06-06 11:13 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/on_demand/token_instance_metadata_refetch.ex
> +    case {:fetched_metadata, MetadataRetriever.fetch_json(result, token_id, normalized_token_id, from_base_uri?)} do
Probably it makes sense to add nil clause to `MetadataRetriever.fetch_json` in order to not flood the logs with errors about invalid contracts.

2024-06-06 11:13 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/utility/token_instance_metadata_refetch_attempt.ex
> +    field(:retries_number, :integer, primary_key: false)
```suggestion
    field(:token_id, :decimal, primary_key: true, null: true)
```

2024-06-06 11:13 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/on_demand/token_instance_metadata_refetch.ex
> +        )
Shouldn't we reflect new metadata in the database?

2024-06-06 11:15 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex
> +        |> Chain.select_repo(@api_true).preload([:owner, :token])
Do we need :token preload here? We can pass already fetched `token` in `TokenInstanceMetadataRefetchOnDemand.trigger_refetch(token_instance)` call

2024-06-06 11:15 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/routers/tokens_api_v2_router.ex
> +    get("/:address_hash_param", V2.TokenController, :token)
Seems you missed `/bridged` which was in origin api_router.ex
```
  if Application.compile_env(:explorer, Explorer.Chain.BridgedToken)[:enabled] do
    get("/bridged", V2.TokenController, :bridged_tokens_list)
  end
```

2024-06-06 11:15 UTC, nikitosing commented on apps/indexer/lib/indexer/fetcher/on_demand/token_instance_metadata_refetch.ex
> +    end
Why did you distinct these 2 clauses? Shouldn't we union them?

2024-06-06 11:15 UTC, nikitosing commented on apps/indexer/lib/indexer/fetcher/on_demand/token_instance_metadata_refetch.ex
> +        )
Is it new event? I think you need to add this event at least here https://github.com/blockscout/blockscout/blob/25039ca7317734716a99bac6e501656187dcc059/apps/explorer/lib/explorer/chain/events/publisher.ex#L6 and handle it in appropriate channel

2024-06-06 11:20 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex
> +        |> Chain.select_repo(@api_true).preload([:owner, :token])
Maybe we can do `Chain.select_repo(@api_true).preload([:owner, token: token])`

2024-06-06 11:42 UTC, vbaranov commented on apps/explorer/lib/explorer/utility/token_instance_metadata_refetch_attempt.ex
> +    field(:retries_number, :integer, primary_key: false)
Could you tell me what is the reason for allowing a null token id?

2024-06-06 11:49 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/routers/tokens_api_v2_router.ex
> +    get("/:address_hash_param", V2.TokenController, :token)
Processed in https://github.com/blockscout/blockscout/pull/10097/commits/842f6f12f51239c2c0e10dfb7695a7bebd97b912

2024-06-06 11:50 UTC, vbaranov commented on apps/explorer/lib/explorer/utility/token_instance_metadata_refetch_attempt.ex
> +  def get_retries_number(token_contract_address_hash, token_id) do
Processed in https://github.com/blockscout/blockscout/pull/10097/commits/842f6f12f51239c2c0e10dfb7695a7bebd97b912

2024-06-06 11:50 UTC, vbaranov commented on apps/explorer/lib/explorer/utility/token_instance_metadata_refetch_attempt.ex
> +  def get_retries_number(token_contract_address_hash, token_id) do
Processed in https://github.com/blockscout/blockscout/pull/10097/commits/842f6f12f51239c2c0e10dfb7695a7bebd97b912

2024-06-06 11:56 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex
> +        |> Chain.select_repo(@api_true).preload([:owner, :token])
no, we don't need it at all

2024-06-06 11:59 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex
> +        |> Chain.select_repo(@api_true).preload([:owner, :token])
I think it won't work

2024-06-07 09:44 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/utility/token_instance_metadata_refetch_attempt.ex
> +    field(:retries_number, :integer, primary_key: false)
I thought null token id is possible, now I see that this is not the case, but then we need to reflect it in the migrationhttps://github.com/blockscout/blockscout/blob/842f6f12f51239c2c0e10dfb7695a7bebd97b912/apps/explorer/priv/repo/migrations/20240520075414_create_token_instance_metadata_refetch_attempts_table.exs#L7

2024-06-07 11:22 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex
> +        |> Chain.select_repo(@api_true).preload([:owner, :token])
`%Instance{token_instance | token: token}` is an alternative

2024-06-10 12:14 UTC, vbaranov commented on apps/indexer/lib/indexer/fetcher/on_demand/token_instance_metadata_refetch.ex
> +    end
Yes, it seems doesn't make sense to distinguish them. Processed in https://github.com/blockscout/blockscout/pull/10097/commits/49c5a295cbffd699c0f27cc1b43dc48ce1acdffa.

2024-06-10 12:14 UTC, vbaranov commented on apps/indexer/lib/indexer/fetcher/on_demand/token_instance_metadata_refetch.ex
> +        )
Exactly. Processed in https://github.com/blockscout/blockscout/pull/10097/commits/49c5a295cbffd699c0f27cc1b43dc48ce1acdffa.

2024-06-10 12:14 UTC, vbaranov commented on apps/explorer/lib/explorer/utility/token_instance_metadata_refetch_attempt.ex
> +    field(:retries_number, :integer, primary_key: false)
Agree. Processed in https://github.com/blockscout/blockscout/pull/10097/commits/49c5a295cbffd699c0f27cc1b43dc48ce1acdffa.

2024-06-10 12:32 UTC, vbaranov commented on apps/indexer/lib/indexer/fetcher/on_demand/token_instance_metadata_refetch.ex
> +    case {:fetched_metadata, MetadataRetriever.fetch_json(result, token_id, normalized_token_id, from_base_uri?)} do
Good catch. Processed in https://github.com/blockscout/blockscout/pull/10097/commits/4f466727c051ae9aab3b9931e6a371ac6b8ac301.

2024-06-10 12:38 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex
> +        |> Chain.select_repo(@api_true).preload([:owner, :token])
This preload existed before the changes. I'd suggest solving this in a separate PR. I created a task https://github.com/blockscout/blockscout/issues/10219.

2024-06-10 13:09 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/routers/tokens_api_v2_router.ex
> +end
I processed the separation of endpoints in order they were using proper pipelines inside the common scope https://github.com/blockscout/blockscout/pull/10097/commits/c8d3aedcbd89b219f3e45d97a5b35ef15bb001b2. So, only path endpoint currently uses `: api_v2_no_forgery_protect ` pipeline. However, I am not sure the separation of `NoForgeryProtectRouter` to a separate file will work.

2024-06-12 10:38 UTC, vbaranov commented on apps/indexer/lib/indexer/fetcher/on_demand/token_instance_metadata_refetch.ex
> +        )
Processed in https://github.com/blockscout/blockscout/pull/10097/commits/eaae2fbba72b82b36b4f10c2f629e23e81147684

2024-06-12 10:49 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex
> +        |> Chain.select_repo(@api_true).preload([:owner, :token])
Originally, I wrongly answered. Preload existed, but another one: :owner. Indeed, I added :token preload. And, indeed, it seems is redundant, since we already fetched it from the DB in the previous steps. Processed in https://github.com/blockscout/blockscout/pull/10097/commits/35e8774f2cc95f3bc2d199c147b919fe0bfc7a10.

2024-06-13 08:03 UTC, sl1depengwyn approved these changes

2024-06-13 11:19 UTC, nikitosing approved these changes

2024-06-13 11:20 UTC, merged