Add Celestia blobs support to Optimism batches fetcher
blockscout/blockscout pull request #10199
Opened 2024-06-05 11:24 UTC by varasev

Closes https://github.com/blockscout/blockscout/issues/10198.

This PR adds Celestia blobs handling to `Indexer.Fetcher.Optimism.TxnBatch` module and saving blob's metadata to the database. For EIP-4844 blobs the metadata is also saved.

New API routes were added:

- `/optimism/txn-batches/:l2_block_range_start/:l2_block_range_end` allows to limit displaying batches by the specified L2 block range. There is no `/optimism/txn-batches/:l2_block_range_start/:l2_block_range_end/count` handle, so UI `/batches` page should hide the total number of batches when using the explicit range. `l2_block_range_start` must be less than or equal to `l2_block_range_end`.

- `/optimism/txn-batch-by-celestia-blob/:commitment/:height` outputs L1 batch info by Celestia blob's commitment and height. Requests and response examples (for Optimism Celestia Raspberry):

   ```
   http://localhost:4000/api/v2/optimism/txn-batch-by-celestia-blob/0xf1a51990b5a358a2376e85648b489138ca38533e2b86e0283d41ceeebcf058ea/760960
   ```

   or

   ```
   http://localhost:4000/api/v2/optimism/txn-batch-by-celestia-blob/0x3834d3a92ede97db07defc291c848b6085389c236f88c52b67a933271f316fee/760961
   ```

   requests will respond with

   ```
   {
     "l1_timestamp": "2023-12-20T10:17:24.000000Z",
     "l1_transaction_hash": "0xf41211e966ec23032dde713d1f775ae5cb07dc5e15951281e6844d74cc02a930,0x9abc0df13890e8c0818b448b15056ecd96368dc2b4f625c1232285e05e5b3826",
     "l1_transactions": [
       {
         "blob_commitment": "0xf1a51990b5a358a2376e85648b489138ca38533e2b86e0283d41ceeebcf058ea",
         "blob_height": 760960,
         "l1_timestamp": "2023-12-20T10:17:12.000000Z",
         "l1_transaction_hash": "0xf41211e966ec23032dde713d1f775ae5cb07dc5e15951281e6844d74cc02a930"
       },
       {
         "blob_commitment": "0x3834d3a92ede97db07defc291c848b6085389c236f88c52b67a933271f316fee",
         "blob_height": 760961,
         "l1_timestamp": "2023-12-20T10:17:24.000000Z",
         "l1_transaction_hash": "0x9abc0df13890e8c0818b448b15056ecd96368dc2b4f625c1232285e05e5b3826"
       }
     ],
     "l2_block_number_from": 29996,
     "l2_block_number_to": 33082
   }
   ```

   - `l1_transaction_hash` field can have more than one L1 tx hash (comma-separated).
   - `l1_timestamp` contains the timestamp of the last L1 transaction in the list.
   - `l1_transactions` array represents the list of L1 transactions with the corresponding blob metadata (commitment and height), sorted chronologically.
   - `l2_block_number_from` and `l2_block_number_to` represent L2 block range of the batch.

- `/blocks/:block_hash_or_number` API route was extended to show L1 batch info (where the specified L2 block relates to). Example:

   ```
   {
     ...
     "l1_batch": {
       "celestia_blobs": [
         {
           "commitment": "0xf1a51990b5a358a2376e85648b489138ca38533e2b86e0283d41ceeebcf058ea",
           "height": 760960,
           "l1_timestamp": "2023-12-20T10:17:12.000000Z",
           "l1_transaction_hash": "0xf41211e966ec23032dde713d1f775ae5cb07dc5e15951281e6844d74cc02a930",
           "namespace": "0x00000000000000000000000000000000000000000008e5f679bf7116cb"
         },
         {
           "commitment": "0x3834d3a92ede97db07defc291c848b6085389c236f88c52b67a933271f316fee",
           "height": 760961,
           "l1_timestamp": "2023-12-20T10:17:24.000000Z",
           "l1_transaction_hash": "0x9abc0df13890e8c0818b448b15056ecd96368dc2b4f625c1232285e05e5b3826",
           "namespace": "0x00000000000000000000000000000000000000000008e5f679bf7116cb"
         }
       ],
       "l1_timestamp": "2023-12-20T10:17:24.000000Z",
       "l1_transaction_hash": "0xf41211e966ec23032dde713d1f775ae5cb07dc5e15951281e6844d74cc02a930,0x9abc0df13890e8c0818b448b15056ecd96368dc2b4f625c1232285e05e5b3826"
     },
     ...
   }
   ```

   - `l1_transaction_hash` field can have more than one L1 tx hash (comma-separated).
   - `l1_timestamp` contains the timestamp of the last L1 transaction in the list.
   - `celestia_blobs` array contains the blobs (with metadata) related to the L1 batch, sorted chronologically. In case of EIP-4844 blobs there will be `eip4844_blobs` list instead of `celestia_blobs`. If there are no blobs, such `*_blobs` fields will be absent.

A new optional env variable `INDEXER_OPTIMISM_L1_BATCH_CELESTIA_BLOBS_API_URL` was added to define URL to blobs indexer service. Example: `http://localhost:8050/api/v1/celestia/blob`. If the URL is not defined, Celestia blobs will be skipped.

## Checklist for your Pull Request (PR)

  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [x] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [x] If I added new DB indices, I checked, that they are not redundant with PGHero or other tools.
  - [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

2024-06-24 20:50 UTC, akolotov requested changes

2024-06-24 20:50 UTC, akolotov commented on apps/indexer/lib/indexer/fetcher/optimism/txn_batch.ex
> +  defp first_byte(tx_input) when byte_size(tx_input) > 0 do
Is this equal to
```
defp first_byte(<<
           version_byte::binary-size(1),
           _rest::binary
         >>) do
version_byte
end
```

2024-06-24 20:50 UTC, akolotov commented on apps/indexer/lib/indexer/fetcher/optimism/txn_batch.ex
> +        next_blob_id = next_blob_id(List.last(new_blobs_acc))
Does it make sense to make the field `id` with auto increment so there will be no need execute the DB query just to get the next id for the entity?

2024-07-05 06:26 UTC, varasev commented on apps/block_scout_web/lib/block_scout_web/views/api/v2/optimism_view.ex
> +          "l2_block_range" => "#{from}-#{to}",
The main purpose of the `l2_block_range` field is to show the range of L2 blocks included into a batch. Of course, it can also be used to calculate the number of L2 blocks, but this is secondary

2024-07-05 11:14 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism/txn_batch.ex
> +        next_blob_id = next_blob_id(List.last(new_blobs_acc))
I would keep it as it is because there can be a case when the same blob is rewritten by another L1 transaction (with bigger manual id) within the same database import. The manual ids needed to set the right order

2024-07-05 12:12 UTC, varasev commented on apps/explorer/lib/explorer/chain/optimism/frame_sequence.ex
> +  @default_paging_options %PagingOptions{page_size: 50}
Thanks, fixed in https://github.com/blockscout/blockscout/commit/6387592084f054972b4c838acdb2d7fa67a5c1e3

2024-07-05 12:12 UTC, varasev commented on apps/explorer/lib/explorer/chain/optimism/frame_sequence.ex
> +        "l2_block_range" => "#{l2_block_number_from}-#{l2_block_number_to}",
Done in https://github.com/blockscout/blockscout/commit/6387592084f054972b4c838acdb2d7fa67a5c1e3

2024-07-05 12:12 UTC, varasev commented on apps/explorer/lib/explorer/chain/optimism/frame_sequence.ex
>    schema "op_frame_sequences" do
Done in https://github.com/blockscout/blockscout/commit/6387592084f054972b4c838acdb2d7fa67a5c1e3

2024-07-05 12:13 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism/txn_batch.ex
> +  defp first_byte(tx_input) when byte_size(tx_input) > 0 do
Not quite as the right solution is `version_byte::size(8)`. The `version_byte::binary-size(1)` would return `<<version_byte>>` instead of `version_byte`. Fixed in https://github.com/blockscout/blockscout/commit/6387592084f054972b4c838acdb2d7fa67a5c1e3

2024-07-09 22:30 UTC, akolotov approved these changes

2024-07-10 10:39 UTC, vbaranov commented on apps/indexer/lib/indexer/fetcher/optimism.ex
> +      nil ->
Which condition in `with` could return `nil`?

2024-07-10 10:39 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/transaction.ex
> +        on: b.hash == t.block_hash and b.consensus == true,
Since you anyways check consensus == true, changing join by block numbers should work way faster.
```suggestion
        on: b.number == t.block_number and b.consensus == true,
```

2024-07-10 10:39 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/optimism/txn_batch.ex
> +        where: tb.frame_sequence_id == ^id,
Nitpick: extract:
```
tb in __MODULE__,
select: tb.l2_block_number,
where: tb.frame_sequence_id == ^id,
limit: 1
```

as a base query for clauses of edge_l2_block_number/2

2024-07-10 10:39 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
> +  def optimism_batch(conn, %{"batch_number" => batch_number} = params) do
Do we make a validation, that batch number input is non-negative integer?

2024-07-11 08:14 UTC, varasev commented on config/runtime.exs
Done in https://github.com/blockscout/blockscout/commit/4acbaebc0df56d87b86fc202c3974275c26301f0

2024-07-11 08:14 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism.ex
> +      nil ->
The `read_system_config` function can return `nil` there

2024-07-11 08:14 UTC, varasev commented on apps/explorer/lib/explorer/chain/optimism/txn_batch.ex
> +        where: tb.frame_sequence_id == ^id,
Done in https://github.com/blockscout/blockscout/commit/4acbaebc0df56d87b86fc202c3974275c26301f0

2024-07-11 08:15 UTC, varasev commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
> +  def optimism_batch(conn, %{"batch_number" => batch_number} = params) do
Done in https://github.com/blockscout/blockscout/commit/4acbaebc0df56d87b86fc202c3974275c26301f0

2024-07-11 14:10 UTC, vbaranov approved these changes

2024-07-11 14:58 UTC, merged