fix: include internal transactions in state change
blockscout/blockscout pull request #10210
Opened 2024-06-07 16:28 UTC by sl1depengwyn

Closes #8647
Fixes https://github.com/blockscout/blockscout/issues/8878
Fixes https://github.com/blockscout/blockscout/issues/10337

## Changelog

- Refactor and optimize preloads
- Take into account internal transactions

## Checklist for your Pull Request (PR)

  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I added new DB indices, I checked, that they are not redundant with PGHero or other tools.
  - [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

2024-06-07 23:39 UTC, GodArges commented
> Closes #8647
> 
> ## Changelog
> ## Checklist for your Pull Request (PR)
> * [ ]  If I added new functionality, I added tests covering it.
> * [ ]  If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
> * [ ]  I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
> * [ ]  If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables.
> * [ ]  If I added new DB indices, I checked, that they are not redundant with PGHero or other tools.
> * [ ]  If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

2024-06-07 23:44 UTC, GodArges requested changes
apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex

2024-07-10 09:39 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/models/transaction_state_helper.ex
> +        block: [miner: [:names, :smart_contract, :proxy_implementations]],
The miner should be EOA. Do we really need to make a preload of smart-contract and proxy_implementations?

2024-07-10 09:39 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/models/transaction_state_helper.ex
> +        from_address: [:names, :smart_contract, :proxy_implementations],
Transaction cannot be originated by smart-contract. The same question as above is applied here.

2024-07-10 09:39 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/transaction/state_change.ex
> +  def from_loss(%Transaction{} = tx) do
Please add spec and doc for this function

2024-07-10 09:39 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/transaction/state_change.ex
> +  def to_profit(%InternalTransaction{} = tx) do
Please add spec and doc for this function

2024-07-10 09:39 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/transaction/state_change.ex
> +  def native_coin_entries(transaction, coin_balances_before_tx) do
Please add spec and doc for this function

2024-07-10 12:19 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/models/transaction_state_helper.ex
> +        from_address: [:names, :smart_contract, :proxy_implementations],
Seems, it is not true for Arbitrum system transactions.

2024-07-10 12:19 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/models/transaction_state_helper.ex
> +        block: [miner: [:names, :smart_contract, :proxy_implementations]],
Seems, it is not true for Optimism https://optimism.blockscout.com/block/122505314

2024-07-10 15:59 UTC, vbaranov approved these changes

2024-07-16 09:41 UTC, Qwerty5Uiop approved these changes

2024-07-16 11:20 UTC, fedor-ivn commented on apps/explorer/lib/explorer/chain/transaction/state_change.ex
> +  end
Don't bother my comment if I am wrong, but I think we could use here regular function instead of multiple anonymous functions

```suggestion
  def update_coin_balances_from_tx(coin_balances, tx, block) do
    coin_balances =
      coin_balances
      |> update_balance(tx.from_address_hash, &Wei.sub(&1, from_loss(tx)))
      |> update_balance(tx.to_address_hash, &Wei.sum(&1, to_profit(tx)))
      |> update_balance(block.miner_hash, &Wei.sum(&1, miner_profit(tx, block)))

    if error?(tx) do
      coin_balances
    else
      tx.internal_transactions |> Enum.reduce(coin_balances, &update_coin_balances_from_internal_tx(&1, &2))
    end
  end

  defp update_balance(coin_balances, address_hash, update_fn) when is_nil(address_hash), 
    do: coin_balances
  
  defp update_balance(coin_balances, address_hash, update_function) do
    if Map.has_key?(coin_balances, address_hash) do
      Map.update(coin_balances, address_hash, @zero_wei, fn {address, balance} ->
        {address, update_function.(balance)}
      end)
    else
      coin_balances
    end
  end
```

2024-07-18 13:25 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/transaction/state_change.ex
> +  end
Good suggestion, thanks! Refactored here https://github.com/blockscout/blockscout/pull/10210/commits/b95bc189c0f3c31393d27b6dedc4a0f73dfb22b2

2024-07-19 12:52 UTC, merged