CDN
blockscout/blockscout pull request #10675
Opened 2024-08-29 16:25 UTC by nikitosing

Closes #8694

## Changelog

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/for-developers/information-and-settings/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

2024-11-11 16:57 UTC, vbaranov requested changes
Docker compose setup is broken because of this:
env file .../docker-compose/envs/common-nft-media-handler.env not found: stat .../docker-compose/envs/common-nft-media-handler.env: no such file or directory

Could we process NFT Media handler application such crash:
```
** (Mix) Could not start application nft_media_handler_dispatcher: NFTMediaHandlerDispatcher.Application.start(:normal, []) returned an error: shutdown: failed to start child: NFTMediaHandlerDispatcher.Queue
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:file_error, ~c"./dets/queue_storage", :enoent}}
            (nft_media_handler_dispatcher 6.9.0) lib/nft_media_handler_dispatcher/queue.ex:54: NFTMediaHandlerDispatcher.Queue.init/1
            (stdlib 6.1) gen_server.erl:2229: :gen_server.init_it/2
            (stdlib 6.1) gen_server.erl:2184: :gen_server.init_it/6
            (stdlib 6.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
```

2024-11-11 16:57 UTC, vbaranov commented on apps/nft_media_handler_dispatcher_interface/README.md
> +**TODO: Add description**
Please add 😄

2024-11-11 16:57 UTC, vbaranov commented on apps/nft_media_handler/README.md
> +**TODO: Add description**
Let's do this

2024-11-11 16:57 UTC, vbaranov commented on apps/nft_media_handler_dispatcher/README.md
> +**TODO: Add description**
Yep, suggest to do that.

2024-11-11 16:57 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/views/abi_encoded_value_view.ex
> +    ~H|<%= @spacing %><%=@html%>|
```suggestion
    ~H|<%= @spacing %><%= @html%>|
```

2024-11-11 16:57 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex
> +      # |> List.to_string()
Is this left accidentally?

2024-11-11 16:57 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex
> +      # |> List.to_string()
Btw, why it is commented here?

2024-11-11 16:57 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/token/instance.ex
> +  * `media_urls` - map of media urls, key is resolution value is url
```suggestion
  * `media_urls` - map of media urls, key is resolution, value is url
```

2024-11-11 16:57 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/token/instance.ex
> +  * `cdn_upload_error` - error while processing(resizing)/uploading media to cdn
```suggestion
  * `cdn_upload_error` - error while processing(resizing)/uploading media to CDN
```

2024-11-11 16:57 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/token/instance.ex
> +  def set_media_urls({token_contract_address_hash, token_id}, urls, {type, subtype}) do
Please add spec && doc for all new functions in this module.

2024-11-11 16:57 UTC, vbaranov commented on apps/explorer/priv/repo/migrations/20240729181753_add_cdn_upload_error.exs
Can we merge this migration with `apps/explorer/priv/repo/migrations/20240708152519_add_nft_media_urls.exs`?

2024-11-11 16:57 UTC, vbaranov commented on apps/nft_media_handler/mix.exs
> +      # {:sibling_app_in_umbrella, in_umbrella: true}
Do we need to keep these commented lines?

2024-11-11 16:57 UTC, vbaranov commented on apps/nft_media_handler_dispatcher/lib/nft_media_handler_dispatcher.ex
> +  @spec get_media_url_from_metadata(nil | map()) :: nil | binary()
Doc attirbute is missing

2024-11-11 16:57 UTC, vbaranov commented on apps/nft_media_handler_dispatcher/lib/nft_media_handler_dispatcher/application.ex
> +         Application.get_env(:nft_media_handler, :uniqueness_cache_name),
replacing anywhere `uniqueness_cache` to `cache_uniqueness` will increase readability, I guess? wdyt?

2024-11-11 16:57 UTC, vbaranov commented on apps/nft_media_handler/lib/nft_media_handler.ex
> +  def prepare_and_upload_inner({"image", _} = media_type, initial_image_binary, url, r2_folder) do
```suggestion
  defp prepare_and_upload_inner({"image", _} = media_type, initial_image_binary, url, r2_folder) do
```

2024-11-11 16:57 UTC, vbaranov commented on apps/nft_media_handler/lib/nft_media_handler.ex
> +  @spec prepare_and_upload_by_url(binary(), binary()) :: :error | {map(), {binary(), binary()}}
Doc attribute is missing

2024-11-11 16:57 UTC, vbaranov commented on apps/nft_media_handler/lib/nft_media_handler.ex
> +  def image_to_binary(resized_image, _file_name, extension) when extension in [".jpg", ".png", ".webp"] do
spec && doc is missing.

2024-11-11 16:57 UTC, vbaranov commented on apps/nft_media_handler/lib/nft_media_handler.ex
> +  def prepare_and_upload_inner({"video", _} = media_type, body, url, r2_folder) do
```suggestion
  defp prepare_and_upload_inner({"video", _} = media_type, body, url, r2_folder) do
```

2024-11-11 16:57 UTC, vbaranov commented on apps/nft_media_handler/lib/nft_media_handler/image/resizer.ex
> +  def resize(image, url, extension) do
spec && doc

2024-11-11 16:57 UTC, vbaranov commented on apps/nft_media_handler/lib/nft_media_handler/image/resizer.ex
> +  def generate_file_name(url, extension, size) do
spec && doc

2024-11-11 16:57 UTC, vbaranov commented on apps/nft_media_handler/lib/nft_media_handler/media/fetcher.ex
Please cover all public functions in this module with doc && spec attributes

2024-11-11 16:57 UTC, vbaranov commented on apps/nft_media_handler/lib/nft_media_handler/r2/uploader.ex
> +  @spec upload_image(binary(), binary(), binary()) :: {:error, any()} | {:ok, any(), nonempty_binary()}
Please add doc

2024-11-11 16:57 UTC, vbaranov commented on apps/nft_media_handler_dispatcher/lib/nft_media_handler_dispatcher/backfiller.ex
> +  def get_instances(amount) do
spec && doc

2024-11-11 16:57 UTC, vbaranov commented on apps/nft_media_handler_dispatcher/lib/nft_media_handler_dispatcher/queue.ex
> +  @spec process_new_instance(any()) :: any()
doc is missing

2024-11-11 16:57 UTC, vbaranov commented on apps/nft_media_handler_dispatcher_interface/lib/nft_media_handler_dispatcher_interface.ex
Please add doc && spec to all public functions in this module

2024-11-18 11:52 UTC, nikitosing commented on config/config_helper.exs
> +  @spec parse_url_env_var(String.t(), boolean()) :: String.t() | nil
Created an issue https://github.com/blockscout/blockscout/issues/11220!

2024-11-18 20:14 UTC, nikitosing commented
@vbaranov processed everything in 48bc6b157dd66144a08ebea8af1d31f4fb44ca2c

2024-12-04 10:25 UTC, vbaranov commented on apps/nft_media_handler/mix.exs
> +      version: "6.9.0",
The current version of the app is 6.9.2.
```suggestion
      version: "6.9.2",
```

2024-12-04 10:25 UTC, vbaranov commented on apps/nft_media_handler/mix.exs
> +      version: "6.9.0",
Also, it requires extending `bin/version_bump.sh` script to process changing this version from it.

2024-12-04 10:25 UTC, vbaranov commented on apps/explorer/priv/repo/migrations/20240708152519_add_nft_media_urls.exs
Let's merge DB migrations into one.

2024-12-05 08:54 UTC, vbaranov commented on apps/nft_media_handler/lib/nft_media_handler.ex
> +  defp maybe_process_ipfs("Qm" <> _ = result) do
How about processing CID v1 https://github.com/blockscout/blockscout/blob/ee8f527f1e2e72947adfca22ab6738cd095f7e2c/apps/explorer/lib/explorer/token/metadata_retriever.ex#L610 as well?

2024-12-05 08:54 UTC, vbaranov commented on apps/nft_media_handler/lib/nft_media_handler.ex
> +  defp maybe_process_ipfs("#{@ipfs_protocol}ipfs/" <> right) do
I suppose it worth for consistency to equalize clauses with that we have in https://github.com/blockscout/blockscout/blob/ee8f527f1e2e72947adfca22ab6738cd095f7e2c/apps/explorer/lib/explorer/token/metadata_retriever.ex#L581 function.

2024-12-05 08:54 UTC, vbaranov commented on apps/nft_media_handler/lib/nft_media_handler/dispatcher.ex
> +  # shouldn't happen
Do we need it then?

2024-12-05 08:54 UTC, vbaranov commented on apps/nft_media_handler/lib/nft_media_handler/image/resizer.ex
> +  @sizes [{60, "60x60"}, {250, "250x250"}, {500, "500x500"}]
It seems we can generate "60x60" based on the int value 60. Then, @sizes list can be simplified to [60, 250, 500]. Wdyt?

2024-12-05 08:54 UTC, vbaranov commented on apps/nft_media_handler/lib/nft_media_handler/media/fetcher.ex
> +  defp media_type(media_src, headers) when not is_nil(media_src) do
We also have `media_type` function defined in `BlockScoutWeb.Tokens.Instance.OverviewView` module. Do you think we could stick to a single implementation?

2024-12-05 08:54 UTC, vbaranov commented on apps/nft_media_handler/lib/nft_media_handler/r2/uploader.ex
> +    with %ExAws.Operation.S3{} = request <- ExAws.S3.put_object(r2_config[:bucket_name], file_path, file_binary) do
Should we return {:error, reason} in the `else` of `with` statement as well? Otherwise, `no return` will be triggered.

2024-12-05 10:59 UTC, nikitosing commented on apps/nft_media_handler/lib/nft_media_handler/image/resizer.ex
> +  @sizes [{60, "60x60"}, {250, "250x250"}, {500, "500x500"}]
Yes, you are right. But in my opinion current variant is more readable and more effective than string concatenation on each access to @sizes, wdyt?

2024-12-05 12:03 UTC, sl1depengwyn commented on apps/nft_media_handler/lib/nft_media_handler/dispatcher_interface.ex
> +  Documentation for `NFTMediaHandler.DispatcherInterface`.
I think we need to put some actual doc here

2024-12-05 12:16 UTC, sl1depengwyn commented on apps/nft_media_handler/test/nft_media_handler_test.exs
> +end
I think we do not need this file

2024-12-05 12:17 UTC, sl1depengwyn commented on apps/nft_media_handler/test/test_helper.exs
> +ExUnit.start()
Together with test folder probably

2024-12-05 12:18 UTC, sl1depengwyn commented on apps/nft_media_handler/.formatter.exs
> +]
I think we do not separate formatter file as we have one in the root

2024-12-05 12:20 UTC, sl1depengwyn commented on docker-compose/docker-compose.yml
> +        RELEASE_VERSION: 6.9.0
Update release version

2024-12-05 12:40 UTC, nikitosing commented on apps/indexer/lib/indexer/nft_media_handler/queue.ex
> +          Enum.map_reduce(backfill_items, [], fn {url, instances}, acc ->
but here also collected list with urls

2024-12-05 14:03 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/nft_media_handler/queue.ex
> +          Enum.map_reduce(backfill_items, [], fn {url, instances}, acc ->
ah, okay, I see

2024-12-05 14:04 UTC, sl1depengwyn approved these changes

2024-12-06 11:15 UTC, nikitosing commented on apps/nft_media_handler/lib/nft_media_handler.ex
> +  defp maybe_process_ipfs("Qm" <> _ = result) do
Fixed in 401f9c78f7313f44959744adc6e45d474865c664

2024-12-06 11:16 UTC, nikitosing commented on apps/nft_media_handler/lib/nft_media_handler.ex
> +  defp maybe_process_ipfs("#{@ipfs_protocol}ipfs/" <> right) do
Fixed in 401f9c78f7313f44959744adc6e45d474865c664

2024-12-06 11:16 UTC, nikitosing commented on apps/nft_media_handler/lib/nft_media_handler/media/fetcher.ex
> +  defp media_type(media_src, headers) when not is_nil(media_src) do
Fixed in 401f9c78f7313f44959744adc6e45d474865c664

2024-12-06 14:21 UTC, vbaranov commented on apps/nft_media_handler/lib/nft_media_handler/image/resizer.ex
> +  @sizes [{60, "60x60"}, {250, "250x250"}, {500, "500x500"}]
I still think this format is strange. But ok, this is not so critical and subjective. Let's leave it as is.

2024-12-06 14:35 UTC, vbaranov approved these changes

2024-12-06 14:35 UTC, merged