feat: return `authorizationList` for EIP-7702 transactions in `/addresses/:address` response
blockscout/blockscout pull request #10776
Opened 2024-09-16 14:31 UTC by AllFi

*[GitHub keywords to close any associated issues](https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/)*

## Motivation

*Why we should merge these changes.  If using GitHub keywords to close [issues](https://github.com/poanetwork/blockscout/issues), this is optional as the motivation can be read on the issue page.*

## Changelog

### Enhancements

*Things you added that don't break anything.  Regression tests for Bug Fixes count as Enhancements.*

### Bug Fixes

*Things you changed that fix bugs.  If a fixes a bug, but in so doing adds a new requirement, removes code, or requires a database reset and reindex, the breaking part of the change should be added to Incompatible Changes below also.*

### Incompatible Changes

*Things you broke while doing Enhancements and Bug Fixes.  Breaking changes include (1) adding new requirements and (2) removing code.  Renaming counts as (2) because a rename is a removal followed by an add.*

## Upgrading

*If you have any Incompatible Changes in the above Changelog, outline how users of prior versions can upgrade once this PR lands or when reviewers are testing locally.  A common upgrading step is "Database reset and re-index required".*

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/for-developers/information-and-settings/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

2024-09-23 12:46 UTC, AllFi commented on apps/explorer/priv/repo/migrations/20240904161254_create_signed_authorizations.exs
> +      add(:s, :numeric, precision: 100, null: false)
Decided to keep them for now, but it makes sense to revisit this once we have a clearer understanding of how this EIP should be integrated into the Blockscout UI.

2024-09-27 11:20 UTC, k1rill-fedoseev requested changes

2024-09-27 11:20 UTC, k1rill-fedoseev commented on apps/explorer/lib/explorer/chain/import/runner/signed_authorizations.ex
> +        :logs
```suggestion
        :block_referencing,
        :signed_authorizations,
        :signed_authorizations
```

2024-09-27 11:20 UTC, k1rill-fedoseev commented on apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
> +  def to_signed_authorization(map) do
Let's move this to `apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex`, or even better to a separate module to be consistent with how `block.withdrawals` or `receipt.logs` are handled.

2024-10-01 13:10 UTC, AllFi commented on apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
> +  def to_signed_authorization(map) do
Done in the https://github.com/blockscout/blockscout/pull/10776/commits/d3eff0dfd41cebc52ea35651a435c0297ae94b37.

2024-10-02 09:31 UTC, vbaranov reviewed
The changes look good to me in general. My only concern is that it is implied, that new functionality: an additional block import step, and preloads of signed authorisations, are spread to all chain types. Don't we want to reduce their applicability to only `ethereum` chain type?

2024-10-02 10:23 UTC, AllFi commented
Thank you for the review!

> The changes look good to me in general. My only concern is that it is implied, that new functionality: an additional block import step, and preloads of signed authorisations, are spread to all chain types. Don't we want to reduce their applicability to only ethereum chain type?

We briefly discussed this with @k1rill-fedoseev [here](https://www.notion.so/EIP-7702-1033d73641f880f18b2feaa3d2526c0a?d=1043d73641f8807fa11c001c3cafb2fb&pvs=4#1033d73641f8806d8250ca843dd1482b) and agreed that this EIP will likely be adopted by the majority of chains. I believe the additional block import step shouldn't significantly affect performance if no signed authorizations need to be saved. Since the `signed_authorizations` table will be empty and these preloads only occur for single transaction and single address requests, I don't think they will have noticeable effect on performance as well (though I could be wrong). That’s why I believe it's better to support this for all chains from the start, to avoid the need for additional changes later.

What do you think?

2024-10-02 10:44 UTC, vbaranov commented
> We briefly discussed this with @k1rill-fedoseev [here](https://www.notion.so/EIP-7702-1033d73641f880f18b2feaa3d2526c0a?d=1043d73641f8807fa11c001c3cafb2fb&pvs=4#1033d73641f8806d8250ca843dd1482b) and agreed that this EIP will likely be adopted by the majority of chains. I believe the additional block import step shouldn't significantly affect performance if no signed authorizations need to be saved. Since the `signed_authorizations` table will be empty and these preloads only occur for single transaction and single address requests, I don't think they will have noticeable effect on performance as well (though I could be wrong). That’s why I believe it's better to support this for all chains from the start, to avoid the need for additional changes later.
> 
> What do you think?

yep, this sounds reasonable to keep it as is then.

2024-10-02 10:45 UTC, vbaranov approved these changes

2024-10-03 09:25 UTC, k1rill-fedoseev approved these changes

2024-10-03 10:28 UTC, merged