feat: support EIP-7702 in `/address/:address` endpoint
blockscout/blockscout pull request #10799
Opened 2024-09-19 13:28 UTC by AllFi

*[GitHub keywords to close any associated issues](https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/)*

## Motivation

*Why we should merge these changes.  If using GitHub keywords to close [issues](https://github.com/poanetwork/blockscout/issues), this is optional as the motivation can be read on the issue page.*

## Changelog

### Enhancements

*Things you added that don't break anything.  Regression tests for Bug Fixes count as Enhancements.*

### Bug Fixes

*Things you changed that fix bugs.  If a fixes a bug, but in so doing adds a new requirement, removes code, or requires a database reset and reindex, the breaking part of the change should be added to Incompatible Changes below also.*

### Incompatible Changes

*Things you broke while doing Enhancements and Bug Fixes.  Breaking changes include (1) adding new requirements and (2) removing code.  Renaming counts as (2) because a rename is a removal followed by an add.*

## Upgrading

*If you have any Incompatible Changes in the above Changelog, outline how users of prior versions can upgrade once this PR lands or when reviewers are testing locally.  A common upgrading step is "Database reset and re-index required".*

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/for-developers/information-and-settings/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

2024-09-27 11:38 UTC, k1rill-fedoseev requested changes

2024-09-27 11:38 UTC, k1rill-fedoseev commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex
> +      :signed_authorizations => :optional
I'm very concerned about this preload, since it's gonna return very long list for some rare addresses.

2024-09-27 11:38 UTC, k1rill-fedoseev commented on apps/explorer/lib/explorer/chain/address.ex
> +        has_many(:signed_authorizations, SignedAuthorization, foreign_key: :authority, references: :hash)
I think we need an index on `authority` to be able to do such preload efficiently

2024-09-27 11:38 UTC, k1rill-fedoseev commented on apps/explorer/lib/explorer/chain/smart_contract/proxy/eip_7702.ex
> +  defp get_delegate_address(contract_bytecode) do
Let's come up with a single helper function that can be used in `eoa_with_code?` too.

2024-09-27 11:38 UTC, k1rill-fedoseev commented on apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
> +    # TODO: do we need to handle EIP-7702 case here?
Looks like this function is only used for the old UI, so no need to change it.

2024-09-27 11:38 UTC, k1rill-fedoseev commented on apps/explorer/lib/explorer/chain/address/counters.ex
>      if Address.smart_contract?(address) do
Yes, let's do 
```suggestion
    if Address.smart_contract?(address) and not Address.eoa_with_code?(address) do
```

2024-10-02 11:32 UTC, AllFi commented on apps/explorer/lib/explorer/chain/address/counters.ex
>      if Address.smart_contract?(address) do
Done in https://github.com/blockscout/blockscout/pull/10799/commits/a14ef70025a614eff9e03955ec761c3fd533a5cc

2024-10-02 11:33 UTC, AllFi commented on apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
> +    # TODO: do we need to handle EIP-7702 case here?
Removed the todo comment

2024-10-02 11:33 UTC, AllFi commented on apps/explorer/lib/explorer/chain/address.ex
> +        has_many(:signed_authorizations, SignedAuthorization, foreign_key: :authority, references: :hash)
I've added the index in https://github.com/blockscout/blockscout/pull/10799/commits/a14ef70025a614eff9e03955ec761c3fd533a5cc

2024-10-02 11:33 UTC, AllFi commented on apps/explorer/lib/explorer/chain/smart_contract/proxy/eip_7702.ex
> +  defp get_delegate_address(contract_bytecode) do
Done in https://github.com/blockscout/blockscout/pull/10799/commits/a14ef70025a614eff9e03955ec761c3fd533a5cc

2024-10-02 11:38 UTC, AllFi commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex
> +      :signed_authorizations => :optional
I replaced `has_many` with `has_one` in `address.ex` (which, according to the documentation, just applies `LIMIT 1`). I’m not sure if it's the best solution, but it works and avoids large preloads without introducing a lot of new code.

2024-10-03 09:31 UTC, k1rill-fedoseev requested changes

2024-10-03 09:31 UTC, k1rill-fedoseev commented on apps/explorer/priv/repo/migrations/20240904161254_create_signed_authorizations.exs
> +    create(index(:signed_authorizations, [:authority]))
When we'll have an API for displaying all authorizations by address, or an API for latest transactions with given authorizations, we'll need an `(authority, nonce)` index, and index on `authority` won't be needed anymore.
```suggestion
    create(index(:signed_authorizations, [:authority, :nonce]))
```

2024-10-03 10:36 UTC, merged