feat: Open access to re-fetch metadata button for token instances without metadata initially fetched
blockscout/blockscout pull request #10878
Opened 2024-10-04 11:39 UTC by vbaranov

## Motivation

Resolves https://github.com/blockscout/blockscout/issues/10877

## Changelog

Remove condition that metadata initially exists for NFT metadata re-fetch functionality.

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/for-developers/information-and-settings/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

2024-10-14 08:32 UTC, Qwerty5Uiop approved these changes

2024-10-14 08:39 UTC, fedor-ivn commented on apps/indexer/test/indexer/fetcher/on_demand/token_instance_metadata_refetch_test.exs
> +      Application.put_env(:explorer, :http_adapter, Explorer.Mox.HTTPoison)
Nitpick: It might be more readable to keep the code related to temporary environment variable changes together by using `on_exit/1`.

```suggestion
      Application.put_env(:explorer, :http_adapter, Explorer.Mox.HTTPoison)
      on_exit(fn ->
        Application.put_env(:explorer, :http_adapter, HTTPoison)
      end)
```

2024-10-14 16:09 UTC, vbaranov commented on apps/indexer/test/indexer/fetcher/on_demand/token_instance_metadata_refetch_test.exs
> +      Application.put_env(:explorer, :http_adapter, Explorer.Mox.HTTPoison)
Processed in https://github.com/blockscout/blockscout/pull/10878/commits/2591ce78353e96d0a45194e50e3f1ee958336cb6

2024-10-16 10:26 UTC, nikitosing requested changes
Let's add test (similar to `"do run the update on the token instance with no metadata fetched initially"`) to `apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs`

2024-10-17 12:45 UTC, vbaranov commented
> Let's add test (similar to `"do run the update on the token instance with no metadata fetched initially"`) to `apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_controller_test.exs`

Processed in https://github.com/blockscout/blockscout/pull/10878/commits/e0c1799f088bfc2d8e23182b88d6d63f5c35db5a

2024-10-17 14:16 UTC, nikitosing approved these changes

2024-10-17 14:36 UTC, merged