Multichain search
blockscout/blockscout pull request #11139
Opened 2024-11-05 09:32 UTC by vbaranov

Resolves https://github.com/blockscout/blockscout/issues/10652

## Motivation

Add support of filling the data multi-chain search DB.

## Changelog

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/for-developers/information-and-settings/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

2024-12-18 16:57 UTC, sl1depengwyn requested changes
about preloads, I suggest to not preload anything at all before calling MultichainSearch module and preload entites that we expect there, this way we do not need to keep in mind all places where import called, but we can be sure that associations were preloaded

2024-12-18 16:57 UTC, sl1depengwyn commented on config/runtime.exs
> +  enabled: ConfigHelper.parse_bool_env_var("MICROSERVICE_MULTICHAIN_SEARCH_ENABLED")
I understand that this comes from microservice template use, but maybe we can omit this variable and decide whether the service enabled via `MICROSERVICE_MULTICHAIN_SEARCH_URL`? I think this would be enough and we came up with a similar decision about stylus verifier internally

2024-12-18 16:57 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/microservice_interfaces/multichain_search.ex
> +        }) :: {:error, :disabled | <<_::416>> | Jason.DecodeError.t()} | {:ok, any()}
```suggestion
  @spec batch_import(%{
          addresses: [Address.t()],
          blocks: [Block.t()],
          transactions: [Transaction.t()]
        }) :: {:error, :disabled | String.t() | Jason.DecodeError.t()} | {:ok, any()}
```

Also, need to replace `alias Explorer.Chain.Hash` with `alias Explorer.Chain.{Address, Block, Hash, Transaction}`

2024-12-18 16:57 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/migrator/backfill_multichain_search_db.ex
> +          end)
maybe bring this closer to token transfer query

2024-12-18 16:57 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/migrator/backfill_multichain_search_db.ex
> +
in batch_import we expect that token field is tried to preload, though here we are not preload token, so all addresses will be formatted as non tokens.
I suggest to remove preloads from the previous request entirely as they are redundant as far as I can see, and preload necessary smart contract and token fields here after whole addresses list, this way we reduce number of requests to the database

2024-12-18 16:57 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/migrator/backfill_multichain_search_db.ex
> +  defp extract_address_from_result(result) do
what you think about proxy implementations here? they must be created in a some transaction, so they would be imported as created_contract_address here on other block, but what if they are predeployed? I think we need to add call to multichain search import to chainspec parser

2024-12-18 16:57 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/block/fetcher.ex
> +      })
here we have no any preloads I think

2024-12-18 16:57 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/import.ex
> +          | {:error, [Changeset.t()] | :timeout | :insert_to_multichain_search_db_failed}
where exactly this error may come from, as far as I see actual import is not affected with microservice communication

2024-12-18 17:06 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/migrator/backfill_multichain_search_db.ex
> +
correction: not entirely, but leave only address preloads itself
maybe even better option is to pass to microservice interface address hashes instead if addresses, however I'm not sure, but this way worth considering

2024-12-18 18:28 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/import.ex
> +          | {:error, [Changeset.t()] | :timeout | :insert_to_multichain_search_db_failed}
the spec of `import` function defines output as of `Import.all_result()` type `@spec import(Import.all_options()) :: Import.all_result()`. And one of the possible result of function execution is `_ -> {:error, :insert_to_multichain_search_db_failed}` now.

2024-12-18 18:35 UTC, vbaranov commented on apps/explorer/lib/explorer/migrator/backfill_multichain_search_db.ex
> +  @spec extract_address_from_result(Transaction.t() | InternalTransaction.t() | TokenTransfer.t() | Block.t()) :: list()
Processed in https://github.com/blockscout/blockscout/pull/11139/commits/781976d50da5368629401221370e4ed5d028a308

2024-12-18 18:50 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v1/health_controller.ex
> +    migration_status_finished? = migration.status == "completed"
Indeed, I missed that. Without handling in the case of disabled integration `/api/health/multichain-search-export` will throw an exception. I processed in https://github.com/blockscout/blockscout/pull/11139/commits/7269a3c8ad4bc91f858b0427485c43b68283f1eb.

2024-12-18 19:24 UTC, vbaranov commented on config/runtime.exs
> +  enabled: ConfigHelper.parse_bool_env_var("MICROSERVICE_MULTICHAIN_SEARCH_ENABLED")
Processed in https://github.com/blockscout/blockscout/pull/11139/commits/a00a51ccf79962ed06a2034c469238010625cb0b. PR description and related PR to the docs repo are updated accordingly.

2024-12-19 11:00 UTC, vbaranov commented
> about preloads, I suggest to not preload anything at all before calling MultichainSearch module and preload entites that we expect there, this way we do not need to keep in mind all places where import called, but we can be sure that associations were preloaded

@sl1depengwyn I processed the suggested preloads refactoring as we discussed internally. For proxy implementations, I created an enhancement request for the future https://github.com/blockscout/blockscout/issues/11491.

2024-12-19 11:04 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v1/health_controller.ex
> +  defp result(
Yes, but maybe even better to leave old format in v1 endpoint during one release, not sure if it worth it though

2024-12-19 12:16 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/microservice_interfaces/multichain_search.ex
> +  defp get_smart_contract_name(token), do: token.name
maybe rename argument to smart_contract

2024-12-19 12:16 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/microservice_interfaces/multichain_search.ex
> +      |> Repo.preload([:token, :names, :smart_contract])
as far as I can see we do not access names field, so we do not need names preload here

2024-12-19 12:16 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/migrator/backfill_multichain_search_db.ex
> +        token_transfer_preloads = [:from_address, :to_address, :token_contract_address]
maybe move this definition closer to `token_transfers_query` definition on line 94?

2024-12-19 12:48 UTC, sl1depengwyn approved these changes

2024-12-19 12:48 UTC, vbaranov commented on apps/explorer/lib/explorer/microservice_interfaces/multichain_search.ex
> +  defp get_smart_contract_name(token), do: token.name
Processed in https://github.com/blockscout/blockscout/pull/11139/commits/47b77a354dc82b21c99f01de09be651a15a86f13

2024-12-19 12:49 UTC, vbaranov commented on apps/explorer/lib/explorer/migrator/backfill_multichain_search_db.ex
> +        token_transfer_preloads = [:from_address, :to_address, :token_contract_address]
Processed in https://github.com/blockscout/blockscout/pull/11139/commits/47b77a354dc82b21c99f01de09be651a15a86f13

2024-12-19 12:49 UTC, vbaranov commented on apps/explorer/lib/explorer/microservice_interfaces/multichain_search.ex
> +      |> Repo.preload([:token, :names, :smart_contract])
Processed in https://github.com/blockscout/blockscout/pull/11139/commits/47b77a354dc82b21c99f01de09be651a15a86f13

2024-12-19 13:09 UTC, merged