feat: Add Stylus verificaiton support
blockscout/blockscout pull request #11183
Opened 2024-11-12 10:39 UTC by nikitosing

Closes #10830 

## Changelog
- Added Stylus verification support through microservice
- one new env added:
https://github.com/blockscout/docs/pull/345
  `MICROSERVICE_STYLUS_VERIFIER_URL`
!! Important note: integration with stylus verifier works only if valid url set to`MICROSERVICE_STYLUS_VERIFIER_URL` and `CHAIN_TYPE=arbitrum`
- new verification endpoint: `/api/v2/smart-contracts/{address_hash}/verification/via/stylus-github-repository`
- new field in `smart_contracts` table for all chain types: `language`. It's enum, possible values: `[solidity: 1, vyper: 2, yul: 3, stylus_rust: 4]`(https://github.com/blockscout/blockscout/issues/11188)
- new fields in `smart_contracts` table for arbitrum chain_type: `github_repository_metadata` and `package_name`

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/for-developers/information-and-settings/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

2024-11-14 11:31 UTC, sl1depengwyn reviewed
Please, add `MICROSERVICE_STYLUS_VERIFIER_URL` and `MICROSERVICE_STYLUS_VERIFIER_ENABLED` to `common-blockscout.env` and to docs repository

2024-11-15 04:45 UTC, akolotov requested changes

2024-11-15 04:45 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus_verifier_interface.ex
> +  def enabled?,
```suggestion
  defp enabled?,
```

2024-11-15 04:45 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus_verifier_interface.ex
> +  def base_url, do: Microservice.base_url(__MODULE__)
```suggestion
  defp base_url, do: Microservice.base_url(__MODULE__)
```

2024-11-15 04:45 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus_verifier_interface.ex
> +  def base_api_url, do: "#{base_url()}" <> "/api/v1/stylus-sdk-rs"
```suggestion
  defp base_api_url, do: "#{base_url()}" <> "/api/v1/stylus-sdk-rs"
```

2024-11-15 04:45 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus_verifier_interface.ex
> +  def versions_list_url, do: base_api_url() <> "/cargo-stylus-versions"
```suggestion
  defp versions_list_url, do: base_api_url() <> "/cargo-stylus-versions"
```

2024-11-15 04:45 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus_verifier_interface.ex
> +  def github_repository_verification_url,
```suggestion
  defp github_repository_verification_url,
```

2024-11-15 04:45 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus_verifier_interface.ex
> +  def process_verifier_response(other) do
```suggestion
  @spec process_verifier_response(any()) :: {:error, any()}
  defp process_verifier_response(other) do
```

2024-11-15 04:45 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus_verifier_interface.ex
> +  def process_verifier_response(%{"versions" => versions}), do: {:ok, Enum.map(versions, &Map.fetch!(&1, "version"))}
```suggestion
  # Handles responce from `stylus-sdk-rs/cargo-stylus-versions` of stylus verifier microservice
  @spec process_verifier_response(map()) :: {:ok, [String.t()]}
  defp process_verifier_response(%{"versions" => versions}), do: {:ok, Enum.map(versions, &Map.fetch!(&1, "version"))}
```

2024-11-15 04:45 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus_verifier_interface.ex
> +  def process_verifier_response(%{"verificationFailure" => %{"message" => error_message}}) do
```suggestion
  # Handles responce from `stylus-sdk-rs/verify-github-repository` of stylus verifier microservice
  @spec process_verifier_response(map()) :: {:error, String.t()}
  defp process_verifier_response(%{"verificationFailure" => %{"message" => error_message}}) do
```

2024-11-15 04:45 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus_verifier_interface.ex
> +  def process_verifier_response(%{"verificationSuccess" => source}) do
```suggestion
  # Handles responce from `stylus-sdk-rs/verify-github-repository` of stylus verifier microservice
  @spec process_verifier_response(map()) :: {:ok, map()}
  defp process_verifier_response(%{"verificationSuccess" => source}) do
```

2024-11-15 04:45 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus_verifier_interface.ex
> +  def process_verifier_response(body) when is_binary(body) do
```suggestion
  @spec process_verifier_response(binary()) :: {:ok, map() | [String.t()]} | {:error, any()}
  defp process_verifier_response(body) when is_binary(body) do
```

2024-11-15 04:45 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus_verifier_interface.ex
> +  def get_versions_list do
```suggestion
  @doc """
    Retrieves a list of supported versions of Cargo Stylus package from the verification microservice.

    ## Returns
    - `{:ok, [String.t()]}` - List of versions on success
    - `{:error, any()}` - Error message if the request fails
  """
  @spec get_versions_list() :: {:ok, [String.t()]} | {:error, any()}
  def get_versions_list do
```

2024-11-15 04:45 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus_verifier_interface.ex
> +  def http_get_request(url) do
```suggestion
  @spec http_get_request(String.t()) :: {:ok, [String.t()]} | {:error, any()}
  defp http_get_request(url) do
```

2024-11-15 04:45 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus_verifier_interface.ex
> +  def http_post_request(url, body) do
```suggestion
  @spec http_post_request(String.t(), map()) :: {:ok, map()} | {:error, any()}
  defp http_post_request(url, body) do
```

2024-11-15 04:45 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus_verifier_interface.ex
> +  def verify_github_repository(
```suggestion
  @doc """
    Verifies a Stylus smart contract using source code from a GitHub repository.

    Sends verification request to the verification microservice with repository details
    and deployment information.

    ## Parameters
    - `body`: A map containing:
      - `deployment_transaction`: Transaction hash where contract was deployed
      - `rpc_endpoint`: RPC endpoint URL for the chain
      - `cargo_stylus_version`: Version of cargo-stylus used for deployment
      - `repository_url`: GitHub repository URL containing contract code
      - `commit`: Git commit hash used for deployment
      - `path_prefix`: Optional path prefix if contract is not in repository root

    ## Returns
    - `{:ok, map}` with verification details:
      - `abi`: Contract ABI (optional)
      - `contract_name`: Contract name (optional)
      - `package_name`: Package name
      - `files`: Map of file paths to contents used in verification
      - `cargo_stylus_version`: Version of cargo-stylus used
      - `github_repository_metadata`: Repository metadata (optional)
    - `{:error, any}` if verification fails
  """
  @spec verify_github_repository(map()) :: {:ok, map()} | {:error, any()}
  def verify_github_repository(
```

2024-11-15 04:45 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus_verifier_interface.ex
> +  """
```suggestion
  @moduledoc """
    Provides an interface for verifying Stylus smart contracts by interacting with a verification
    microservice.

    Handles verification requests for Stylus contracts deployed from GitHub repositories by
    communicating with an external verification service.
  """
```

2024-11-15 04:46 UTC, akolotov commented on config/runtime.exs
> +  enabled: ConfigHelper.parse_bool_env_var("MICROSERVICE_STYLUS_VERIFIER_ENABLED")
Another suggestion is to not introduce `MICROSERVICE_STYLUS_VERIFIER_DISABLED` or `MICROSERVICE_STYLUS_VERIFIER_ENABLED` at all and enable the service if `MICROSERVICE_STYLUS_VERIFIER_URL` is configured.

2024-11-15 14:34 UTC, nikitosing commented on apps/explorer/lib/explorer/smart_contract/stylus_verifier_interface.ex
> +  def enabled?,
It should be public: https://github.com/blockscout/blockscout/blob/f7ae7cef232608938f4fc24bf7f4ef76aa330c1f/apps/block_scout_web/lib/block_scout_web/controllers/api/v2/verification_controller.ex#L69

2024-11-15 15:08 UTC, nikitosing commented on apps/explorer/lib/explorer/smart_contract/compiler_version.ex
>    end
Processed in 00253da4d7c93809f95c31267b9ee3dee0faea97

2024-11-15 15:14 UTC, nikitosing commented on config/runtime.exs
> +  enabled: ConfigHelper.parse_bool_env_var("MICROSERVICE_STYLUS_VERIFIER_ENABLED")
Thanks, it makes sense, but I'd prefer stick to our current approach of adding envs for external integrations.
As for me, it's more convenient set `MICROSERVICE_STYLUS_VERIFIER_ENABLED` and not to touch `MICROSERVICE_STYLUS_VERIFIER_URL`: firstly you'll need to cut it, then return it back, switching one bool env is simpler. And another my point is consistency across already existing envs for microservices.

2024-11-15 17:17 UTC, akolotov commented on config/runtime.exs
> +  enabled: ConfigHelper.parse_bool_env_var("MICROSERVICE_STYLUS_VERIFIER_ENABLED")
> And another my point is consistency across already existing envs for microservices.

And continue magnifying ENV vars hell whereas it is possible to move away from it step-by-step?

> `MICROSERVICE_STYLUS_VERIFIER_URL`: firstly you'll need to cut it, then return it back, switching one bool env is simpler

Just to simplify the work during debug session you don't want to reduce amount of variables, right?

2024-11-15 17:18 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus_verifier_interface.ex
> +  def enabled?,
Ah, yes, sorry

2024-11-15 21:25 UTC, akolotov requested changes

2024-11-15 21:25 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus/verifier.ex
> +  defp evaluate_authenticity_inner(true, address_hash, params) do
```suggestion
  # Verifies the authenticity of a Stylus smart contract using GitHub repository source code.
  #
  # This function retrieves the contract creation transaction and blockchain RPC endpoint,
  # which together with passed parameters are required by the verification microservice to
  # validate the contract deployment and verify the source code against the deployed
  # bytecode.
  #
  # ## Parameters
  # - `true`: Required boolean flag to proceed with verification
  # - `address_hash`: Contract address
  # - `params`: Map containing verification parameters
  #
  # ## Returns
  # - `{:ok, map}` with verification details including ABI, contract name, and source files
  # - `{:error, any}` if verification fails
  @spec evaluate_authenticity_inner(boolean(), EthereumJSONRPC.address() | Hash.Address.t(), map()) ::
          {:ok, map()} | {:error, any()}
  defp evaluate_authenticity_inner(true, address_hash, params) do```

2024-11-15 21:25 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus/verifier.ex
> +  def evaluate_authenticity(address_hash, params) do
```suggestion
  @doc """
    Verifies a Stylus smart contract by comparing source code from a GitHub repository against the deployed bytecode using a verification microservice.

    ## Parameters
    - `address_hash`: Contract address
    - `params`: Map containing verification parameters:
      - `cargo_stylus_version`: Version of cargo-stylus used for deployment
      - `repository_url`: GitHub repository URL containing contract code
      - `commit`: Git commit hash used for deployment
      - `path_prefix`: Optional path prefix if contract is not in repository root

    ## Returns
    - `{:ok, map}` with verification details:
      - `abi`: Contract ABI (optional)
      - `contract_name`: Contract name (optional)
      - `package_name`: Package name
      - `files`: Map of file paths to contents used in verification
      - `cargo_stylus_version`: Version of cargo-stylus used
      - `github_repository_metadata`: Repository metadata (optional)
    - `{:error, any}` if verification fails or is disabled
  """
  @spec evaluate_authenticity(EthereumJSONRPC.address() | Hash.Address.t(), map()) ::
          {:ok, map()} | {:error, any()}
  def evaluate_authenticity(address_hash, params) do
```

2024-11-15 21:25 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus/verifier.ex
> +  alias Explorer.SmartContract.StylusVerifierInterface
```suggestion
  alias Explorer.Chain.Hash
  alias Explorer.SmartContract.StylusVerifierInterface
```

2024-11-15 21:25 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus/verifier.ex
> +  then Verified.
```suggestion
    Verifies Stylus smart contracts by comparing their source code against deployed bytecode.

    This module handles verification of Stylus smart contracts through their GitHub repository
    source code. It interfaces with a verification microservice that:
    - Fetches source code from the specified GitHub repository and commit
    - Compiles the code using the specified cargo-stylus version
    - Compares the resulting bytecode against the deployed contract bytecode
    - Returns verification details including ABI and contract metadata
```

2024-11-15 21:25 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus/publisher.ex
> +  defp unverified_smart_contract(address_hash, params, error, error_message, verification_with_files? \\ false) do
```suggestion
  # Creates an invalid changeset for a Stylus smart contract that failed verification.
  #
  # Prepares contract attributes with MD5 hash of bytecode and creates an invalid changeset
  # with appropriate error messages. The changeset is marked with `:insert` action to
  # indicate a failed verification attempt.
  #
  # ## Parameters
  # - `address_hash`: The contract's address hash
  # - `params`: Map containing contract details from verification attempt
  # - `error`: The verification error that occurred
  # - `error_message`: Optional custom error message
  # - `verification_with_files?`: Boolean indicating if verification used source files.
  #   Defaults to `false`
  #
  # ## Returns
  # An invalid `t:Ecto.Changeset.t/0` with:
  # - Contract attributes including MD5 hash of bytecode
  # - Error message attached to appropriate field
  # - Action set to `:insert`
  @spec unverified_smart_contract(binary() | Explorer.Chain.Hash.t(), %{String.t() => any()}, any(), any(), boolean()) ::
          Ecto.Changeset.t()
  defp unverified_smart_contract(address_hash, params, error, error_message, verification_with_files? \\ false) do
```

2024-11-15 21:25 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus/publisher.ex
> +          {:error, Ecto.Changeset.t() | String.t()} | {:ok, Explorer.Chain.SmartContract.t()}
```suggestion
  # This function first checks if a smart contract already exists in the database
  # at the given address. If it exists, updates the contract with new attributes.
  # Otherwise, creates a new smart contract record.
  @spec create_or_update_smart_contract(binary() | Explorer.Chain.Hash.t(), map()) ::
          {:error, Ecto.Changeset.t() | String.t()} | {:ok, Explorer.Chain.SmartContract.t()}
```

2024-11-15 21:25 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus/publisher.ex
> +  defp publish_smart_contract(address_hash, params, abi) do
```suggestion
  # Stores information about a verified Stylus smart contract in the database.
  #
  # ## Parameters
  # - `address_hash`: The contract's address hash as binary or `t:Explorer.Chain.Hash.t/0`
  # - `params`: Map containing contract details:
  #   - `name`: Contract name
  #   - `file_path`: Path to the contract source file
  #   - `compiler_version`: Version of the Stylus compiler
  #   - `contract_source_code`: Source code of the contract
  #   - `secondary_sources`: Additional source files
  #   - `package_name`: Package name for Stylus contract
  #   - `github_repository_metadata`: Repository metadata
  # - `abi`: Contract's ABI (Application Binary Interface)
  #
  # ## Returns
  # - `{:ok, smart_contract}` if publishing succeeds
  # - `{:error, changeset}` if there are validation errors
  # - `{:error, message}` if the database operation fails
  @spec publish_smart_contract(binary() | Explorer.Chain.Hash.t(), %{String.t() => any()}, map()) ::
          {:error, Ecto.Changeset.t() | String.t()} | {:ok, Explorer.Chain.SmartContract.t()}
  defp publish_smart_contract(address_hash, params, abi) do
```

2024-11-15 21:25 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus/publisher.ex
> +  defp process_verifier_response(
```suggestion
  # Processes successful Stylus contract verification response and stores contract data.
  #
  # Takes the verification response from `evaluate_authenticity/2` containing verified contract
  # details and prepares them for storage in the database. The main source file is extracted
  # from `files` map using the default filename, while other files are stored as secondary
  # sources.
  #
  # ## Parameters
  # - `response`: Verification response map containing:
  #   - `abi`: Contract ABI as JSON string
  #   - `cargo_stylus_version`: Version of cargo-stylus used
  #   - `contract_name`: Name of the contract
  #   - `files`: Map of file paths to source code contents
  #   - `package_name`: Package name of the contract
  #   - `github_repository_metadata`: Repository metadata
  # - `address_hash`: The contract's address hash as binary or `t:Explorer.Chain.Hash.t/0`
  #
  # ## Returns
  # - `{:ok, smart_contract}` if database storage succeeds
  # - `{:error, changeset}` if there are validation errors
  # - `{:error, message}` if the database operation fails
  @spec process_verifier_response(%{String.t() => any()}, binary() | Explorer.Chain.Hash.t()) ::
          {:ok, Explorer.Chain.SmartContract.t()} | {:error, Ecto.Changeset.t() | String.t()}
  defp process_verifier_response(
```

2024-11-15 21:25 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus/publisher.ex
> +  def publish(address_hash, params) do
```suggestion
  @doc """
    Verifies and publishes a Stylus smart contract using GitHub repository source code.

    Initiates verification of a contract through the verification microservice. On
    successful verification, processes and stores the contract details in the
    database. On failure, creates an invalid changeset with appropriate error
    messages.

    ## Parameters
    - `address_hash`: The contract's address hash as binary or `t:Explorer.Chain.Hash.t/0`
    - `params`: Map containing verification parameters:
      - `"cargo_stylus_version"`: Version of cargo-stylus used for deployment
      - `"repository_url"`: GitHub repository URL containing contract code
      - `"commit"`: Git commit hash used for deployment
      - `"path_prefix"`: Optional path prefix if contract is not in repository root

    ## Returns
    - `{:ok, smart_contract}` if verification and database storage succeed
    - `{:error, changeset}` if verification fails or there are validation errors
  """
  @spec publish(binary() | Explorer.Chain.Hash.t(), %{String.t() => any()}) ::
          {:error, Ecto.Changeset.t()} | {:ok, Explorer.Chain.SmartContract.t()}
  def publish(address_hash, params) do
```

2024-11-15 21:25 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus/publisher.ex
> +  Module responsible to control the contract verification.
```suggestion
    Module responsible for verifying and publishing Stylus smart contracts.

    The verification process includes:
    1. Initiating verification through a microservice that compares GitHub repository
      source code against deployed bytecode
    2. Processing the verification response, including ABI and source files
    3. Creating or updating the smart contract record in the database
    4. Handling verification failures by creating invalid changesets with error messages
```

2024-11-15 21:25 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus/publisher_worker.ex
> +  defp broadcast(method, address_hash, args) do
```suggestion
  # Broadcasts the result of a Stylus smart contract verification attempt.
  #
  # Executes the specified verification method in the `Publisher` module and
  # broadcasts the result through the events publisher.
  #
  # ## Parameters
  # - `method`: The verification method to execute
  # - `address_hash`: Contract address
  # - `args`: Arguments to pass to the verification method
  #
  # ## Returns
  # - `{:ok, contract}` if verification succeeds
  # - `{:error, changeset}` if verification fails
  @spec broadcast(atom(), binary() | Explorer.Chain.Hash.t(), any()) :: any()
  defp broadcast(method, address_hash, args) do
```

2024-11-15 21:25 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus/publisher_worker.ex
> +  def perform({"github_repository", %{"address_hash" => address_hash} = params}) do
```suggestion
  @doc """
    Processes a Stylus smart contract verification request.

    Initiates the verification process by broadcasting the verification request to
    the module responsible for the actual verification and conseqequent update of
    the database. This function is called automatically by the job queue system.

    ## Parameters
    - `{"github_repository", params}`: Tuple containing:
      - First element: `"github_repository"` indicating the verification source
      - Second element: Map containing:
        - `"address_hash"`: The contract's address hash to verify

    ## Returns
    - Result of the broadcast operation
  """
  @spec perform({binary(), %{String.t() => any()}}) :: any()
  def perform({"github_repository", %{"address_hash" => address_hash} = params}) do
```

2024-11-15 21:25 UTC, akolotov commented on apps/explorer/lib/explorer/smart_contract/stylus/publisher_worker.ex
> +  Background smart contract verification worker.
```suggestion
    Processes Stylus smart contract verification requests asynchronously in the background.

    This module implements a worker that handles verification of Stylus smart contracts
    through their GitHub repository source code. It uses a job queue system to:
    - Receive verification requests containing contract address and GitHub details
    - Delegate verification to the Publisher module
    - Broadcast verification results through the events system
```

2024-11-15 21:25 UTC, akolotov commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/verification_controller.ex
> +  defp maybe_add_stylus_options(config) do
```suggestion
  # Adds Stylus compiler versions to config if Stylus verification is enabled
  defp maybe_add_stylus_options(config) do
```

2024-11-15 21:25 UTC, akolotov commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/verification_controller.ex
> +  def verification_via_stylus_github_repository(
```suggestion
  @doc """
    Initiates verification of a Stylus smart contract using its GitHub repository source code.

    Validates the request parameters and queues the verification job to be processed
    asynchronously by the Stylus publisher worker.

    ## Parameters
    - `conn`: The connection struct
    - `params`: A map containing:
      - `address_hash`: Contract address to verify
      - `cargo_stylus_version`: Version of cargo-stylus used for deployment
      - `repository_url`: GitHub repository URL containing contract code
      - `commit`: Git commit hash used for deployment
      - `path_prefix`: Optional path prefix if contract is not in repository root

    ## Returns
    - JSON response with:
      - Success message if verification request is queued successfully
      - Error message if:
        - Stylus verification is not enabled
        - Address format is invalid
        - Contract is already verified
        - Access is restricted
  """
  @spec verification_via_stylus_github_repository(Plug.Conn.t(), %{String.t() => any()}) ::
          {:already_verified, true}
          | {:format, :error}
          | {:not_found, false | nil}
          | {:restricted_access, true}
          | Plug.Conn.t()
  def verification_via_stylus_github_repository(
```

2024-11-19 08:12 UTC, nikitosing commented on config/runtime.exs
> +  enabled: ConfigHelper.parse_bool_env_var("MICROSERVICE_STYLUS_VERIFIER_ENABLED")
Dropped `_ENABLED`. Here an issue for further refactoring: https://github.com/blockscout/blockscout/issues/11228

2024-11-20 12:34 UTC, akolotov approved these changes

2024-11-20 13:56 UTC, sl1depengwyn approved these changes

2024-11-21 14:29 UTC, nikitosing commented on config/config_helper.exs
> +  defp valid_url?(string) when is_binary(string) do
Unfortunately `config_helper.exs` is script file and does not belong umbrella, so we cant hold this function here.
We can store this function in one of umbrella app, but each app should be dependand of chosen one. And only possible is ethereum_json_rpc. But this function does not follow role of the `ethereum_json_rpc` app. In future it will be reasonable to move it to new `utils` app, introduced in https://github.com/blockscout/blockscout/pull/11148

2024-11-21 14:31 UTC, nikitosing commented on apps/explorer/lib/explorer/smart_contract/stylus_verifier_interface.ex
> +  end
There are bug on the microservice side, and for now we have to handle current buggy and future fixed responses

2024-11-21 14:46 UTC, nikitosing commented on apps/explorer/lib/explorer/smart_contract/compiler_version.ex
> +  defp fetch_compiler_versions(compiler_list_fn, :stylus = compiler_type) do
Done in 7952aa85ef8a6bd21a004ed6ae7ceaac6b2dee29

2024-11-21 14:46 UTC, nikitosing commented on apps/explorer/lib/explorer/smart_contract/helper.ex
> +  @spec fetch_data_for_stylus_verification(binary() | Hash.Address.t()) :: Hash.t() | nil
Done in 7952aa85ef8a6bd21a004ed6ae7ceaac6b2dee29

2024-11-21 15:40 UTC, vbaranov approved these changes

2024-11-21 15:40 UTC, merged