feat: add CSV export of epoch transactions for address
blockscout/blockscout pull request #11195
Opened 2024-11-13 20:44 UTC by fedor-ivn

Closes #11194.

## Motivation

Celo had a request from the community to ensure that validators are still able to export epoch transaction data for when they migrate to our instance. This is generally important for calculating how much each validator has earned from participating in one of the validator groups in the celo protocol.

For context, we're talking about something [like this](https://explorer.celo.org/mainnet/address/0xc24baeac0Fd189637112B7e33d22FfF2730aF993/epoch-transactions) in the address page for a validator in the legacy celo explorer, where at the bottom of the page they have the ability to [create a csv export](https://explorer.celo.org/mainnet/csv-export?address=0xc24baeac0Fd189637112B7e33d22FfF2730aF993&type=epoch-transactions) for the specific data.

## Changelog

### Enhancements

New `/api/v1/celo-election-rewards-csv` endpoint and `AddressElectionRewardsCsvExporter` module.

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/for-developers/information-and-settings/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

2024-11-20 16:24 UTC, fedor-ivn commented on apps/explorer/lib/explorer/chain/csv_export/celo/address_election_rewards_csv_exporter.ex
> +          reward.amount |> Wei.to(:wei) |> Decimal.to_string(:normal),
Should we avoid scientific notation here like `1E-27`?

2024-11-22 16:26 UTC, sl1depengwyn requested changes

2024-11-22 16:26 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/celo/election_reward.ex
> +  # sobelow_skip ["DOS.StringToAtom"]
This is actually a DOS possibility, lets define `@string_types_enum` or do it in some other way than calling `String.to_atom`

2024-11-22 16:26 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/csv_export/celo/address_election_rewards_csv_exporter.ex
> +          reward.amount |> Wei.to(:wei) |> Decimal.to_string(:normal),
I would avoid it

2024-11-22 16:26 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/celo/election_reward.ex
> +  def where_block_number_in_period(base_query, from_block, to_block)
```suggestion
  @spec where_block_number_in_period(Ecto.Query.t(), String.t() | integer() | nil, String.t() | integer() | nil) ::
          Ecto.Query.t()
  def where_block_number_in_period(base_query, from_block, to_block)
```

2024-11-26 09:17 UTC, sl1depengwyn approved these changes

2024-12-03 08:03 UTC, fedor-ivn commented on apps/explorer/lib/explorer/chain/celo/reader.ex
> +  alias Explorer.Chain
There's no rationale I guess, probably introduced by accident. Fixed ✅

2024-12-03 08:20 UTC, vbaranov approved these changes

2024-12-03 08:21 UTC, merged