fix: handle simultaneous api key creation
blockscout/blockscout pull request #11233
Opened 2024-11-20 11:32 UTC by sl1depengwyn

*[GitHub keywords to close any associated issues](https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/)*

## Motivation

*Why we should merge these changes.  If using GitHub keywords to close [issues](https://github.com/poanetwork/blockscout/issues), this is optional as the motivation can be read on the issue page.*

## Changelog

### Enhancements

*Things you added that don't break anything.  Regression tests for Bug Fixes count as Enhancements.*

### Bug Fixes

*Things you changed that fix bugs.  If a fixes a bug, but in so doing adds a new requirement, removes code, or requires a database reset and reindex, the breaking part of the change should be added to Incompatible Changes below also.*

### Incompatible Changes

*Things you broke while doing Enhancements and Bug Fixes.  Breaking changes include (1) adding new requirements and (2) removing code.  Renaming counts as (2) because a rename is a removal followed by an add.*

## Upgrading

*If you have any Incompatible Changes in the above Changelog, outline how users of prior versions can upgrade once this PR lands or when reviewers are testing locally.  A common upgrading step is "Database reset and re-index required".*

## Checklist for your Pull Request (PR)

- [ ] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
- [ ] I checked whether I should update the docs and did so by submitting a PR to [docs repository](https://github.com/blockscout/docs).
- [ ] If I added/changed/removed ENV var, I submitted a PR to [docs repository](https://github.com/blockscout/docs) to update the list of [env vars](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md) and I updated the version to `master` in the Version column. If I removed variable, I added it to [Deprecated ENV Variables](https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables/deprecated-env-variables/README.md) page. After merging docs PR, changes will be reflected in these [pages](https://docs.blockscout.com/for-developers/information-and-settings/env-variables).
- [ ] If I added new DB indices, I checked, that they are not redundant, with PGHero or other tools.
- [ ] If I added/removed chain type, I modified the Github CI matrix and PR labels accordingly.

2024-11-20 15:00 UTC, vbaranov reviewed
We have other functionality in the Account module where similar `create/1` function is implemented. Is it possible, that those parts are affected similar vulnerability?

2024-11-20 15:26 UTC, nikitosing requested changes
Will be written migration to drop abused API keys?

2024-11-21 10:10 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/account/api/key.ex
> +    {:error, %__MODULE__{} |> changeset(Map.put(attrs, :value, generate_api_key()))}
This clause is unlikely to be fired actually, but I added it in case if the function is somehow called without `identity_id` because the changeset with the error is more clear than function clause error. The changeset is chosen over `:identity_not_found` in order to be compatible with previous behaviour

2024-11-22 07:37 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/account/api/key.ex
> +      end
Fixed, thanks

2024-11-22 07:37 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/account/api/key.ex
> +    {:error, %__MODULE__{} |> changeset(Map.put(attrs, :value, generate_api_key()))}
I have removed `:identity_not_found` as well

2024-11-22 07:39 UTC, sl1depengwyn commented
@nikitosing Nice catch, added as well

2024-11-22 07:52 UTC, sl1depengwyn commented
> We have other functionality in the Account module where similar create/1 function is implemented. Is it possible, that those parts are affected similar vulnerability?

@vbaranov wil do in a separate pr

2024-11-22 07:57 UTC, vbaranov commented on apps/explorer/priv/account/migrations/20241121140138_remove_abused_api_keys.exs
> +                    WHERE row_number > 5)
```suggestion
                    WHERE row_number > 3)
```

We allow 3 keys at most:
> You have added the maximum number of API keys (3). Contact us to request additional keys.

2024-11-22 08:42 UTC, vbaranov approved these changes

2024-11-22 11:13 UTC, nikitosing approved these changes

2024-11-22 11:32 UTC, merged