Add support for partially verified via sourcify contracts
blockscout/blockscout pull request #4331
Opened 2021-07-01 15:06 UTC by nikitosing

Closes #4317 

## Changelog
- If smart-contract verified via Sourcify Blockscout will fetch it automatically
- Added support for partially verified contracts via Sourcify

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [x] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [x] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2021-07-03 18:10 UTC, mj5599-spo reviewed
# #

2021-07-08 18:14 UTC, vbaranov requested changes
Some nitpicks about the naming and method interface changing, test coverage in the code and:
1. Incorrect URL generated to Sourcify repository for partially verified contract: `https://repo.sourcify.dev/contracts/full_match/partial_match/77/0xE300553919bEC8641eF110cbc9042b83b9f4b5a1/`
2. I know this is not a part of concrete this PR, but let's put "Verify & Publish" button above:
![Screenshot 2021-07-08 at 20 47](https://user-images.githubusercontent.com/4341812/124970270-63a8f000-e030-11eb-88b1-2c8fa1d142fe.png)

2021-07-08 18:14 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
> +         {:contract, {:ok, contract}} <- to_smart_contract(address_hash, address_param) do
I would suggest not changing the interface of the function in order to prevent errors because it is used in multiple places. And the second param can be derived from the first parameter

2021-07-08 18:14 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
> +<% full_verified = Chain.smart_contract_full_verified?(@address.hash)%>
Let's rename it to `fully_verified`?

2021-07-08 18:14 UTC, vbaranov commented on apps/explorer/lib/explorer/chain.ex
> +  defp check_full_verified(address_hash) do
Let's rename it to `check_fully_verified `?

2021-07-08 18:14 UTC, vbaranov commented on apps/explorer/priv/repo/migrations/20210701084814_support_partial_match.exs
> +      add(:partial_verified, :boolean, null: true)
Let's rename to 'partially_verified'?

2021-07-08 18:14 UTC, vbaranov commented on apps/explorer/lib/explorer/chain.ex
> +  def update_smart_contract(attrs \\ %{}, external_libraries \\ [], secondary_sources \\ []) do
Let's add documentation for this function and cover it with tests because looks potentially dangerous.

2021-07-09 09:33 UTC, vbaranov reviewed
`listcontracts` API endpoint with `unverified` option returns verified in Sourcify contracts. It should return them with `verified` option.

2021-07-09 09:52 UTC, vbaranov commented
> `listcontracts` API endpoint with `unverified` option returns verified in Sourcify contracts. It should return them with `verified` option.

This works in fact

2021-07-09 12:27 UTC, vbaranov commented on apps/explorer/test/explorer/chain_test.exs
> +            "pragma solidity >=0.7.0 <0.9.0;contract Storage {uint256 number;function store(uint256 num) public {number = num;}function retrieve_() public view returns (uint256){return number;}}",
Let's set different contract_source_code for each file in the test

2021-07-09 13:01 UTC, vbaranov approved these changes

2021-07-09 13:02 UTC, merged