Fix logs query
blockscout/blockscout pull request #4784
Opened 2021-10-19 10:26 UTC by nikitosing

Close #4773 

## Changelog

### Bug Fixes
- Fix query: move limit to the whole query
- Remove useless `where`
## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2021-11-17 15:18 UTC, vbaranov requested changes
Logs are failed to load in UI after changes are implemented:

https://blockscout.com/poa/sokol/address/0x79dD14623c4D33413c0c28fDAbC2285Fdb1e572e/logs
https://blockscout.com/poa/sokol/address/0x2C3917F8665DCCF80671b889362AE64E4f9F586a/logs

<img width="830" alt="Screenshot 2021-11-17 at 18 15 55" src="https://user-images.githubusercontent.com/4341812/142227767-5695a295-89be-4702-8daa-75a24e5b585a.png">
<img width="813" alt="Screenshot 2021-11-17 at 18 15 47" src="https://user-images.githubusercontent.com/4341812/142227770-725cdba5-48c4-43bb-9699-c47e7a7ca3e6.png">

I suppose the query should be rewritten or missing DB indices should be installed

2022-01-26 10:20 UTC, Successahead commented
Approve

2022-01-26 10:21 UTC, Successahead approved these changes

2022-01-26 10:21 UTC, Successahead approved these changes

2022-11-26 10:02 UTC, nikitosing commented
Problem was fixed by https://github.com/blockscout/blockscout/pull/6420

2022-11-26 10:02 UTC, closed without merging