Np fix transaction error status
blockscout/blockscout pull request #5016
Opened 2021-12-19 07:50 UTC by nikitosing

Close #4974 

## Changelog

### Enhancements

![image](https://user-images.githubusercontent.com/32202610/146667681-6abffc3c-a5e3-4246-b008-b69277809d1b.png)

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2021-12-27 10:22 UTC, vbaranov requested changes

2021-12-27 10:22 UTC, vbaranov commented on apps/explorer/priv/repo/migrations/20211217201759_add_has_error_in_iternal_txs_field_to_transaction.exs
> +      add(:has_error_in_iternal_txs, :boolean, null: true)
iternal -> internal

2021-12-29 18:07 UTC, nikitosing commented on apps/explorer/priv/repo/migrations/20211217201759_add_has_error_in_iternal_txs_field_to_transaction.exs
> +      add(:has_error_in_iternal_txs, :boolean, null: true)
thanks, fixed

2022-01-17 11:06 UTC, vbaranov requested changes

2022-01-17 11:06 UTC, vbaranov commented on apps/explorer/priv/repo/migrations/20211217201759_add_has_error_in_iternal_txs_field_to_transaction.exs
> +defmodule Explorer.Repo.Migrations.AddHasErrorInIternalTxsFieldToTransaction do
Iternal -> Internal and also typo in the file name

2022-01-23 17:37 UTC, nikitosing commented on apps/explorer/priv/repo/migrations/20211217201759_add_has_error_in_iternal_txs_field_to_transaction.exs
> +defmodule Explorer.Repo.Migrations.AddHasErrorInIternalTxsFieldToTransaction do
Thanks

2022-02-17 12:10 UTC, vbaranov approved these changes

2022-02-17 13:02 UTC, merged