fix getreserves value display
blockscout/blockscout pull request #5036
Opened 2021-12-23 18:14 UTC by zalam003

Closes #5035 

## Changelog

### Enhancements
*Display getReserves values*

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2021-12-27 09:44 UTC, vbaranov reviewed
@zalam003 please attach the screenshots of the visual changes: before/after changes.

2021-12-27 13:45 UTC, zalam003 commented
@vbaranov We already updated our deployment.  But you can see the difference below.

Here is the [before](https://blockscout.com/xdai/mainnet/address/0x0E3e9CCeb13c9f8c6FAF7a0f00F872d6291630dE/read-contract):

![image](https://user-images.githubusercontent.com/48445346/147477442-ea1d1135-2d8c-43fe-89ec-e833e6bb7d97.png)



and [after](https://explorer.energi.network/address/0x5Cc8B3D89AE2cA30A08b6697E33606FC3437d392/read-contract):

![image](https://user-images.githubusercontent.com/48445346/147477401-2d87ea2c-5326-4c73-a5cb-471d350b870f.png)

2021-12-29 08:19 UTC, nikitosing requested changes

2021-12-29 08:19 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex
> +    "<div class=\"py-2 pr-2 text-nowrap\" style=\"padding-left: 20px\">(#{type}) : #{value}</div>"
These changes also affect on the other elements:
Before: 

![image](https://user-images.githubusercontent.com/32202610/147640860-c21ef5fb-8554-4ab0-a9b4-13aaed67574f.png)

After:

![image](https://user-images.githubusercontent.com/32202610/147641008-6bce04bd-a712-4c72-8ae9-57e5069a4863.png)

I think better to return old view (namely indentation and black color for the names) for the such function response boxes
contract on the screenshot:
https://blockscout.com/poa/sokol/address/0xB9f191f5c324B4c97B4c11333338288918c5968C/read-contract
method: `getReceipt`
input data: `0x9cd14677f9aa5569b3bbb351fcd67d1115aa563ae1624276d3d4e67fb3d6f926`

2021-12-29 08:20 UTC, nikitosing commented
Also, please rebase on master branch and run the following commands to fix gettext error:
`cd apps/block_scout_web`
`mix gettext.extract --merge`

2021-12-29 13:52 UTC, zalam003 commented
@nikitosing We have customized our implementation at Energi.  We are not ready to open source it yet.  However, we want to share some of the changes with you as and when we feel it may benefit you.  We felt this is something Blockscout should include.  We leave it up to you if you want to merge or reject. Or refactor to your specifications if needed.

We have implemented it to match what you see for LP tokens in [etherscan.io](https://etherscan.io/token/0xb6916bc20cae34de64af39b8534d1459d8bb4128#readContract).  Following is a screenshot from Etherscan.

![image](https://user-images.githubusercontent.com/48445346/147668916-6a600b4e-0f23-4ead-bbfb-020a47d17c69.png)

2022-02-18 08:13 UTC, vbaranov commented
Closed in favor https://github.com/blockscout/blockscout/pull/5197

2022-02-18 08:13 UTC, closed without merging