Add transaction state changes feature
blockscout/blockscout pull request #5944
Opened 2022-08-17 17:04 UTC by sl1depengwyn

https://github.com/blockscout/blockscout/issues/5583

## Changelog
Add tab with state changes to transaction page that show how balances changed. Some examlpes below:
- [tx](https://blockscout.com/xdai/mainnet/tx/0xfeacfd6eaa41ad529e29d9779fb4d4a8d9e74c22001d40bba66defb815bb4dc2)
![image](https://user-images.githubusercontent.com/53992153/185777644-a1e46453-1239-490a-8d14-7cd97f49985e.png)
- [tx](https://blockscout.com/poa/sokol/tx/0xf2b1c231ff1af2ba4be2282fdc5fb53c2217ca3aa0fc05fbed168d3c81a1dcb7)
![image](https://user-images.githubusercontent.com/53992153/185778134-c9cdd6b4-598b-4382-a6e4-106808567475.png)
In case of multiple transfers of unique tokens of the same contranct all of them diaplayed in one change
- [tx](https://blockscout.com/xdai/mainnet/tx/0x92d6f2f5798d8104c337c55e25dfae50194dcc81f930c94bea32a57bc9425506)
![image](https://user-images.githubusercontent.com/53992153/185776572-3fbc6a4e-19ff-46dc-85f6-ba17f1643d84.png)
Here balance of contract(0x09C131) is unknown, so it isn't displayed

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [x] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2022-08-19 10:17 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/address/token_balance.ex
> -
These are imported by `use Explorer.Schema`
https://github.com/blockscout/blockscout/blob/e23653fa88cffa74ed6d5c649ad05603613a8ebb/apps/explorer/lib/explorer/schema.ex#L4-L12

2022-08-29 19:36 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/address/token_balance.ex
> +      order_by: [desc: :block_number]
@sl1depengwyn  Is this complication because of the query performance considerations?

2022-08-29 19:38 UTC, vbaranov reviewed
@sl1depengwyn when I click to any tx's tab except `State changes` scroll jumps to tab's content. It would be awesome to keep the same behaviour for `State changes` tab as well.

2022-08-29 20:07 UTC, vbaranov commented
@sl1depengwyn also, what is the order of state changes?

2022-08-29 20:34 UTC, vbaranov commented
@sl1depengwyn tx failed, but state change asserting transfer of the coin value, what is incorrect:

![scrnli_29_08_2022_23-33-58](https://user-images.githubusercontent.com/4341812/187293675-4b2148f7-fa11-40c8-b9e0-fcad4a961562.png)

2022-08-31 09:37 UTC, sl1depengwyn commented
> @sl1depengwyn also, what is the order of state changes?

first 3 entries are coin from, to and miner and then all token transfers changes, token transfers changes unordered since stored in Map, but grouped by address

2022-08-31 09:47 UTC, sl1depengwyn commented
> @sl1depengwyn when I click to any tx's tab except `State changes` scroll jumps to tab's content. It would be awesome to keep the same behaviour for `State changes` tab as well.

fix

2022-08-31 09:47 UTC, sl1depengwyn commented
> @sl1depengwyn tx failed, but state change asserting transfer of the coin value, what is incorrect:
> 
> ![scrnli_29_08_2022_23-33-58](https://user-images.githubusercontent.com/4341812/187293675-4b2148f7-fa11-40c8-b9e0-fcad4a961562.png)

fixed

2022-08-31 13:21 UTC, vbaranov reviewed
@sl1depengwyn 1 test failed:
```
1) test GET index/3 returns fetched state changes for the transaction with token transfer (BlockScoutWeb.TransactionStateControllerTest)
Error:      test/block_scout_web/controllers/transaction_state_controller_test.exs:33
     Expected truthy, got false
     code: assert String.contains?(full_text, format_wei_value(%Wei{value: Decimal.new(1, 2, 18)}, :ether))
     arguments:
```

2022-09-02 14:15 UTC, nikitosing requested changes

2022-09-02 14:15 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/controllers/transaction_state_controller.ex
> +        paging_options: %PagingOptions{key: nil, page_size: 512}
We should not assume that block has no more than X transactions.

2022-09-03 11:48 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/controllers/transaction_state_controller.ex
> +      if is_nil(max_priority_fee_per_gas) or is_nil(base_fee_per_gas),
Wrote in PM about block's rewards

2022-09-08 08:16 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/controllers/transaction_state_controller.ex
> +      block_txs = Chain.block_to_transactions(block.hash)
You did not pass paging options here. It will use default one

2022-09-08 08:17 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/controllers/transaction_state_controller.ex
>        token_transfers = Chain.transaction_to_token_transfers(transaction_hash, full_options)
Inside the `Chain.transaction_to_token_transfers` function `limit` is applied before `hadle_paging_options`. You should re-check it

2022-09-09 07:49 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/controllers/transaction_state_controller.ex
>        token_transfers = Chain.transaction_to_token_transfers(transaction_hash, full_options)
According to [documentation](https://www.postgresql.org/docs/current/sql-select.html#SQL-LIMIT):
`If the count expression evaluates to NULL, it is treated as LIMIT ALL, i.e., no limit.`
So, I think It's okay in this case

2022-09-09 11:32 UTC, nikitosing approved these changes

2022-11-01 13:46 UTC, vbaranov approved these changes

2022-11-01 13:47 UTC, merged