Core BlockScout API V2
blockscout/blockscout pull request #6164
Opened 2022-09-26 15:36 UTC by nikitosing

[API docs](https://app.swaggerhub.com/apis/NIKITOSING4/CoreBlockScoutAPI/1.0.0)

## Motivation

To interact with new front-end we need new RESTful API

## Changelog
`/transactions/{tx_hash}`
`/transactions/{tx_hash}/token-transfers`
`/transactions/{tx_hash}/internal-transactions`
`/transactions/{tx_hash}/logs`
`/transactions/{tx_hash}/raw-trace`

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2022-09-29 13:28 UTC, Qwerty5Uiop approved these changes

2022-09-29 19:09 UTC, sl1depengwyn requested changes

2022-09-29 19:09 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain.ex
> +      when is_list(options) do
Update spec according to new function parameters

2022-09-30 13:41 UTC, vbaranov reviewed
@nikitosing 

```
Server: localhost:4000 (http)
Request: GET /api/v2/transactions
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Explorer.Chain.recent_transactions/4
        (explorer 4.1.8) lib/explorer/chain.ex:6273: Explorer.Chain.recent_transactions([necessity_by_association: %{:block => :optional, [created_contract_address: :names] => :optional, [from_address: :names] => :optional, [to_address: :names] => :optional, [to_address: :smart_contract] => :optional}, paging_options: %Explorer.PagingOptions{asc_order: false, is_index_in_asc_order: false, is_pending_tx: false, key: nil, page_number: 1, page_size: 51}], [], [], [])
        (block_scout_web 4.1.8) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:62: BlockScoutWeb.API.V2.TransactionController.transactions/2
        (block_scout_web 4.1.8) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:1: BlockScoutWeb.API.V2.TransactionController.action/2
        (block_scout_web 4.1.8) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:1: BlockScoutWeb.API.V2.TransactionController.phoenix_controller_pipeline/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (phoenix 1.5.13) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (block_scout_web 4.1.8) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2
        (block_scout_web 4.1.8) lib/plug/debugger.ex:136: BlockScoutWeb.Endpoint."call (overridable 3)"/2
        (block_scout_web 4.1.8) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint."call (overridable 4)"/2
        (block_scout_web 4.1.8) lib/spandex_phoenix.ex:156: BlockScoutWeb.Endpoint.call/2
        (phoenix 1.5.13) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.9.0) /Users/barrakuda/Documents/code/blockscout/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /Users/barrakuda/Documents/code/blockscout/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /Users/barrakuda/Documents/code/blockscout/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

2022-10-03 07:15 UTC, sl1depengwyn approved these changes

2022-10-03 08:04 UTC, vbaranov approved these changes

2022-10-03 08:05 UTC, merged