Add verified contracts list page
blockscout/blockscout pull request #6324
Opened 2022-10-23 21:42 UTC by sl1depengwyn

## Changelog

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [x] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2022-10-25 12:08 UTC, nikitosing reviewed
for some reasons some contracts have infinite spinner

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/32202610/197768963-890b8991-f309-4468-9193-7df19e15db7b.png">

2022-10-29 09:29 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/chain.ex
> +  def paging_options(%{"smartcontract_id" => id}) do
Nitpick: let's split words by underscore: `smart_contract_id`

2022-11-01 10:14 UTC, vbaranov reviewed
@sl1depengwyn since you moved counters to /chain/cache directory, I think it makes more sense to move tests to the same sub-path. What do you think?

2022-11-01 14:43 UTC, vbaranov approved these changes

2022-11-01 17:40 UTC, nikitosing requested changes

2022-11-01 17:40 UTC, nikitosing commented on apps/explorer/lib/explorer/chain.ex
> +    |> filter_contracts(filter)
filter does not work with search

![image](https://user-images.githubusercontent.com/32202610/199293604-de49e784-12fe-4071-8cfc-03868838826f.png)

2022-11-01 17:40 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/controllers/verified_contracts_controller.ex
> +  @necessity_by_association %{[address: :token] => :required}
I think here you don't need :required, :optional will be enough, isnt it?

2022-11-01 17:40 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/templates/verified_contracts/_metatags.html.eex
> +<meta name="keywords" content="<%= "Verifed contracts, #{BlockScoutWeb.LayoutView.subnetwork_title()}, #{Explorer.coin()}" %>">
Let's add gettext for this line also

2022-11-02 07:56 UTC, nikitosing approved these changes

2022-11-02 19:35 UTC, merged