BS core API V2: addresses, stats, main page, websockets
blockscout/blockscout pull request #6361
Opened 2022-10-28 10:24 UTC by nikitosing

*[GitHub keywords to close any associated issues](https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/)*

## Motivation

*Why we should merge these changes.  If using GitHub keywords to close [issues](https://github.com/poanetwork/blockscout/issues), this is optional as the motivation can be read on the issue page.*

## Changelog

### Enhancements
*Things you added that don't break anything.  Regression tests for Bug Fixes count as Enhancements.*

### Bug Fixes
*Things you changed that fix bugs.  If a fixes a bug, but in so doing adds a new requirement, removes code, or requires a database reset and reindex, the breaking part of the change should be added to Incompatible Changes below also.*

### Incompatible Changes
*Things you broke while doing Enhancements and Bug Fixes.  Breaking changes include (1) adding new requirements and (2) removing code.  Renaming counts as (2) because a rename is a removal followed by an add.*

## Upgrading

*If you have any Incompatible Changes in the above Changelog, outline how users of prior versions can upgrade once this PR lands or when reviewers are testing locally.  A common upgrading step is "Database reset and re-index required".*

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2022-10-31 15:50 UTC, sl1depengwyn requested changes

2022-10-31 15:50 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/views/api/v2/helper.ex
>    def is_smart_contract(_), do: false
Consider adding following clause: (may fix previous comment)
```elixir
def is_smart_contract(%NotLoaded{}), do: nil
```

2022-10-31 16:13 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex
> +  end
Yes, it's not necessary since we do not need this info in log tile 

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/32202610/199055802-f5e1bce1-e2f0-44fa-b554-ef76d634c706.png">

2022-10-31 16:15 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/views/api/v2/helper.ex
>    def is_smart_contract(_), do: false
Thanks, added

2022-10-31 18:10 UTC, sl1depengwyn approved these changes

2022-11-01 11:39 UTC, vbaranov approved these changes

2022-11-01 11:40 UTC, merged