Add visualuze sol2uml controller
blockscout/blockscout pull request #6401
Opened 2022-11-06 16:15 UTC by sevenzing

*[GitHub keywords to close any associated issues](https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/)*

## Motivation

*Why we should merge these changes.  If using GitHub keywords to close [issues](https://github.com/poanetwork/blockscout/issues), this is optional as the motivation can be read on the issue page.*

## Changelog

### Enhancements
*Things you added that don't break anything.  Regression tests for Bug Fixes count as Enhancements.*

### Bug Fixes
*Things you changed that fix bugs.  If a fixes a bug, but in so doing adds a new requirement, removes code, or requires a database reset and reindex, the breaking part of the change should be added to Incompatible Changes below also.*

### Incompatible Changes
*Things you broke while doing Enhancements and Bug Fixes.  Breaking changes include (1) adding new requirements and (2) removing code.  Renaming counts as (2) because a rename is a removal followed by an add.*

## Upgrading

*If you have any Incompatible Changes in the above Changelog, outline how users of prior versions can upgrade once this PR lands or when reviewers are testing locally.  A common upgrading step is "Database reset and re-index required".*

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2022-11-11 15:52 UTC, nikitosing requested changes

2022-11-11 15:52 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/templates/visualize_sol2uml/index.html.eex
> +                        <img src="data:image/svg+xml;base64,<%= @svg %>"/>
let's add here style: max-width: 100%; max-height: 100%;
after adding style:

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/32202610/201368926-10d93b3e-c1a7-484c-99bf-1f717cfd28b5.png">

before:

<img width="1668" alt="image" src="https://user-images.githubusercontent.com/32202610/201369006-e79de1ae-17d3-4bbe-876a-feb8158f6fc5.png">

2022-11-11 15:52 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
> +              <span data-original-title="Visualize contract code using Sol2Uml JS library" data-placement="top" data-toggle="tooltip">
Why Sol2Uml is JS library?

2022-11-11 15:52 UTC, nikitosing commented on apps/explorer/lib/explorer/visualize/sol2uml.ex
> +      {:ok, %Response{body: body, status_code: _}} ->
about error handling. mb add here clauses for some of status codes

2022-11-11 15:52 UTC, nikitosing commented on apps/explorer/lib/explorer/visualize/sol2uml.ex
> +        {:error, body}
let's handle somehow error responses

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/32202610/201370603-7337d359-208d-4655-876a-19c097993f4a.png">

2022-11-11 15:52 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/controllers/visualize_sol2uml_controller.ex
> +         true <- Chain.smart_contract_fully_verified?(address_hash_string),
Mb add support for partially verified and twin contracts as well. As I see, button for such contracts do not hide

2022-11-11 15:52 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/controllers/visualize_sol2uml_controller.ex
> +        :smart_contract => :optional,
leave here only this line (`:smart_contract => :optional`), others are redundant

2022-11-11 16:10 UTC, sevenzing commented on apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
> +              <span data-original-title="Visualize contract code using Sol2Uml JS library" data-placement="top" data-toggle="tooltip">
it's a npm package. if you want, you can suggest another tooltip for this button

2022-11-12 09:11 UTC, nikitosing commented
@sevenzing also let's add async loading of svg image

2022-11-16 17:41 UTC, sevenzing commented on apps/block_scout_web/assets/webpack.config.js
> +      'img_viewer': './js/pages/img_viewer.js',
ok, but I renamed it to `sol2uml.js` because now this file is related only to sol2uml page

2022-11-16 17:42 UTC, sevenzing commented on apps/explorer/lib/explorer/visualize/sol2uml.ex
> +        {:error, body}
now, in case of error I return "failed to visualize contract" message to frontend and log the error

2022-11-16 17:43 UTC, sevenzing commented on apps/block_scout_web/lib/block_scout_web/controllers/visualize_sol2uml_controller.ex
> +         true <- Chain.smart_contract_fully_verified?(address_hash_string),
now I check that contract is verified using `!is_nil(address.smart_contract)`

2022-11-23 08:29 UTC, nikitosing commented
@sevenzing The last 2 moments:
1. let's hide sol2uml button for yul contracts (such contracts has null abi)
2. let's place buttons in a column for a small screen sizes
<img width="344" alt="image" src="https://user-images.githubusercontent.com/32202610/203500824-654d9fde-577f-4272-b10e-fea94bd52f94.png">

2022-11-23 09:28 UTC, nikitosing approved these changes

2022-11-23 15:07 UTC, vbaranov reviewed
@sevenzing 

- Could you please create a PR with the docs update in "Misc UI management" section in https://github.com/blockscout/docs/pulls since you introduce new env vars. An example of merged PR https://github.com/blockscout/docs/pull/93/files.
- Please add those env vars also below https://github.com/blockscout/blockscout/blob/master/docker/Makefile#L550-L552 like in these lines.
- And to the end of https://github.com/blockscout/blockscout/blob/master/docker-compose/envs/common-blockscout.env with the default values.

2022-11-23 15:14 UTC, vbaranov commented on apps/block_scout_web/assets/package.json
> -    "jquery": "^3.6.1",
@sevenzing what is the rationale to remove jquery from packages?

2022-11-23 16:20 UTC, vbaranov requested changes

2022-11-23 16:20 UTC, vbaranov commented on apps/explorer/lib/explorer/visualize/sol2uml.ex
> +  def base_url do
We have a similar function base_url/0 in `Explorer.SmartContract.RustVerifierInterface`. Can we define this function in a common helper, which will be used for both modules>

2022-11-23 16:20 UTC, vbaranov commented on apps/explorer/lib/explorer/visualize/sol2uml.ex
> +  @post_timeout :infinity
Shouldn't we change it to some limit, like 60 sec? Will not an unlimited timeout be a vector for DDoS of the application?

2022-11-23 16:20 UTC, vbaranov commented on apps/block_scout_web/assets/js/pages/sol2uml.js
> +        console.log('Got svg from server')
Could we omit this debug log?

2022-11-23 16:20 UTC, vbaranov commented on apps/block_scout_web/assets/js/pages/sol2uml.js
> +        console.log('Got error from server')
Could we omit this debug log?

2022-11-25 10:33 UTC, vbaranov reviewed
@sevenzing Please rebase to the recent master, and please add sol2uml service to all docker-compose configs. The rest looks good to me.

2022-11-25 10:33 UTC, vbaranov commented on docker-compose/envs/common-blockscout.env
> +VISUALIZE_SOL2UML_VISUALIZE_SOL2UML_SERVICE_URL=http://host.docker.internal:8050/
@sevenzing I suppose we need to add the service in each docker-compose config? Otherwise, docker-compose setup will be broken.

2022-11-27 18:36 UTC, vbaranov approved these changes

2022-11-27 18:36 UTC, merged