Fix state cahnges for contract creation transactions
blockscout/blockscout pull request #6473
Opened 2022-11-17 20:16 UTC by sl1depengwyn

Fix #6442 

## Changelog

Add handling of `nil` `address`  in template
Moved address hash from comment to `<tr>` tag attribute

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2022-11-17 20:39 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/controllers/transaction_state_controller.ex
>        from = transaction.from_address
Shouldn't definition of `from` here and `to` at line 88 be moved inside `if` statement since they also used only when `if` condition satisfied?

2022-11-18 07:57 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/controllers/transaction_state_controller.ex
>        from = transaction.from_address
Thanks for suggestion, make sense. Done

2022-11-18 08:49 UTC, vbaranov approved these changes

2022-11-18 14:59 UTC, nikitosing commented on apps/block_scout_web/test/block_scout_web/controllers/transaction_state_controller_test.exs
> +  alias Explorer.Factory
Why did you add this alias? Logs from tests run:
```
2022-11-18T07:59:44.2671783Z 
2022-11-18T07:59:44.4216520Z warning: unused alias Blocks
2022-11-18T07:59:44.4217328Z ##[warning]  test/block_scout_web/controllers/transaction_state_controller_test.exs:10
2022-11-18T07:59:44.4218030Z 
2022-11-18T07:59:44.4250503Z warning: unused alias Factory
2022-11-18T07:59:44.4251198Z ##[warning]  test/block_scout_web/controllers/transaction_state_controller_test.exs:11
2022-11-18T07:59:44.4251835Z 
```

2022-11-18 14:59 UTC, nikitosing approved these changes

2022-11-18 15:04 UTC, nikitosing commented
@sl1depengwyn why not to add `|> Enum.reject(&is_nil/1)` here https://github.com/blockscout/blockscout/pull/6473/files#diff-b89d6fbcaee2a35ef53a048f2c986f6af73b334169f12cfa652b7cb6506beabaR149 . Because now we just sending nulls to client, am I right?

2022-11-18 15:13 UTC, nikitosing requested changes
Please,
1. fix tests warnings
2. filter nulls in controller response

2022-11-24 06:36 UTC, sl1depengwyn commented
> @sl1depengwyn why not to add `[from_coin_entry, to_coin_entry, miner_entry | items] |> Enum.reject(&is_nil/1)` here
> 
> https://github.com/blockscout/blockscout/blob/8fe51600c73103441515132a0e043365ccb1214c/apps/block_scout_web/lib/block_scout_web/controllers/transaction_state_controller.ex#L149
> 
> . Because now we just sending nulls to client, am I right? (In case of contract creation tx for example)

Thanks, fixed
https://github.com/blockscout/blockscout/blob/cc4c19bee4706903d841b9081f01a19e2c19f329/apps/block_scout_web/lib/block_scout_web/controllers/transaction_state_controller.ex#L148-L150

2022-11-24 09:44 UTC, nikitosing approved these changes

2022-11-24 09:45 UTC, merged