Integrate sig provider
blockscout/blockscout pull request #6541
Opened 2022-12-02 13:19 UTC by nikitosing

Close #5579
Close #2385

## Changelog
- Integrate [sig provider](https://github.com/blockscout/blockscout-rs/tree/main/sig-provider)
- New env vars:
  - `DECODE_NOT_A_CONTRACT_CALLS`
  -  `SIG_PROVIDER_SERVICE_URL`
  -  `SIG_PROVIDER_ENABLED`

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2022-12-16 18:46 UTC, vbaranov commented
@nikitosing please rebase

2022-12-21 15:12 UTC, nikitosing commented
@vbaranov rebase done

2023-01-10 18:02 UTC, vbaranov requested changes
@nikitosing please add new environment variables to
- docker/Makefile
- docker-compose/envs/common-blockscout.env
Sig-provider service should be included to all docker-compose configs as itis done for Sol2UML visualizer service.

2023-01-10 18:27 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/transaction.ex
>        # In some cases transactions use methods of some unpredictadle contracts, so we can try to look up for method in a whole DB
```suggestion
      # In some cases transactions use methods of some unpredictable contracts, so we can try to look up for method in a whole DB
```

2023-01-10 18:33 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/transaction.ex
>    end
@nikitosing What is the whole point of `: decode_not_a_contract_calls` property? Why not try to decode every time if we have not empty input? What is the drawback of this approach? Afterall, in most cases, non-empty input in transaction to the address without bytecode is because Blockscout didn't get that bytecode yet, and actually this is a contract, no?

2023-01-12 08:50 UTC, nikitosing commented on apps/explorer/lib/explorer/chain/transaction.ex
>    end
In average case when chain is fully indexed it will be useless since blockscout should know if some tx are a contract call or not. This env will be useful only for partially indexed chains

2023-01-20 12:54 UTC, vbaranov approved these changes

2023-01-20 15:19 UTC, vbaranov approved these changes

2023-01-27 20:19 UTC, merged