Transaction actions indexer
blockscout/blockscout pull request #6582
Opened 2022-12-13 12:36 UTC by varasev

## Motivation

This is a part of https://github.com/blockscout/blockscout/issues/6289.

## Changelog

This PR contains the following features and changes:
- an indexer for tx actions
- an extension of API v2 to handle requests from the new UI

This PR adds support of one protocol yet (Uniswap V3). Other protocols will be added in the next PRs.

Indexing of tx actions runs with `realtime` and `catchup` block fetchers (if `DISABLE_INDEXER` is not `true`).

There is also a separate `transaction_action` fetcher for historical blocks which only runs if the block range is defined (see env variables description below). We need it for the case when we need to index tx actions for historical (already indexed) blocks of the chain or reindex tx actions for the defined block range (in case we found a bug in tx action indexer and need to reindex the actions for some blocks and/or protocols).

Also, the PR adds 4 new environment variables:
- `INDEXER_TX_ACTIONS_MAX_TOKEN_CACHE_SIZE` (defaults to 100000) - sets a maximum number of items in an internal cache of tx actions indexing process (to limit memory consumption).
- `INDEXER_TX_ACTIONS_REINDEX_FIRST_BLOCK` - defines the first block of a block range for historical indexing or reindexing of tx actions. If not defined, indexing only runs in real-time.
- `INDEXER_TX_ACTIONS_REINDEX_LAST_BLOCK` - defines the last block of a block range for historical indexing or reindexing of tx actions. If not defined, indexing only runs in real-time. Cannot exceed the last block of a chain.
- `INDEXER_TX_ACTIONS_REINDEX_PROTOCOLS` (defaults to empty string) - defines comma-separated names of protocols which should be indexed or reindexed on historical blocks defined by the range. Example: `uniswap_v3,zkbob` - only these protocols will be indexed or reindexed for the defined block range. If the value is empty string (or not defined), all supported protocols will be indexed/reindexed. This option is not applicable to `realtime` and `catchup` fetcher (it always indexes all supported protocols).

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2023-01-11 11:14 UTC, vbaranov requested changes
@varasev could you please also add new enironment variables into 
- docker/Makefile
- docker-compose/envs/common-blockscout.env (setting default values)

2023-01-11 11:14 UTC, vbaranov commented on .dialyzer-ignore
> +lib/block_scout_web/templates/transaction/_actions.html.eex:1
I would suggesting remove this line from dialyzer ignore. The problem actually is with this code in `_actions.html.eex`:
```
<% address_is_ok = (address_hash_status == :ok and address_status == :ok) %>
        <% address = if address_is_ok, do: render_to_string(BlockScoutWeb.AddressView, "_link.html", address: address, contract: BlockScoutWeb.AddressView.contract?(address), use_custom_tooltip: false, trimmed: false), else: render_to_string(BlockScoutWeb.TransactionView, "_actions_address.html", address_string: address_string, action: @action) %>
```

The first thing, I would suggest is to move it from template into the view helper. The issue is that in the previous lines you defined `address_hash_status` and `address_status` as:
```
<% {address_hash_status, address_hash} = Chain.string_to_address_hash(address_string) %>
<% {address_status, address} = Chain.hash_to_address(address_hash) %>
```

But since you expect {x, y} structure to return in `string_to_address_hash`, it automatically assume that x == :ok, because otherwise, this functions return `:error` (https://github.com/blockscout/blockscout/blob/master/apps/explorer/lib/explorer/chain.ex#L3520-L3525), and than no need to make this check:
```
<% address_is_ok = (address_hash_status == :ok and address_status == :ok) %>
```

This is what actually dialyzer is trying to tell, if I am not mistaken.

I suppose, you should change how you define `address_hash_status`.

2023-01-11 11:15 UTC, vbaranov commented
@varasev could you please also rebase the branch in order to resolve merging conflicts?

2023-01-11 11:28 UTC, vbaranov commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +        (first_topic == "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef" &&
"0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef" topic is used multiple times. Let's define as module attribute.

2023-01-11 11:30 UTC, vbaranov commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +          "0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67"
These topics are defined multiple times, could we also defined as an module attributes?

2023-01-11 11:31 UTC, vbaranov commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +    if first_topic == "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef" do
Should we, probably, change to compare only 4bytes signature instead of the whole topic?

2023-01-11 11:32 UTC, vbaranov commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +        if from == "0x0000000000000000000000000000000000000000" do
Let's use @burn_address instead here and everywhere in this file?

2023-01-11 11:34 UTC, vbaranov commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +  @null_address "0x0000000000000000000000000000000000000000"
Just to keep consistency: we call this as @burn_address throughout the application

2023-01-11 11:54 UTC, vbaranov commented
@varasev also, what will happen if catchup indexer ranges, which are managed by FIRST_BLOCk, LAST_BLOCK or and ranges for transaction action indexer (BLOCK_RANGES INDEXER_TX_ACTIONS_REINDEX_FIRST_BLOCK, INDEXER_TX_ACTIONS_REINDEX_LAST_BLOCK) don't match or inersects partially?

2023-01-11 13:22 UTC, vbaranov commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +    end
I would suggest to shorten this to something like:
```
            with false <- first_topic == "@transfer_topic",
         pool_address <- String.downcase(address_hash_to_string(log.address_hash)),
         false <- Enum.empty?(legitimate[pool_address]),
         token_address <- legitimate[pool_address],
         token_data <- get_token_data(token_address),
         false <- token_data === false do
      case first_topic do
        "@mint_event" ->
          # this is Mint event
          uniswap_handle_mint_event(log, token_address, token_data, chain_id)

        "@burn_event" ->
          # this is Burn event
          uniswap_handle_burn_event(log, token_address, token_data, chain_id)

        "@collect_event" ->
          # this is Collect event
          uniswap_handle_collect_event(log, token_address, token_data, chain_id)

        "@swap_event" ->
          # this is Swap event
          uniswap_handle_swap_event(log, token_address, token_data, chain_id)

        _ ->
          []
      end
    else
      _ ->
        []
    end
```

2023-01-12 11:25 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/transform/addresses.ex
> +
Let me suggest this way of writing this function: (in my opinion it's little bit more readable)
```elixir
  defp find_tx_action_addresses(data, accumulator \\ [])

  defp find_tx_action_addresses(data, accumulator) when is_map(data) or is_list(data) do
    Enum.reduce(data, accumulator, fn
      {_, value}, acc -> find_tx_action_addresses(value, acc)
      value, acc -> find_tx_action_addresses(value, acc)
    end)
  end

  defp find_tx_action_addresses(value, accumulator) when is_binary(value) do
    case Chain.string_to_address_hash(value) do
      {:ok, _} -> [value | accumulator] # [%{:fetched_coin_balance_block_number => block_number, :hash => value} | accumulator] if you agree with my previous comment
      _ -> accumulator
    end
  end

  defp find_tx_action_addresses(_value, accumulator), do: accumulator
```
bearing in mind Victor's remark

2023-01-12 11:25 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/transaction_action.ex
> +defmodule Indexer.Fetcher.TransactionAction do
Am I right that this `GenServer` do not terminate after fetching all tx actions, should we terminate it after fetching to release the resources kept by it?

2023-01-12 11:31 UTC, sl1depengwyn commented on apps/explorer/priv/repo/migrations/20221104091552_add_transaction_actions_table.exs
> +      add(:log_index, :integer, null: false, primary_key: true)
As I understand `:hash` field forms a composite primary key with `log_index`

2023-01-12 11:32 UTC, sl1depengwyn commented on .dialyzer-ignore
> +lib/block_scout_web/templates/transaction/_actions.html.eex:1
I would suggest to use something like this: (like in the majority of our controllers)
```elixir
with {:ok, address_hash} <- Chain.string_to_address_hash(address_hash_string),
         {:ok, address} <- Chain.hash_to_address(address_hash) do
...
else
    :error -> ...
...
end
```

2023-01-12 17:57 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/transaction_action.ex
> +defmodule Indexer.Fetcher.TransactionAction do
Also, it seems that block range defined for transaction actions fetcher will be re-fetched on each app restart, is it expected behavior, maybe we can somehow store info that everything fetched to avoid consuming resources, this block range I suppose could be huge

2023-01-13 06:01 UTC, sl1depengwyn commented
Also, I'm having troubles with app start on clean db. Transaction fetcher do not let the app start without provided env variables (from and last block), from and last block must be > 0, but if set them to first=1 last=1, for instance, fetcher complains that last block is greater than max block in the db (=0 since db is empty), it seems that there is no way to start app

2023-01-13 13:41 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/templates/transaction/_actions.html.eex
> +        <%= gettext("Mint of %{address} <span class=\"text-muted\">To</span> %{to}", address: address, to: safe_to_string(to)) |> raw() %>
May be add here `text-muted` to `Mint` too, as in other actions?

2023-01-13 15:02 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +    end)
Rewriting this in such a way probably will give a considerable speed up (all changed lines are commented for easier diff)
```elixir
mint_nft = tx_logs # keep mint_nft actions in a var
    |> Enum.reduce(%{}, fn log, acc ->
      first_topic = String.downcase(log.first_topic)

      if first_topic == "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef" do
        # This is Transfer event for NFT
        from = truncate_address_hash(log.second_topic)

        if from == "0x0000000000000000000000000000000000000000" do
          to = truncate_address_hash(log.third_topic)
          [token_id] = decode_data(log.fourth_topic, [{:uint, 256}])
          mint_nft_ids = Map.put_new(acc, to, %{ids: [], log_index: log.index})

          Map.put(mint_nft_ids, to, %{
            ids: Enum.reverse([to_string(token_id) | Enum.reverse(mint_nft_ids[to].ids)]),
            log_index: mint_nft_ids[to].log_index
          })
        else
          acc
        end
      else
        acc
      end
    end)
    |> Enum.reduce([], fn {to, %{ids: ids, log_index: log_index}}, acc -> # start reduce with empty list
      action = %{
        hash: tx_hash,
        protocol: "uniswap_v3",
        data: %{
          name: "Uniswap V3: Positions NFT",
          symbol: "UNI-V3-POS",
          address: @uniswap_v3_positions_nft,
          to: Address.checksum(to),
          ids: ids,
          block_number: first_log.block_number
        },
        type: "mint_nft",
        log_index: log_index
      }

      [action | acc] # just cons without reverse
    end)
    |> Enum.reverse() # reverse whole list once

    actions_acc ++ mint_nft # append list to all actions
```

2023-01-13 15:27 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +          Enum.reverse([address | Enum.reverse(acc)])
same here

2023-01-22 12:11 UTC, varasev commented
> @varasev could you please also add new enironment variables into
> 
> * docker/Makefile
> * docker-compose/envs/common-blockscout.env (setting default values)

Done in https://github.com/blockscout/blockscout/pull/6582/commits/9aa9c5399e19348c11870e1b27aff8e0cfd722d2.

2023-01-22 12:12 UTC, varasev commented on config/runtime.exs
> +  tx_actions_max_token_cache_size: System.get_env("INDEXER_TX_ACTIONS_MAX_TOKEN_CACHE_SIZE")
Done in https://github.com/blockscout/blockscout/pull/6582/commits/9aa9c5399e19348c11870e1b27aff8e0cfd722d2.

2023-01-22 12:12 UTC, varasev commented on apps/block_scout_web/lib/block_scout_web/templates/transaction/_actions.html.eex
> +          <%= gettext("<span class=\"text-muted\">Add</span> %{amount0} %{symbol0} <span class=\"text-muted\">And</span> %{amount1} %{symbol1} <span class=\"text-muted\">Liquidity To Uniswap V3</span
Done in https://github.com/blockscout/blockscout/pull/6582/commits/9aa9c5399e19348c11870e1b27aff8e0cfd722d2.

2023-01-22 12:16 UTC, varasev commented on apps/explorer/priv/repo/migrations/20221104091552_add_transaction_actions_table.exs
> +      add(:log_index, :integer, null: false, primary_key: true)
@vbaranov @sl1depengwyn Yes, it's in a composite index with the `hash` field.

2023-01-22 12:19 UTC, varasev commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +    if first_topic == "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef" do
I think it's better to compare all of the bytes because Event's signature consists of 32 bytes, not 4 bytes like for function's signature.

2023-01-22 12:27 UTC, varasev commented
> Also, I'm having troubles with app start on clean db. Transaction fetcher do not let the app start without provided env variables (from and last block), from and last block must be > 0, but if set them to first=1 last=1, for instance, fetcher complains that last block is greater than max block in the db (=0 since db is empty), it seems that there is no way to start app

You mean `FIRST_BLOCK` and `LAST_BLOCK`? If so, this is not related to this PR.

2023-01-22 12:28 UTC, varasev commented on apps/block_scout_web/lib/block_scout_web/templates/transaction/_actions.html.eex
> +        <%= gettext("Mint of %{address} <span class=\"text-muted\">To</span> %{to}", address: address, to: safe_to_string(to)) |> raw() %>
No, I took the example from here: https://etherscan.io/tx/0x192a4604f6dc3a27c7689f395e9ae3b2742b149db5afdafe357b086069537ed2 - it's without muting there.

2023-01-22 12:32 UTC, varasev commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +          put_token_data_to_cache(request.contract_address, new_data)
The token data will be fetched (and written to db) by the indexer itself, so I think we don't.

2023-01-22 12:38 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/transaction_action.ex
> +defmodule Indexer.Fetcher.TransactionAction do
It's disabled by default because if `INDEXER_TX_ACTIONS_REINDEX_FIRST_BLOCK` or `INDEXER_TX_ACTIONS_REINDEX_LAST_BLOCK` is not defined, the fetcher won't be launched: https://github.com/blockscout/blockscout/blob/9aa9c5399e19348c11870e1b27aff8e0cfd722d2/apps/indexer/lib/indexer/fetcher/transaction_action.ex#L52-L59 - so, I believe another `enable/disable` config option would be redundant.

2023-01-22 13:01 UTC, varasev commented
> @varasev also, what will happen if catchup indexer ranges, which are managed by FIRST_BLOCk, LAST_BLOCK or and ranges for transaction action indexer (BLOCK_RANGES INDEXER_TX_ACTIONS_REINDEX_FIRST_BLOCK, INDEXER_TX_ACTIONS_REINDEX_LAST_BLOCK) don't match or inersects partially?

The use case for `Indexer.Fetcher.TransactionAction` is to fetch tx actions for already indexed logs existed in DB (that only uses the `logs` table). We shouldn't use `Indexer.Fetcher.TransactionAction` if we index the chain by the regular catchup indexer (as tx actions will be handled there by `Indexer.Transform.TransactionActions`).

So, it's better to launch `Indexer.Fetcher.TransactionAction` after all blocks are indexed by the catchup. But if the ranges intersect, the existing tx actions will just be rewritten in DB.

2023-01-22 13:06 UTC, sl1depengwyn commented
> * INDEXER_TX_ACTIONS_REINDEX_FIRST_BLOCK



> > Also, I'm having troubles with app start on clean db. Transaction fetcher do not let the app start without provided env variables (from and last block), from and last block must be > 0, but if set them to first=1 last=1, for instance, fetcher complains that last block is greater than max block in the db (=0 since db is empty), it seems that there is no way to start app
> 
> You mean `FIRST_BLOCK` and `LAST_BLOCK`? If so, this is not related to this PR.

I understood that fetcher does not start when `INDEXER_TX_ACTIONS_REINDEX_FIRST_BLOCK` and `INDEXER_TX_ACTIONS_REINDEX_LAST_BLOCK` are not provided, thanks

2023-01-22 13:23 UTC, varasev commented
> > * INDEXER_TX_ACTIONS_REINDEX_FIRST_BLOCK
> 
> > > Also, I'm having troubles with app start on clean db. Transaction fetcher do not let the app start without provided env variables (from and last block), from and last block must be > 0, but if set them to first=1 last=1, for instance, fetcher complains that last block is greater than max block in the db (=0 since db is empty), it seems that there is no way to start app
> > 
> > 
> > You mean `FIRST_BLOCK` and `LAST_BLOCK`? If so, this is not related to this PR.
> 
> I understood that fetcher does not start when `INDEXER_TX_ACTIONS_REINDEX_FIRST_BLOCK` and `INDEXER_TX_ACTIONS_REINDEX_LAST_BLOCK` are not provided, thanks

Ok. From my side I thought you meant `Transaction fetcher`, not `Transaction actions fetcher`.

2023-01-22 16:00 UTC, varasev commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +    end
Done in https://github.com/blockscout/blockscout/commit/97c2d17d508f5fff82c5ceeda8d938a7bd8e1b9e.

2023-01-22 16:19 UTC, varasev commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
> +           Repo.preload(preloaded, :transaction_actions) do
Did you mean `@transaction_necessity_by_association`? The suggested `@token_transfers_in_tx_neccessity_by_association` relates to token transfers.

Anyway, I believe we need to keep `Repo.preload` here because `@transaction_necessity_by_association` is also used in the `transactions` function which is responsible for getting transaction list, but we don't need to read actions for tx list - we only need them on tx page.

2023-01-22 17:12 UTC, varasev commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +    end)
Good hint, thx. Applied in https://github.com/blockscout/blockscout/pull/6582/commits/db537188b6b7f2aca1f9567fab248b98d814afd3.

2023-01-22 17:12 UTC, varasev commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +      end)
Done in https://github.com/blockscout/blockscout/pull/6582/commits/db537188b6b7f2aca1f9567fab248b98d814afd3.

2023-01-22 17:12 UTC, varasev commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +          Enum.reverse([address | Enum.reverse(acc)])
Done in https://github.com/blockscout/blockscout/pull/6582/commits/db537188b6b7f2aca1f9567fab248b98d814afd3.

2023-01-23 11:56 UTC, varasev commented on apps/indexer/lib/indexer/transform/addresses.ex
> +  defp is_address?(value) do
Hmm, I discovered that `Chain.string_to_address_hash` has incorrect behaviour for floating-point numbers presented as string, for example:

```
require Logger
Logger.warn(inspect(Chain.string_to_address_hash("2.416505220404223741")))
```

will print

```
{:ok, %Explorer.Chain.Hash{byte_count: 20, bytes: "2.416505220404223741"}}
```

So, I will keep my `is_address?` function yet.

2023-01-23 12:00 UTC, varasev commented on apps/indexer/lib/indexer/transform/addresses.ex
> +
Done in https://github.com/blockscout/blockscout/pull/6582/commits/704194cefab9fcacef5f8288b6f3868486d9caa7.

2023-01-23 12:18 UTC, varasev commented on apps/indexer/lib/indexer/transform/addresses.ex
> +          %{:fetched_coin_balance_block_number => block_number, :hash => address}
Done in https://github.com/blockscout/blockscout/pull/6582/commits/7907856bb2c768282a80ba6a1f8c5bbce354714a.

2023-01-23 12:40 UTC, varasev commented on apps/block_scout_web/lib/block_scout_web/templates/transaction/_actions.html.eex
> +        <% amount1 = BlockScoutWeb.CldrHelper.Number.to_string!(Decimal.new(amount1), format: "#,##0.##################") %>
Done in https://github.com/blockscout/blockscout/pull/6582/commits/784dc88a86ba1711cd18dbda5eeb09944841a56c.

2023-01-23 12:46 UTC, varasev commented on apps/explorer/lib/explorer/chain/transaction_actions.ex
> +  @supported_protocols [:uniswap_v3, :"opensea_v1.1", :wrapping, :approval, :zkbob]
I think no, but ok, renamed it: https://github.com/blockscout/blockscout/pull/6582/commits/022e1b40df46de9b94d9ae470969bc57c15b143b

2023-01-23 12:48 UTC, varasev commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +    # logs
Removed in https://github.com/blockscout/blockscout/pull/6582/commits/1579c758bac6f6620cec55f50fe9a1ef39d5cdac.

2023-01-23 13:33 UTC, varasev commented on apps/indexer/lib/indexer/transform/addresses.ex
> +
@sl1depengwyn But now it makes dialyzer return the following error:

```
lib/indexer/transform/addresses.ex:1:pattern_match
The pattern can never match the type.

Pattern:
false

Type:
true
```

Do you have any ideas why?

2023-01-23 13:39 UTC, varasev commented on .dialyzer-ignore
> +lib/block_scout_web/templates/transaction/_actions.html.eex:1
Thanks for explanations. Done in https://github.com/blockscout/blockscout/pull/6582/commits/d11271e99a10ec8b3342ea62abd7cab4d2c4d6ec.

2023-01-23 14:03 UTC, varasev commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +        (first_topic == "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef" &&
Done in https://github.com/blockscout/blockscout/pull/6582/commits/5765125f8563e5fd11ddffe0f3ba960f9ef9f0a5.

2023-01-23 14:03 UTC, varasev commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +          "0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67"
Done in https://github.com/blockscout/blockscout/pull/6582/commits/5765125f8563e5fd11ddffe0f3ba960f9ef9f0a5.

2023-01-23 14:03 UTC, varasev commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +        if from == "0x0000000000000000000000000000000000000000" do
Done in https://github.com/blockscout/blockscout/pull/6582/commits/5765125f8563e5fd11ddffe0f3ba960f9ef9f0a5.

2023-01-23 15:28 UTC, varasev commented on apps/explorer/lib/explorer/chain/import/runner/transaction_actions.ex
> +    # Enforce TransactionActions ShareLocks order (see docs: sharelocks.md)
Done in https://github.com/blockscout/docs/pull/101/commits/2b7b456c55274bbef777e01484e3296e31819a19.

2023-01-23 15:48 UTC, varasev commented on apps/explorer/lib/explorer/chain/transaction_actions.ex
> +defmodule Explorer.Chain.TransactionActions do
Done in https://github.com/blockscout/blockscout/pull/6582/commits/18fcc3561e851bde01d6ab66929efe4b65853c3e.

2023-01-23 15:56 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/transaction_action.ex
> +defmodule Indexer.Fetcher.TransactionAction do
> Am I right that this GenServer do not terminate after fetching all tx actions

I will check it.

> it seems that block range defined for transaction actions fetcher will be re-fetched on each app restart

I have an idea how to fix it. Will implement

2023-01-24 14:25 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
> +           Repo.preload(preloaded, :transaction_actions) do
No, I meant `@token_transfers_in_tx_neccessity_by_association` because its used to fetch `preloaded` that you use as first argument to `Repo.preload/2` and it used only in this place in the file, so I think it's okay to edit it.
https://github.com/blockscout/blockscout/blob/3bc618dac7ff7d4d52be78bd754a33a6425f44f7/apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex#L73-L76

2023-01-24 16:26 UTC, varasev commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
> +           Repo.preload(preloaded, :transaction_actions) do
@sl1depengwyn maybe we need to rename `token_transfers_in_tx_neccessity_by_association` then? Since tx actions are not related to token transfers.

2023-01-24 16:48 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
> +           Repo.preload(preloaded, :transaction_actions) do
I think this name means that we want to get txs with token transfers , am I right @nikitosing? So, maybe we should rename it to something like `tx_actions_and_tts_in_tx_neccessity_by_association`

2023-01-24 17:11 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
> +           Repo.preload(preloaded, :transaction_actions) do
let's set just `@transaction_neccessity_by_association`

2023-01-24 17:18 UTC, varasev commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
> +           Repo.preload(preloaded, :transaction_actions) do
@nikitosing we already discussed it above: `@transaction_necessity_by_association` is also used in the `transactions` function which is responsible for getting transaction list, but we don't need to read actions for tx list - we only need them on tx page.

2023-01-24 17:20 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
> +           Repo.preload(preloaded, :transaction_actions) do
Didn't see that it's already defined, sorry, then can suggest `@single_transaction_neccessity_by_association`

2023-01-24 18:12 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/transform/addresses.ex
> +
Not sure about the reasons, but it seems that it refers to these lines (especially if statement):
https://github.com/blockscout/blockscout/blob/ea6a38390e2651842dc5d8746bb810c96f162e99/apps/indexer/lib/indexer/transform/addresses.ex#L471-L475
removing or modifying it removes the error
As I understand dialyzer thinks that `is_address?` always return false here

2023-01-24 18:21 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/transform/addresses.ex
> +
Okay, I got it, the actual thing dialyzer reports is that we check that value is_binary in guard expression in `find_tx_action_addresses` then we have `if is_binary(value) do` in `is_address?` and dialyzer says that in if statement in `is_address?` function we never get false

2023-01-25 08:33 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/transaction_action.ex
> +defmodule Indexer.Fetcher.TransactionAction do
> Am I right that this GenServer do not terminate after fetching all tx actions, should we terminate it after fetching to release the resources kept by it?

Is this a proper way to finish GenServer process? https://github.com/blockscout/blockscout/pull/6582/commits/00fa2643b5872e2c8bd5f91eef9d1c55537c290a

I didn't find examples in Blockscout code

2023-01-25 08:44 UTC, varasev commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
> +           Repo.preload(preloaded, :transaction_actions) do
So, I need to add `@single_transaction_neccessity_by_association` and add one more function (say, `Chain.preload_tx_actions`)? Maybe we just keep one-line `Repo.preload` solution?

2023-01-25 08:49 UTC, varasev commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
> +           Repo.preload(preloaded, :transaction_actions) do
Or you mean concat `@single_transaction_neccessity_by_association` to `@transaction_necessity_by_association` in this line https://github.com/blockscout/blockscout/blob/00fa2643b5872e2c8bd5f91eef9d1c55537c290a/apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex#L69 ?

2023-01-25 08:58 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
> +           Repo.preload(preloaded, :transaction_actions) do
I think the second variant but rename: `@single_transaction_neccessity_by_association` -> `@transaction_actions_neccessity_by_association` (I only now got the whole context) where @transaction_actions_neccessity_by_association contains [transaction_actions: :optional]

2023-01-25 08:59 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/transaction_action.ex
> +defmodule Indexer.Fetcher.TransactionAction do
I think it's better to add `restart: :transient` to this line:
https://github.com/blockscout/blockscout/blob/00fa2643b5872e2c8bd5f91eef9d1c55537c290a/apps/indexer/lib/indexer/fetcher/transaction_action.ex#L32
And stop gen server with `{:stop, :normal, state}`
You can check this example https://github.com/blockscout/blockscout/blob/mf-withdrawals/apps/indexer/lib/indexer/fetcher/withdrawal.ex

2023-01-25 09:08 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
> +           Repo.preload(preloaded, :transaction_actions) do
Or more simpler: 
`Map.put(@transaction_necessity_by_association, :transaction_actions, :optional)` on the 69th line

2023-01-25 09:15 UTC, varasev commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
> +           Repo.preload(preloaded, :transaction_actions) do
Ok, done: https://github.com/blockscout/blockscout/pull/6582/commits/d6fcef4b191c5d6e7e95f7612b7060cb572fc985

2023-01-25 10:13 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/transaction_action.ex
> +defmodule Indexer.Fetcher.TransactionAction do
Ok, thanks, done in https://github.com/blockscout/blockscout/pull/6582/commits/2201b164cd268db1e455b2c319a81114c18072a5

2023-01-25 13:25 UTC, varasev commented on apps/indexer/lib/indexer/transform/addresses.ex
> +
Ok, looks like this is the fix: https://github.com/blockscout/blockscout/commit/74c9b74bfbaf005a664f18b5a15520d137d0605c

2023-01-26 14:32 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/transaction_action.ex
> +defmodule Indexer.Fetcher.TransactionAction do
> Also, it seems that block range defined for transaction actions fetcher will be re-fetched on each app restart, is it expected behavior, maybe we can somehow store info that everything fetched to avoid consuming resources, I suppose this block range could be huge

I added stage keeping here: https://github.com/blockscout/blockscout/pull/6582/commits/a4641ba197aad3d1ecbddf25698c9fff78e6213a

Now the fetcher checks whether `first_block/last_block` saved in DB are the same as in env variables: if they are, the fetcher continues work from the last block it previously stopped on; if they are different, the fetcher starts from `first_block`.

2023-01-26 14:34 UTC, varasev commented
@nikitosing I finished working on the reviewers' comments. Now you can review as well. Thanks

2023-01-26 15:04 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/transaction_action.ex
> +defmodule Indexer.Fetcher.TransactionAction do
Maybe we can use `last_fetched_counters` table for it? @vbaranov what do you think?

2023-01-26 17:00 UTC, vbaranov commented on apps/indexer/lib/indexer/fetcher/transaction_action.ex
> +defmodule Indexer.Fetcher.TransactionAction do
Yes, agree. We could save the state into `last_fetched_counters` table.

2023-01-27 12:42 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/transaction_action.ex
> +defmodule Indexer.Fetcher.TransactionAction do
Ok, updated: https://github.com/blockscout/blockscout/pull/6582/commits/ff82fd01a694f7e577467ba15015ee02a7799623.

2023-01-30 14:47 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/templates/transaction/_actions_uniswap.html.eex
> +<%= gettext("<span class=\"text-muted\">%{action}</span> %{amount0} %{symbol0} <span class=\"text-muted\">%{conjunction}</span> %{amount1} %{symbol1} <span class=\"text-muted\">%{tail}</span>", actio
Why do use gettext here?

2023-01-30 14:57 UTC, varasev commented on apps/block_scout_web/lib/block_scout_web/templates/transaction/_actions_uniswap.html.eex
> +<%= gettext("<span class=\"text-muted\">%{action}</span> %{amount0} %{symbol0} <span class=\"text-muted\">%{conjunction}</span> %{amount1} %{symbol1} <span class=\"text-muted\">%{tail}</span>", actio
There was an English text that was replaced with `%{...}` items. I forgot to remove `gettext`. Will fix it

2023-01-31 02:39 UTC, varasev commented on apps/block_scout_web/lib/block_scout_web/templates/transaction/_actions_uniswap.html.eex
> +<%= gettext("<span class=\"text-muted\">%{action}</span> %{amount0} %{symbol0} <span class=\"text-muted\">%{conjunction}</span> %{amount1} %{symbol1} <span class=\"text-muted\">%{tail}</span>", actio
Fixed in https://github.com/blockscout/blockscout/pull/6582/commits/6f5d39460964ebe3150aff36ad7fb725c0851360

2023-01-31 07:51 UTC, nikitosing commented on apps/indexer/lib/indexer/transform/addresses.ex
> +    |> Enum.concat(tx_actions_addresses)
Do we need in this module tx actions at all? As I understand we already indexing all events which may introduce new addresses. Tx actions are only the new convinient representation for all other events (transfer, logs). Isn't it?

2023-01-31 08:20 UTC, varasev commented on apps/indexer/lib/indexer/transform/addresses.ex
> +    |> Enum.concat(tx_actions_addresses)
> Do we need in this module tx actions at all? As I understand we already indexing all events which may introduce new addresses. Tx actions are only the new convinient representation for all other events (transfer, logs). Isn't it?

Yes, we need, because addresses from events' params are not parsed anywhere

2023-01-31 08:40 UTC, nikitosing approved these changes

2023-01-31 08:42 UTC, nikitosing commented
@varasev Can you please fix failing tests?

2023-01-31 09:17 UTC, varasev commented
> @varasev Can you please fix failing tests?

Do you mean the following one?

```
Error:      test/indexer/block/realtime/fetcher_test.exs:45
     ** (FunctionClauseError) no function clause matching in anonymous fn/2 in Indexer.Block.Realtime.FetcherTest."test Indexer.Block.Fetcher.fetch_and_import_range/1 in range with internal transactions"/1

     The following arguments were given to anonymous fn/2 in Indexer.Block.Realtime.FetcherTest."test Indexer.Block.Fetcher.fetch_and_import_range/1 in range with internal transactions"/1:
     
         # 1
         %{id: 0, jsonrpc: "2.0", method: "net_version", params: []}
```

I can't reproduce it locally for some reason 🤔  Trying to run:

```
cd apps/indexer
export MIX_ENV=test
mix test --no-start --exclude no_nethermind
```

Am I missing something?

2023-01-31 10:42 UTC, vbaranov commented
> > @varasev Can you please fix failing tests?
> 
> Do you mean the following one?
> 
> ```
> Error:      test/indexer/block/realtime/fetcher_test.exs:45
>      ** (FunctionClauseError) no function clause matching in anonymous fn/2 in Indexer.Block.Realtime.FetcherTest."test Indexer.Block.Fetcher.fetch_and_import_range/1 in range with internal transactions"/1
> 
>      The following arguments were given to anonymous fn/2 in Indexer.Block.Realtime.FetcherTest."test Indexer.Block.Fetcher.fetch_and_import_range/1 in range with internal transactions"/1:
>      
>          # 1
>          %{id: 0, jsonrpc: "2.0", method: "net_version", params: []}
> ```
> 
> I can't reproduce it locally for some reason 🤔 Trying to run:
> 
> ```
> cd apps/indexer
> export MIX_ENV=test
> mix test --no-start --exclude no_nethermind
> ```
> 
> Am I missing something?

All is good. There were blinking tests. All are green after a manual restart.

2023-01-31 17:53 UTC, varasev commented
I added `INDEXER_TX_ACTIONS_ENABLE` env variable (defaults to `false`) in https://github.com/blockscout/blockscout/pull/6582/commits/be99681177866db9f8c2e1a3fbfa75ce7195d8a5.

2023-02-03 11:39 UTC, vbaranov approved these changes

2023-02-03 11:39 UTC, merged