Unhandled division by 0
blockscout/blockscout pull request #6599
Opened 2022-12-15 16:19 UTC by helderjnpinto

Fix the division if is 0

*[GitHub keywords to close any associated issues]
Trying resolve the issue #6598 
 
## Changelog 
### Bug Fixes
 Handle zero division on fetcher of indexer

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2022-12-15 16:23 UTC, helderjnpinto commented
In this case is no_blocks_to_import is zero maybe the Prometheus.Instrumenter.block_import is not to apply :man_shrugging: ?  or divided by 1 to insert the time like as is ...

@vbaranov what you think ?

2022-12-15 17:29 UTC, sl1depengwyn requested changes
Actually, I think it's better not to apply `Prometheus.Instrumenter.block_import` when `no_blocks_to_import` is zero. Thank you very much for pointin it out!

2022-12-15 17:29 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/block/fetcher.ex
> +    no_blocks_to_import_div = if Decimal.compare(no_blocks_to_import, 0) == :eq, do: 1, else: no_blocks_to_import
I think `if Decimal.equal?(no_blocks_to_import, 0), do: 1, else, no_blocks_to_import` is a bit more readable

2022-12-16 09:58 UTC, helderjnpinto commented
> Actually, I think it's better not to apply `Prometheus.Instrumenter.block_import` when `no_blocks_to_import` is zero. Thank you very much for pointin it out! I would write something like this
> 
> ```
> no_blocks_to_import = length(options_with_broadcast.blocks.params)
> if no_blocks_to_import != 0 do
>     Prometheus.Instrumenter.block_import(import_time / no_blocks_to_import, callback_module)
> end
> result
> ```

yes i agree, LGTM !

2022-12-16 10:00 UTC, sl1depengwyn approved these changes

2022-12-16 10:19 UTC, merged