Permanent UI dark mode
blockscout/blockscout pull request #6763
Opened 2023-01-25 14:37 UTC by vbaranov

Resolves https://github.com/blockscout/blockscout/issues/6718

## Motivation

With runtime ENV variable `PERMANENT_DARK_MODE_ENABLED=true` it is now possible.

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2023-01-26 13:01 UTC, sl1depengwyn requested changes

2023-01-26 13:01 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
> +        const permanentDarkModeEnabled = document.getElementById('permanent-dark-mode').textContent === 'true'
Here we can either extract this script to some js file (maybe to `layout.js` it should work) and use there `process.env.PERMANENT_DARK_MODE_ENABLED`, or get this env through elixir `Application.get_env`

2023-01-26 19:07 UTC, vbaranov commented on apps/block_scout_web/assets/js/lib/history_chart.js
> +  const permanentDarkModeEnabled = document.getElementById('permanent-dark-mode').textContent === 'true'
Honestly, I against this, because this will turn this ENV var to compile-time var, which we want to avoid.

2023-01-26 19:11 UTC, vbaranov commented on apps/block_scout_web/assets/js/lib/history_chart.js
> +  const permanentDarkModeEnabled = document.getElementById('permanent-dark-mode').textContent === 'true'
It gives less flexibility having it as compile-time env var. I am for Blocskcout maintainer has the ability to make UI changes without recompiling the application.

2023-01-27 07:53 UTC, sl1depengwyn commented on apps/block_scout_web/assets/js/lib/history_chart.js
> +  const permanentDarkModeEnabled = document.getElementById('permanent-dark-mode').textContent === 'true'
Okay then, make sense

2023-01-27 10:42 UTC, sl1depengwyn approved these changes

2023-01-27 14:23 UTC, merged