Mf sort token balances by value
blockscout/blockscout pull request #6925
Opened 2023-02-17 14:33 UTC by sl1depengwyn

Close #6547 
Close #6855 

## Motivation

It happened that now we have no token price feature in master branch. Also, we sorted token balances by value that is not very useful for user. Additionally, we had issue of paginating balances of ERC-1155 or ERC-721 tokens when user have the same amount of different token ids of the same token 

## Changelog

To be able to sort and paginate token balances I implemented new token balance fetch

### Enhancements
*Things you added that don't break anything.  Regression tests for Bug Fixes count as Enhancements.*

### Bug Fixes
*Things you changed that fix bugs.  If a fixes a bug, but in so doing adds a new requirement, removes code, or requires a database reset and reindex, the breaking part of the change should be added to Incompatible Changes below also.*

### Incompatible Changes
*Things you broke while doing Enhancements and Bug Fixes.  Breaking changes include (1) adding new requirements and (2) removing code.  Renaming counts as (2) because a rename is a removal followed by an add.*

## Upgrading

*If you have any Incompatible Changes in the above Changelog, outline how users of prior versions can upgrade once this PR lands or when reviewers are testing locally.  A common upgrading step is "Database reset and re-index required".*

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2023-02-22 14:47 UTC, vbaranov commented on config/runtime.exs
> +  case "TOKEN_EXCANGE_RATE_INTERVAL" |> System.get_env("") |> String.downcase() |> Integer.parse() do
@sl1depengwyn Typo, missing "h". Also, please fix in the docs https://github.com/blockscout/docs/pull/117

2023-02-22 14:47 UTC, vbaranov commented on config/runtime.exs
> +  case "TOKEN_EXCANGE_RATE_REFETCH_INTERVAL" |> System.get_env("") |> String.downcase() |> Integer.parse() do
Typo

2023-02-22 14:47 UTC, vbaranov commented on config/runtime.exs
> +  case "TOKEN_EXCANGE_RATE_MAX_BATCH_SIZE" |> System.get_env("") |> Integer.parse() do
Typo

2023-02-22 14:47 UTC, vbaranov commented on config/runtime.exs
> +  enabled: System.get_env("DISABLE_TOKEN_EXCANGE_RATE") != "true",
Typo

2023-02-22 15:01 UTC, vbaranov reviewed
@sl1depengwyn does it make sense to display price on "top tokens page" `/tokens` as well and make the same default sorting?

2023-02-22 15:10 UTC, sl1depengwyn commented
> @sl1depengwyn does it make sense to display price on top tokens page `/tokens` as well and make the same default sorting?

You mean sort by total supply * token price? In this case I think it make sense

2023-02-22 15:28 UTC, vbaranov commented
> > @sl1depengwyn does it make sense to display price on top tokens page `/tokens` as well and make the same default sorting?
> 
> You mean sort by total supply * token price? In this case I think it make sense

yes

2023-03-08 11:56 UTC, vbaranov requested changes
/verified-contracts page doesn't open with the changes

```
Request: GET /verified-contracts?type=JSON
** (exit) an exception was raised:
    ** (KeyError) key :market_cap not found in: %Explorer.Chain.Token{__meta__: #Ecto.Schema.Metadata<:loaded, "tokens">, name: "Seizon", symbol: "Seizon", total_supply: #Decimal<7573>, decimals: nil, type: "ERC-721", cataloged: true, holder_count: 3362, skip_metadata: nil, total_supply_updated_at_block: nil, fiat_value: nil, circulating_market_cap: nil, contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<166, 205, 39, 40, 116, 238, 124, 135, 46, 182, 104, 1, 239, 246, 39, 132, 192, 177, 50, 133>>}, contract_address: #Ecto.Association.NotLoaded<association :contract_address is not loaded>, inserted_at: ~U[2023-03-06 23:59:07.423871Z], updated_at: ~U[2023-03-08 11:53:03.304706Z]}
        (block_scout_web 5.1.1) lib/block_scout_web/templates/verified_contracts/_contract.html.eex:58: BlockScoutWeb.VerifiedContractsView."_contract.html"/1
        (phoenix 1.5.13) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3
        (phoenix 1.5.13) lib/phoenix/view.ex:479: Phoenix.View.render_to_string/3
        (block_scout_web 5.1.1) lib/block_scout_web/controllers/verified_contracts_controller.ex:27: anonymous fn/2 in BlockScoutWeb.VerifiedContractsController.index/2
        (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
        (block_scout_web 5.1.1) lib/block_scout_web/controllers/verified_contracts_controller.ex:26: BlockScoutWeb.VerifiedContractsController.index/2
        (block_scout_web 5.1.1) lib/block_scout_web/controllers/verified_contracts_controller.ex:1: BlockScoutWeb.VerifiedContractsController.action/2
        (block_scout_web 5.1.1) lib/block_scout_web/controllers/verified_contracts_controller.ex:1: BlockScoutWeb.VerifiedContractsController.phoenix_controller_pipeline/2
```

2023-03-10 11:05 UTC, sl1depengwyn commented
> /verified-contracts page doesn't open with the changes
> 
> ```
> Request: GET /verified-contracts?type=JSON
> ** (exit) an exception was raised:
>     ** (KeyError) key :market_cap not found in: %Explorer.Chain.Token{__meta__: #Ecto.Schema.Metadata<:loaded, "tokens">, name: "Seizon", symbol: "Seizon", total_supply: #Decimal<7573>, decimals: nil, type: "ERC-721", cataloged: true, holder_count: 3362, skip_metadata: nil, total_supply_updated_at_block: nil, fiat_value: nil, circulating_market_cap: nil, contract_address_hash: %Explorer.Chain.Hash{byte_count: 20, bytes: <<166, 205, 39, 40, 116, 238, 124, 135, 46, 182, 104, 1, 239, 246, 39, 132, 192, 177, 50, 133>>}, contract_address: #Ecto.Association.NotLoaded<association :contract_address is not loaded>, inserted_at: ~U[2023-03-06 23:59:07.423871Z], updated_at: ~U[2023-03-08 11:53:03.304706Z]}
>         (block_scout_web 5.1.1) lib/block_scout_web/templates/verified_contracts/_contract.html.eex:58: BlockScoutWeb.VerifiedContractsView."_contract.html"/1
>         (phoenix 1.5.13) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3
>         (phoenix 1.5.13) lib/phoenix/view.ex:479: Phoenix.View.render_to_string/3
>         (block_scout_web 5.1.1) lib/block_scout_web/controllers/verified_contracts_controller.ex:27: anonymous fn/2 in BlockScoutWeb.VerifiedContractsController.index/2
>         (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
>         (block_scout_web 5.1.1) lib/block_scout_web/controllers/verified_contracts_controller.ex:26: BlockScoutWeb.VerifiedContractsController.index/2
>         (block_scout_web 5.1.1) lib/block_scout_web/controllers/verified_contracts_controller.ex:1: BlockScoutWeb.VerifiedContractsController.action/2
>         (block_scout_web 5.1.1) lib/block_scout_web/controllers/verified_contracts_controller.ex:1: BlockScoutWeb.VerifiedContractsController.phoenix_controller_pipeline/2
> ```

Should be fixed in https://github.com/blockscout/blockscout/pull/6925/commits/adb5d7a23b7114e728628e04aad5c77b8605b980

2023-03-13 19:55 UTC, nikitosing commented on apps/block_scout_web/assets/js/pages/token/search.js
> +      if (state.channelDisconnected && !window.loading) $el.show()
Why `$el.show()` depends on `channelDisconnected`?

2023-03-14 20:07 UTC, nikitosing commented on config/runtime.exs
> -config :explorer, Explorer.KnownTokens, enabled: System.get_env("DISABLE_KNOWN_TOKENS") != "true", store: :ets
Let's delete this env also from `docker-compose/envs/common-blockscout.env` and `docker/Makefile`

2023-03-16 07:22 UTC, nikitosing commented on apps/explorer/lib/explorer/exchange_rates/source/coin_gecko.ex
> +    config(:currency) || "usd"
For now we haven't `:currency` in config. Is it for future improvements?

2023-03-16 07:39 UTC, nikitosing commented on apps/explorer/lib/explorer/chain.ex
> +          (t.type > ^type or
Why did you decide to remove ordering by value?

2023-03-16 10:03 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/exchange_rates/source/coin_gecko.ex
> +    config(:currency) || "usd"
Yes, it is

2023-03-16 14:20 UTC, sl1depengwyn commented on apps/block_scout_web/assets/js/pages/token/search.js
> +      if (state.channelDisconnected && !window.loading) $el.show()
Fixed in https://github.com/blockscout/blockscout/pull/6925/commits/f0144911ab944205c2ea9606ee3a1aaa8dcedd6e

2023-03-16 14:21 UTC, sl1depengwyn commented on config/runtime.exs
> -config :explorer, Explorer.KnownTokens, enabled: System.get_env("DISABLE_KNOWN_TOKENS") != "true", store: :ets
Fixed in https://github.com/blockscout/blockscout/pull/6925/commits/f0144911ab944205c2ea9606ee3a1aaa8dcedd6e

2023-03-16 14:21 UTC, sl1depengwyn commented on apps/block_scout_web/assets/js/pages/verified_contracts.js
> +      if (state.channelDisconnected && !window.loading) $el.show()
Fixed in https://github.com/blockscout/blockscout/pull/6925/commits/f0144911ab944205c2ea9606ee3a1aaa8dcedd6e

2023-03-20 18:45 UTC, vbaranov approved these changes

2023-03-20 18:56 UTC, nikitosing commented on apps/explorer/lib/explorer/chain.ex
> +    condition = dynamic([ctb, t], ^fiat_balance < ^fiat_value or is_nil(^fiat_balance))
Shouldn't we take into account case when some current token balances can have the same fiat value?

2023-03-21 18:08 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain.ex
> +    condition = dynamic([ctb, t], ^fiat_balance < ^fiat_value or is_nil(^fiat_balance))
Nice catch, fixed in https://github.com/blockscout/blockscout/pull/6925/commits/061f99232d1c0ef15f34f2385ec4eab70fde78cf#diff-3fce0f082a5cb927aa738ef8f7d582824df91d08957971d36a0873efacd88816

2023-03-22 11:02 UTC, nikitosing approved these changes

2023-03-22 11:30 UTC, merged