Bedrock optimism deposits
blockscout/blockscout pull request #6993
Opened 2023-02-28 13:50 UTC by sl1depengwyn

2023-03-01 11:28 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/logs_controller.ex
> +         {:format, {:ok, validated_params}} <- to_valid_format(fetched_params) |> IO.inspect(label: "validated_params"),
Let's remove debug prints

2023-03-09 11:25 UTC, varasev commented on apps/block_scout_web/lib/block_scout_web/api_router.ex
> +      get("/deposits", V2.OptimismController, :deposits)
Let's move this line one line higher just to follow the order of Optimism modules: `TxnBatches`, `OutputRoots`, `Deposits`, `Withdrawals`

2023-03-09 11:28 UTC, varasev commented on apps/explorer/lib/explorer/chain.ex
> +  Lists `t:Explorer.Chain.OptimismDeposits.t/0`'s' in descending order based on l1_block_number and l2_transaction_hash.
Did you mean `OptimismDeposit` here?

2023-03-09 11:29 UTC, varasev commented on apps/explorer/lib/explorer/chain.ex
> +  @spec list_deposits([paging_options]) :: [OptimismDeposits.t()]
Also, here (and one line above) must be `OptimismDeposit` instead of `OptimismDeposits`

2023-03-09 11:30 UTC, varasev commented on apps/explorer/lib/explorer/chain.ex
> +  def list_deposits(options \\ []) do
Maybe rename this function to `list_optimism_deposits` like it's done for `list_optimism_withdrawals`?

2023-03-09 11:31 UTC, varasev commented on apps/explorer/lib/explorer/chain.ex
> +        left_join: tx in assoc(d, :transaction),
Here must be `inner_join` because we shouldn't output a deposit on UI until we have the corresponding L2 transaction for it

2023-03-09 11:35 UTC, varasev commented on docker-compose/envs/common-blockscout.env
> +# INDEXER_OPTIMISM_L1_DEPOSITS_BATCH_SIZE=
We need to add a separate PR to https://github.com/blockscout/docs to add these envs to `for-developers/information-and-settings/env-variables.md` accordingly

2023-03-09 11:37 UTC, varasev commented on apps/explorer/lib/explorer/chain/import/runner/optimism_deposit.ex
> +    ordered_changes_list = Enum.sort_by(changes_list, & &1.l2_transaction_hash)
We need to add a separate PR to https://github.com/blockscout/docs to add `l2_transaction_hash ` to `for-developers/information-and-settings/sharelock.md`

2023-03-09 11:38 UTC, varasev commented on apps/explorer/lib/explorer/chain/import/runner/optimism_deposit.ex
> +        :insert_optimism_deposits
Looks like here (and one line above) must be `:optimism_deposits` instead of `:insert_optimism_deposits`?

2023-03-09 11:39 UTC, varasev commented on apps/explorer/lib/explorer/chain/import/stage/block_referencing.ex
> +      Runner.OptimismDeposits
Let's move this line two lines higher just to follow the order of Optimism modules: `TxnBatches`, `OutputRoots`, `Deposits`, `Withdrawals`

2023-03-09 11:41 UTC, varasev commented on apps/explorer/lib/explorer/chain/optimism_deposit.ex
> +      order_by: [desc: d.l1_transaction_origin],
Here we should order by `l1_block_number`

2023-03-09 13:13 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism.ex
> +  def json_rpc_named_arguments(optimism_rpc_l1) do
The file `optimism.ex` in `va-bedrock-optimism` branch already contains this function. Did you rebase your branch onto `va-bedrock-optimism`?

2023-03-09 13:34 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +        {:noreply, %{state | start_block: to_block + 1}}
I think, here we need to use `send_after` because we should let the process some time to define `start_block` on this line and only after that invoke `:fetch` with the updated value

2023-03-09 13:43 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +    optimism_portal = Application.get_env(:indexer, :optimism_portal_l1)
In `va-bedrock-optimism` branch this env named as `optimism_l1_portal`, not `optimism_portal_l1`: https://github.com/blockscout/blockscout/blob/3575fec9ff9bdf4e8fefa0df678e340acef487bd/config/runtime.exs#L626

2023-03-09 13:51 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +        Logger.error("Invalid L2 Start Block value. Please, check the value and op_withdrawals table.")
Here must be `Invalid L1 Start Block value. Please, check the value and op_deposits table`

2023-03-09 13:54 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +        Logger.error("Cannot get safe block from Optimism RPC due to the error: #{inspect(error_data)}")
Here must be `Cannot get last L1 transaction from RPC by its hash or last safe block due to the RPC error:`

2023-03-09 14:01 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +      Process.send(self(), :fetch, [])
I think, here we need to use `send_after` because we should let the process some time to define the state and only after that invoke `:fetch` with the defined state

2023-03-09 14:09 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +        Logger.error("#{inspect(err)}")
Shouldn't we move this clause at the end of the current `else` block? I think, it will catch the first possible error and the below `:logs` and `:import` handlers will be skipped

2023-03-09 14:15 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +      Process.send(self(), :fetch, [])
The same `send_after` issue here. Let's use it instead of `send`

2023-03-10 10:48 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +    case Optimism.get_filter_changes(filter_id, json_rpc_named_arguments) do
I believe this is not a reliable way to follow logs from RPC node. What if the node restarts at some point? Then the `filter_id` got by `eth_newFilter` will become not actual and `eth_getFilterChanges` will stop working. I would use `eth_getLogs` instead, like it's done in `Indexer.Fetcher.OptimismOutputRoot` module, or call `eth_uninstallFilter` and recall `eth_newFilter` to get new filter_id when `eth_getFilterChanges` responds with an empty result for a long time or with `filter not found` error.

Example:

```
curl --data '{"method":"eth_getFilterChanges","params":["0x1"],"id":"0","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST some.rpc.address

{"jsonrpc":"2.0","id":"0","error":{"code":-32000,"message":"filter not found"}}
```

Also, I'm not sure `eth_newFilter` and `eth_getFilterChanges` requests work correctly on RPC node without WebSockets (e.g. some public-like RPC node).

I tried to test it on our Goerli ETH RPC node and it returns an empty result VS `eth_getLogs` which works fine for the same parameters.

Did you try to test your module?

2023-03-10 10:56 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +          {:ok, timestamp} = Optimism.get_block_timestamp_by_number(block_number, json_rpc_named_arguments)
This will work very slowly as it will send a separate RPC request for each block. We need to use a batch request like here: https://github.com/blockscout/blockscout/blob/3575fec9ff9bdf4e8fefa0df678e340acef487bd/apps/indexer/lib/indexer/fetcher/optimism_txn_batch.ex#L279-L286

2023-03-10 11:09 UTC, varasev requested changes
Please, view my comments, especially about the method of getting logs (events) and getting blocks timestamps by their numbers. I'm worried of using `eth_newFilter` and `eth_getFilterChanges` - not sure they will work in production.

2023-03-10 11:18 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/chain.ex
> +  defp paging_params(%OptimismDeposit{l1_block_number: l1_block_number, l2_transaction_hash: l2_tx_hash}) do
`paging_params` called from `next_page_params` which is called from https://github.com/blockscout/blockscout/blob/b8b9aa2f402b44af841fb1b46a69f202825d160b/apps/block_scout_web/lib/block_scout_web/controllers/api/v2/optimism_controller.ex#L85
so it passes to `paging_params` list of `OptimismDeposit` structeres

2023-03-10 13:35 UTC, varasev commented on apps/block_scout_web/lib/block_scout_web/chain.ex
> +  defp paging_params(%OptimismDeposit{l1_block_number: l1_block_number, l2_transaction_hash: l2_tx_hash}) do
Ah, you're right, I confused this with other code

2023-03-11 09:01 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +        {:noreply, %{state | start_block: to_block + 1}}
`handle_info` works synchronously, i.e. it will not start processing the next call until the processing of the previous one is completed, so `send_after` here is redundant

2023-03-11 09:07 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/api_router.ex
> +      get("/deposits", V2.OptimismController, :deposits)
Fixed in https://github.com/blockscout/blockscout/pull/6993/commits/eff5c78034e8f89de3ac1110c277cb74d2c04607

2023-03-11 09:08 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain.ex
> +  Lists `t:Explorer.Chain.OptimismDeposits.t/0`'s' in descending order based on l1_block_number and l2_transaction_hash.
Fixed in https://github.com/blockscout/blockscout/pull/6993/commits/eff5c78034e8f89de3ac1110c277cb74d2c04607

2023-03-11 09:09 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain.ex
> +  @spec list_deposits([paging_options]) :: [OptimismDeposits.t()]
Fixed in https://github.com/blockscout/blockscout/pull/6993/commits/eff5c78034e8f89de3ac1110c277cb74d2c04607

2023-03-11 09:09 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain.ex
> +  def list_deposits(options \\ []) do
Renamed in https://github.com/blockscout/blockscout/pull/6993/commits/eff5c78034e8f89de3ac1110c277cb74d2c04607

2023-03-11 09:10 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain.ex
> +        left_join: tx in assoc(d, :transaction),
Nice catch, it left after tests
Fixed in https://github.com/blockscout/blockscout/pull/6993/commits/eff5c78034e8f89de3ac1110c277cb74d2c04607

2023-03-11 09:11 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/optimism_controller.ex
> +    total = Chain.optimism_deposits_total_count()
Fixed in https://github.com/blockscout/blockscout/pull/6993/commits/eff5c78034e8f89de3ac1110c277cb74d2c04607

2023-03-11 09:11 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/import/runner/optimism_deposit.ex
> +        :insert_optimism_deposits
Fixed in https://github.com/blockscout/blockscout/pull/6993/commits/eff5c78034e8f89de3ac1110c277cb74d2c04607

2023-03-11 09:11 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/import/stage/block_referencing.ex
> +      Runner.OptimismDeposits
Fixed in https://github.com/blockscout/blockscout/pull/6993/commits/eff5c78034e8f89de3ac1110c277cb74d2c04607

2023-03-11 09:11 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/optimism_deposit.ex
> +      order_by: [desc: d.l1_transaction_origin],
Fixed in https://github.com/blockscout/blockscout/pull/6993/commits/eff5c78034e8f89de3ac1110c277cb74d2c04607

2023-03-11 09:12 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/optimism.ex
> +  def json_rpc_named_arguments(optimism_rpc_l1) do
Fixed in https://github.com/blockscout/blockscout/pull/6993/commits/eff5c78034e8f89de3ac1110c277cb74d2c04607

2023-03-11 09:12 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +    optimism_portal = Application.get_env(:indexer, :optimism_portal_l1)
Fixed in https://github.com/blockscout/blockscout/pull/6993/commits/eff5c78034e8f89de3ac1110c277cb74d2c04607

2023-03-11 09:13 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +    optimism_rpc_l1 = Application.get_env(:indexer, :optimism_rpc_l1)
Fixed in https://github.com/blockscout/blockscout/pull/6993/commits/eff5c78034e8f89de3ac1110c277cb74d2c04607

2023-03-11 09:14 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +        Logger.error("Invalid L2 Start Block value. Please, check the value and op_withdrawals table.")
Fixed in https://github.com/blockscout/blockscout/pull/6993/commits/eff5c78034e8f89de3ac1110c277cb74d2c04607

2023-03-11 09:14 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +        Logger.error("Cannot get safe block from Optimism RPC due to the error: #{inspect(error_data)}")
Fixed in https://github.com/blockscout/blockscout/pull/6993/commits/eff5c78034e8f89de3ac1110c277cb74d2c04607

2023-03-11 09:14 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +        Logger.error("#{inspect(err)}")
It was for debug purposes
Fixed in https://github.com/blockscout/blockscout/pull/6993/commits/eff5c78034e8f89de3ac1110c277cb74d2c04607

2023-03-11 09:16 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +          {:ok, timestamp} = Optimism.get_block_timestamp_by_number(block_number, json_rpc_named_arguments)
Thanks for suggestion, it will speed up things significantly
Fixed in https://github.com/blockscout/blockscout/pull/6993/commits/eff5c78034e8f89de3ac1110c277cb74d2c04607

2023-03-11 10:09 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +    case Optimism.get_filter_changes(filter_id, json_rpc_named_arguments) do
Nice catch about node restart, fixed in https://github.com/blockscout/blockscout/pull/6993/commits/eff5c78034e8f89de3ac1110c277cb74d2c04607 but without `eth_uninstallFilter` I think we do not need to uninstall the filter if it is not found.

But about correctness I see no reason to doubt `eth_getFilterChanges` method, it returns empty result on first call, because it shows _changes_ so first call is for comparison with next one I suppose, but it's fine for us as we use this method in real time mode only

When I tested this module everything worked as expected

2023-03-11 10:36 UTC, sl1depengwyn commented on docker-compose/envs/common-blockscout.env
> +# INDEXER_OPTIMISM_L1_DEPOSITS_BATCH_SIZE=
Here it is https://github.com/blockscout/docs/pull/124
Also, I suggest to move all L2 related envs to a separate table (created in the PR above)

2023-03-13 11:02 UTC, varasev commented on docker-compose/envs/common-blockscout.env
> +# INDEXER_OPTIMISM_L1_DEPOSITS_BATCH_SIZE=
Ok, I've done the same in my PR in https://github.com/blockscout/docs/pull/122/commits/86a68eb0b17895e1a1a117eed70f0b78bbbee4b9

2023-03-13 11:04 UTC, varasev commented on docker-compose/envs/common-blockscout.env
> +# INDEXER_OPTIMISM_L1_DEPOSITS_BATCH_SIZE=
Please, also rename `INDEXER_OPTIMISM_L1_DEPOSITS_START_BLOCK_L1` to `INDEXER_OPTIMISM_L1_DEPOSITS_START_BLOCK` here

2023-03-13 11:21 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +        {:noreply, %{state | start_block: to_block + 1}}
Makes sense

2023-03-13 12:28 UTC, varasev commented
Please, add logging to the module to see the indexing progress. Example: https://github.com/blockscout/blockscout/blob/70e23d7fd56f225a5296e8cd5ea5a143166693b7/apps/indexer/lib/indexer/fetcher/optimism.ex#L244

2023-03-13 12:38 UTC, varasev commented
Also, please add `gas_limit` field to API's output: it should be taken from the `gas` field of `transactions` table.

2023-03-13 12:51 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +      check_interval = ceil((safe_block_timestamp - prev_safe_block_timestamp) * 1000 / 2)
It's not reliable to define average block time between two neighbour blocks as the block delay is not a constant for many chains. I'd suggest to use some wider range of blocks to get avg block time (e.g., 100 blocks).

2023-03-13 18:19 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +      check_interval = ceil((safe_block_timestamp - prev_safe_block_timestamp) * 1000 / 2)
Done in https://github.com/blockscout/blockscout/pull/6993/commits/6f110609696753e7803a872ae8ca36991a501f22

2023-03-14 10:16 UTC, varasev commented on docker-compose/envs/common-blockscout.env
> +# INDEXER_OPTIMISM_L1_DEPOSITS_BATCH_SIZE=
@sl1depengwyn Please, rename `INDEXER_OPTIMISM_L1_DEPOSITS_START_BLOCK_L1` to `INDEXER_OPTIMISM_L1_DEPOSITS_START_BLOCK` here

2023-03-14 10:28 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +        Optimism.log_blocks_chunk_handling(from_block, to_block, start_block, safe_block, nil, "L1")
We need to pass the items count here to let `log_blocks_chunk_handling` display progress percentage. See https://github.com/blockscout/blockscout/blob/6f110609696753e7803a872ae8ca36991a501f22/apps/indexer/lib/indexer/fetcher/optimism_output_root.ex#L74-L101 for example: we call it when the chunk handling starts and then call it again when the handling finishes.

2023-03-14 10:31 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +        Optimism.log_blocks_chunk_handling(from_block, to_block, start_block, safe_block, nil, "L1")
Note that when we call it second time, we pass `items_count` parameter to it: https://github.com/blockscout/blockscout/blob/6f110609696753e7803a872ae8ca36991a501f22/apps/indexer/lib/indexer/fetcher/optimism_output_root.ex#L99

In this case the `items_count` must be `"#{Enum.count(deposits)} TransactionDeposited event(s)"`.

2023-03-14 10:38 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +      if to_block |> Kernel.-(start_block) |> Kernel./(batch_size + 1) |> trunc() |> rem(10) == 0 do
Let's remove this condition. It confuses me when I analyze logs:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/33550681/224975028-87ca4416-41bc-4106-98e5-4d9bdcb49502.png">

I see very big gaps between neighbour chunks

2023-03-14 10:41 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +      if to_block |> Kernel.-(start_block) |> Kernel./(batch_size + 1) |> trunc() |> rem(10) == 0 do
Also, I don't see realtime logs. They should be displayed to tell us that realtime handling is working at the moment

2023-03-14 10:44 UTC, varasev commented
@sl1depengwyn Please, don't check an item as resolved until I review the change and resolve it myself. Otherwise, it's hard for a reviewer to find the items needed to be reviewed again

2023-03-14 10:45 UTC, varasev commented
HTTP get request `/api/v2/optimism/deposits` throws and error:

```
2023-03-14T13:45:05.121 [error] #PID<0.4543.0> running BlockScoutWeb.Endpoint (connection #PID<0.4542.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /api/v2/optimism/deposits
** (exit) an exception was raised:
    ** (KeyError) key :gas not found in: #Ecto.Association.NotLoaded<association :transaction is not loaded>
        (block_scout_web 5.1.1) lib/block_scout_web/views/api/v2/optimism_view.ex:72: anonymous fn/1 in BlockScoutWeb.API.V2.OptimismView.render/2
        (elixir 1.14.1) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
        (block_scout_web 5.1.1) lib/block_scout_web/views/api/v2/optimism_view.ex:65: BlockScoutWeb.API.V2.OptimismView.render/2
        (phoenix 1.5.13) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3
        (phoenix 1.5.13) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4
        (block_scout_web 5.1.1) lib/block_scout_web/controllers/api/v2/optimism_controller.ex:1: BlockScoutWeb.API.V2.OptimismController.action/2
        (block_scout_web 5.1.1) lib/block_scout_web/controllers/api/v2/optimism_controller.ex:1: BlockScoutWeb.API.V2.OptimismController.phoenix_controller_pipeline/2
        (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
```

2023-03-14 10:49 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +      if to_block |> Kernel.-(start_block) |> Kernel./(batch_size + 1) |> trunc() |> rem(10) == 0 do
Won't it flood logs too much? Imagine fetching millions of blocks and spams thousands of such messages to the log, I thought the purpose of these message is to track the progress of catch up fetcher. Also, about realtime logging, I also see no reason to log every action as it will also take a lot of space in logs, I think absence of error log message mean that the fetcher is okay

2023-03-14 11:08 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +      if to_block |> Kernel.-(start_block) |> Kernel./(batch_size + 1) |> trunc() |> rem(10) == 0 do
> Won't it flood logs too much?

This is not a problem since the logs are rotated. Also, there will only be a lot of logs at the time of catchup fetching that is temporary (until real time mode is reached).

> I thought the purpose of these message is to track the progress of catch up fetcher.

The purpose is to track the progress and to diagnose continuous handling of blocks.

> Also, about realtime logging, I also see no reason to log every action as it will also take a lot of space in logs

In realtime mode we need to see that every new block is handled.

> I think absence of error log message mean that the fetcher is okay.

That's not always truth as there can be a case when we forgot to enable the fetcher.

2023-03-15 05:38 UTC, sl1depengwyn commented
> HTTP GET request `/api/v2/optimism/deposits` throws the following error:
> 
> ```
> 2023-03-14T13:45:05.121 [error] #PID<0.4543.0> running BlockScoutWeb.Endpoint (connection #PID<0.4542.0>, stream id 1) terminated
> Server: localhost:4000 (http)
> Request: GET /api/v2/optimism/deposits
> ** (exit) an exception was raised:
>     ** (KeyError) key :gas not found in: #Ecto.Association.NotLoaded<association :transaction is not loaded>
>         (block_scout_web 5.1.1) lib/block_scout_web/views/api/v2/optimism_view.ex:72: anonymous fn/1 in BlockScoutWeb.API.V2.OptimismView.render/2
>         (elixir 1.14.1) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
>         (block_scout_web 5.1.1) lib/block_scout_web/views/api/v2/optimism_view.ex:65: BlockScoutWeb.API.V2.OptimismView.render/2
>         (phoenix 1.5.13) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3
>         (phoenix 1.5.13) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4
>         (block_scout_web 5.1.1) lib/block_scout_web/controllers/api/v2/optimism_controller.ex:1: BlockScoutWeb.API.V2.OptimismController.action/2
>         (block_scout_web 5.1.1) lib/block_scout_web/controllers/api/v2/optimism_controller.ex:1: BlockScoutWeb.API.V2.OptimismController.phoenix_controller_pipeline/2
>         (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
> ```

I cant reproduce this error, could you please recheck that the branch is up to date on your side? This error seems impossible to happen since we have `join` (equal to `inner_join` for ecto)  so all deposits must be with associated transaction

2023-03-15 05:44 UTC, sl1depengwyn commented on docker-compose/envs/common-blockscout.env
> +# INDEXER_OPTIMISM_L1_DEPOSITS_BATCH_SIZE=
Fixed in https://github.com/blockscout/blockscout/pull/6993/commits/4ba844aabf61ac1f60c4b500edc44de9fe29af74 thank you

2023-03-15 05:46 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +        Optimism.log_blocks_chunk_handling(from_block, to_block, start_block, safe_block, nil, "L1")
Done in https://github.com/blockscout/blockscout/pull/6993/commits/4ba844aabf61ac1f60c4b500edc44de9fe29af74

2023-03-15 05:46 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +      if to_block |> Kernel.-(start_block) |> Kernel./(batch_size + 1) |> trunc() |> rem(10) == 0 do
Done in https://github.com/blockscout/blockscout/pull/6993/commits/4ba844aabf61ac1f60c4b500edc44de9fe29af74

2023-03-15 05:46 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +            "Failed to get L1 block timestamps for deposits due to #{inspect(error)}. Timestamps will be set to now."
Done in https://github.com/blockscout/blockscout/pull/6993/commits/4ba844aabf61ac1f60c4b500edc44de9fe29af74

2023-03-15 11:55 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +         {:catch_up, _, false} <- {:catch_up, new_safe, new_safe - safe_block + 1 > batch_size},
Can you please clarify this moment? Why do we need to request the `safe` block again if it moved far ahead? At such moment we already have handled the range `start_block..safe_block` by the `:fetch` handler, so I guess it's enough to continue working with `safe_block+1 .. latest` range (as you are doing below).

2023-03-15 12:01 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +              to_block,
Please note that there can be a case when `from_block > to_block`. This can happen if we just switched to realtime mode and after that restarted Blockscout instance.

In such a case we need to ignore `eth_getLogs` request as it will return an empty result anyway (but some RPC nodes can swap from_block and to_block).

2023-03-15 12:13 UTC, varasev commented
Let's add logging to `handle_new_logs` when `logs_to_parse` list is not empty. I'd do that as follows:

```
Optimism.log_blocks_chunk_handling(start_block, end_block, start_block, end_block, "#{Enum.count(logs_to_parse)} TransactionDeposited event(s)", "L1")
```

Here `start_block` is the min number of block found in `blockNumber` field of the RPC response, `end_block` is the max number of block found in `blockNumber` field of the RPC response.

2023-03-15 12:23 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +      {deleted_count, _} = Repo.delete_all(from(d in OptimismDeposit, where: d.l1_block_number in ^reorgs))
Let's add

```elixir
Logger.warning("L1 reorg detected. The following L1 blocks were removed: #{inspect(MapSet.to_list(reorgs))}")
```

in `handle_reorgs` after `if MapSet.size(reorgs) > 0 do` but before `Repo.delete_all`.

2023-03-15 17:33 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +         {:catch_up, _, false} <- {:catch_up, new_safe, new_safe - safe_block + 1 > batch_size},
While being in catchup mode there could appear a lot of blocks on the chain such that `safe_block+1 .. latest` request will be too large to handle
So I check if `old_safe..new_safe` is less than batch size (here I assume that range between latest and safe block is okay to be over batch), and if this range is too large I fetch it by chunks in catch up mode

2023-03-15 17:36 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +              to_block,
In this case we will fetch from logs in range `safe..safe` and then switch to realtime mode, won't we?

2023-03-16 08:31 UTC, sl1depengwyn commented
> Let's add logging to `handle_new_logs` when `logs_to_parse` list is not empty. I would do that as follows:
> 
> ```elixir
> Optimism.log_blocks_chunk_handling(start_block, end_block, start_block, end_block, "#{Enum.count(logs_to_parse)} TransactionDeposited event(s)", "L1")
> ```
> 
> Here `start_block` is the min number of block found in `blockNumber` field of the RPC response, `end_block` is the max number of block found in `blockNumber` field of the RPC response.

Could you please clarify why we need one more message for the same action, we already have messages like this:
```
2023-03-16T11:24:36.867 application=indexer fetcher=optimism_deposits [info] Finish handling L1 block range 8552936..8553436. Found 111 TransactionDeposited event(s). Target range: 8381594..8663789. Progress: 60.89%
```
here we see how many events are in the range

2023-03-16 09:20 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +      {deleted_count, _} = Repo.delete_all(from(d in OptimismDeposit, where: d.l1_block_number in ^reorgs))
Added here https://github.com/blockscout/blockscout/pull/6993/commits/45e24fc737c24bb2881d29fc0c978d8722e41bd8

2023-03-16 11:13 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +         {:catch_up, _, false} <- {:catch_up, new_safe, new_safe - safe_block + 1 > batch_size},
Got it

2023-03-16 11:21 UTC, varasev commented
> > Let's add logging to `handle_new_logs` when `logs_to_parse` list is not empty. I would do that as follows:
> > ```elixir
> > Optimism.log_blocks_chunk_handling(start_block, end_block, start_block, end_block, "#{Enum.count(logs_to_parse)} TransactionDeposited event(s)", "L1")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here `start_block` is the min number of block found in `blockNumber` field of the RPC response, `end_block` is the max number of block found in `blockNumber` field of the RPC response.
> 
> Could you please clarify why we need one more message for the same action, we already have messages like this:
> 
> ```
> 2023-03-16T11:24:36.867 application=indexer fetcher=optimism_deposits [info] Finish handling L1 block range 8552936..8553436. Found 111 TransactionDeposited event(s). Target range: 8381594..8663789. Progress: 60.89%
> ```
> 
> here we see how many events are in the range

This is for realtime mode logging. We still don't have logs for realtime

2023-03-16 11:27 UTC, varasev reviewed
There are two things left to do before merging:

1. https://github.com/blockscout/blockscout/pull/6993#discussion_r1136943444

2. https://github.com/blockscout/blockscout/pull/6993#issuecomment-1469895945

2023-03-16 12:15 UTC, sl1depengwyn commented
> There are two things left to do before merging:
> 
> 1. [#6993 (comment)](https://github.com/blockscout/blockscout/pull/6993#discussion_r1136943444)
> 2. [#6993 (comment)](https://github.com/blockscout/blockscout/pull/6993#issuecomment-1469895945)

Done here https://github.com/blockscout/blockscout/pull/6993/commits/13927107374910815371e07f8f5920d7f57fa4c3

About case when `from_block` > `to_block`:
I decided to check it in init function and switch to realtime immediately if it is the case

2023-03-16 13:36 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +      |> Enum.reduce({MapSet.new(), [], nil, 0, 0}, fn
Is it OK to have `nil` for `min_block` initially? Maybe there should be `0`?

2023-03-16 14:01 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +              max(safe_block, from_block) + 1,
I guess here should be `max(safe_block, from_block)` without `+1` because we need to re-handle the block `last_l1_block_number` at the start of the module as there can be a case when not all logs were handled at previous run (e.g. Blockscout was turned off unexpectedly). In this case it's ok if we re-include `safe_block` or `from_block` to the `eth_getLogs` range - already existing logs will be rewritten in db for that block.

2023-03-16 14:02 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +             safe_block + 1,
Shouldn't here be `max(safe_block, from_block)` like for `Optimism.get_logs` above?

2023-03-16 14:15 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +             safe_block + 1,
You are right, fixed in https://github.com/blockscout/blockscout/pull/6993/commits/75c2f2bf1c028bd57a6e76b725e92390275449ed

2023-03-16 14:15 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/optimism_deposit.ex
> +              max(safe_block, from_block) + 1,
Nice catch, https://github.com/blockscout/blockscout/pull/6993/commits/75c2f2bf1c028bd57a6e76b725e92390275449ed

2023-03-16 15:35 UTC, varasev approved these changes

2023-03-16 15:36 UTC, merged