split token instance fetcher
blockscout/blockscout pull request #7286
Opened 2023-04-14 18:32 UTC by nikitosing

Close #7024 

## Changelog

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2023-04-19 09:56 UTC, vbaranov reviewed
I would suggest changing the folders structure and naming of new fetcher's for consistency and reading convenience purposes. Here is the suggestion how to rename new fetchers:

Indexer.Fetcher.Realtime.TokenInstance -> Indexer.Fetcher.TokenInstance.Realtime
Indexer.Fetcher.Retry.TokenInstance -> Indexer.Fetcher.TokenInstance.Retry
Indexer.Fetcher.Sanitize.TokenInstance -> Indexer.Fetcher.TokenInstance.Sanitize
Indexer.Fetcher.TokenInstance -> Indexer.Fetcher.TokenInstance.Helper

And the folder structure like this:
apps/indexer/lib/indexer/fetcher/token_instance:
           - realtime.ex
           - retry.ex
           - sanitize.ex
           - helper.ex

2023-04-19 09:58 UTC, vbaranov commented on apps/explorer/lib/explorer/token/instance_metadata_retriever.ex
> +  @max_error_length 100
What is the rationale for 100? In the DB we have `character varying(255)` type for `error` column in `token_instances` table.

2023-04-20 13:47 UTC, vbaranov commented on apps/indexer/lib/indexer/block/fetcher.ex
> +    TokenInstance.Realtime,
I would suggest to make an alias for this fetcher for the sake of search improvement capabilities:
```
alias Indexer.Fetcher.TokenInstance.Realtime, as: TokenInstanceRealtime
```

2023-04-20 13:47 UTC, vbaranov commented on apps/indexer/lib/indexer/fetcher/token_instance/helper.ex
> +  def fetch_instance(token_contract_address_hash, token_id, is_retry?) do
Let's add spec for this function?

2023-04-20 13:47 UTC, vbaranov commented on apps/indexer/lib/indexer/supervisor.ex
> +    TokenInstance.Sanitize,
I would suggest to make an alias for these fetchers for the sake of search improvement capabilities:
```
alias Indexer.Fetcher.TokenInstance.Realtime, as: TokenInstanceRealtime
alias Indexer.Fetcher.TokenInstance.Retry, as: TokenInstance Retry
alias Indexer.Fetcher.TokenInstance.Sanitize, as: TokenInstanceSanitize
```

2023-04-21 12:01 UTC, sl1depengwyn requested changes

2023-04-21 12:01 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/token_instance/retry.ex
> +    end
Same here

2023-04-21 12:01 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/token_instance/realtime.ex
> +    {0, []}
Same in this module

2023-04-21 12:01 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/supervisor.ex
> +        {TokenInstanceSanitize.Supervisor,
Likewise we don't need to provide `json_rpc_named_arguments` here

2023-04-22 07:18 UTC, nikitosing commented on apps/indexer/lib/indexer/fetcher/token_instance/sanitize.ex
> +    end
Good point. Fixed!

2023-04-22 07:18 UTC, nikitosing commented on apps/indexer/lib/indexer/fetcher/token_instance/retry.ex
> +    end
Fixed!

2023-04-22 07:18 UTC, nikitosing commented on apps/indexer/lib/indexer/fetcher/token_instance/realtime.ex
> +    {0, []}
Fixed!

2023-04-22 07:19 UTC, nikitosing commented on apps/indexer/lib/indexer/supervisor.ex
> +        {TokenInstanceSanitize.Supervisor,
Fixed!

2023-04-23 11:12 UTC, sl1depengwyn approved these changes

2023-04-24 09:06 UTC, vbaranov approved these changes

2023-04-24 09:07 UTC, merged