Add ability to disable reCAPTCHA
blockscout/blockscout pull request #7416
Opened 2023-05-05 08:24 UTC by bretep

*[GitHub keywords to close any associated issues](https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/)*

## Motivation

The enterprise version of reCAPTCHA wasn't working, and we don't need reCAPTCHA. Giving the operator the decision to enable/disable the feature is nice.

## Changelog

### Enhancements
Ability to disable reCAPTCHA

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2023-05-05 08:41 UTC, bretep commented
This commit is currently running on PulseChain Testnet v4

You can test it out here:
https://scan.v4.testnet.pulsechain.com/csv-export?address=0xCe2400835B94d41D5b43Fb5fe729581Df84cF586&type=transactions

2023-05-05 09:08 UTC, sl1depengwyn requested changes

2023-05-05 09:08 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
> +  end
You need to place this clause below clause at https://github.com/blockscout/blockscout/blob/d176aebf821d694dab8fa4e094b7a2e672888454/apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex#L219 as this one will always match so we will never check recaptcha_response

2023-05-05 09:08 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
> +  end
Here I think we can replace two clauses with this one actually
```suggestion
  def transactions_csv(conn, params) do
    items_csv(conn, params, AddressTransactionCsvExporter)
  end
```

2023-05-05 09:12 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
> +        not_found(conn)
Also, we need to change it like this, for instance, to match https://github.com/blockscout/blockscout/blob/d176aebf821d694dab8fa4e094b7a2e672888454/apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex#L195
```suggestion
      false ->
        not_found(conn)
```

2023-05-06 18:49 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
> +
The clause below now is not used, we need to remove it
Everything else looks good to me

2023-05-07 11:25 UTC, sl1depengwyn approved these changes

2023-05-08 08:26 UTC, vbaranov approved these changes

2023-05-08 08:27 UTC, merged