Add endpoint url to the block_scout_web logging
blockscout/blockscout pull request #8609
Opened 2023-10-09 18:58 UTC by nikitosing

Close #8615 
## Motivation
No endpoint info in logging message containing response duration
`2023-10-09T21:38:02.974 application=block_scout_web request_id=F4yEWklLjbCjCagAACji [info] Sent 200 in 48ms`
## Changelog
- Now for each request emits only one log entry, it includes processing time and endpoint url:
`2023-10-23T15:16:34.785 application=block_scout_web request_id=F5C7qShBskH0kHIAAJYj [info] Sent 200 in 64ms on /chain-blocks?`
- For `MIX_ENV=prod` emit logs in json format:
`{"time":"2023-10-11T16:43:55.609Z","severity":"info","message":"Sent 200 in 50ms on /recent-transactions?","metadata":{"duration":50013,"endpoint":"/recent-transactions?","request_id":"F40RdpLpMjayAZsAABsB","status":"200","unit":"microsecond"}}`
- Disable debug ecto logs for `MIX_ENV=test`

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2023-10-24 09:53 UTC, sl1depengwyn requested changes

2023-10-24 09:53 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/plug/logger.ex
> -        [conn.method, ?\s, conn.request_path]
It seems that now we do not log request method, I think we need to keep this behaviour

2023-10-24 12:03 UTC, sl1depengwyn approved these changes

2023-11-09 08:09 UTC, vbaranov approved these changes

2023-11-09 08:09 UTC, merged