Implement sorting of smart contracts, address transactions
blockscout/blockscout pull request #8611
Opened 2023-10-10 11:47 UTC by sl1depengwyn

Part of #7794 

## Motivation

## Changelog

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2023-10-27 15:36 UTC, vbaranov reviewed
Rebase is required.

2023-10-27 15:36 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/transaction.ex
> +  # import Ecto.Query, only: [from: 2, preload: 3, subquery: 1, where: 3]
Do we need this comment?

2023-10-27 15:36 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/block/reward.ex
> +  @spec address_has_rewards?(Address.t()) :: boolean()
Could you please doc as well?

2023-10-27 15:36 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/transaction.ex
> +    # |> Enum.sort(&{&1.block_number, &1.index}, &>=/2)
Do we need this commented line?

2023-10-27 15:36 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/transaction.ex
Could you please add spec/doc for all new public functions?

2023-11-07 12:33 UTC, nikitosing requested changes

2023-11-09 14:53 UTC, vbaranov approved these changes

2023-11-11 18:54 UTC, nikitosing requested changes

2023-11-11 18:54 UTC, nikitosing commented on apps/explorer/lib/explorer/sorting_helper.ex
> +        apply_next_column(next_column, key)
Why did you skip here `is_nil` check?

2023-11-11 18:56 UTC, nikitosing commented on apps/explorer/lib/explorer/sorting_helper.ex
> +  defp apply_as(sorting, query) do
Mb rename it to `apply_sorting_inner` or `apply_sorting_to_query`?

2023-11-12 23:47 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/sorting_helper.ex
> +        apply_next_column(next_column, key)
Great catch! I decided to implement a solution to keep only one copy of this function, basically these clauses now defined in for comprehension

2023-12-04 15:24 UTC, nikitosing approved these changes

2023-12-04 19:49 UTC, merged