API v2: address nft
blockscout/blockscout pull request #8634
Opened 2023-10-16 13:52 UTC by nikitosing

Close #8231 

## Changelog
- Add filter to `/api/v2/tokens/{address_hash}/instances?holder_address_hash={holder_address}`
- Add `/api/v2/addresses/{address_hash}/nft` and `/api/v2/{address_hash}/nft/collections`

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2023-10-24 14:46 UTC, sl1depengwyn requested changes

2023-10-24 14:46 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/address/current_token_balance.ex
> +    field(:preloaded_token_instances, {:array, :any}, virtual: true)
Please, upate the type spec

2023-10-24 14:46 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/token/instance.ex
> +    field(:current_token_balance, :any, virtual: true)
Please, update the type spec

2023-11-09 07:34 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex
> +         {:not_found, {:ok, token}} <- {:not_found, Chain.token_from_address_hash(address_hash, @api_true)},
I think it's better to factor out such refactoring to a separate PR, in order to not to overload PR

2023-11-09 07:43 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex
> +         {:format, {:ok, holder_address_hash}} <- {:format, Chain.string_to_address_hash(holder_address_hash)} do
Nice catch! Fixed

2023-11-09 13:34 UTC, sl1depengwyn approved these changes

2023-11-09 18:36 UTC, vbaranov approved these changes

2023-11-09 18:37 UTC, merged