Add stability_fee for CHAIN_TYPE=stability
blockscout/blockscout pull request #8651
Opened 2023-10-18 13:30 UTC by nikitosing

Close #8650 

## Changelog
- add `stability_fee` field to tx response:
```
"stability_fee": {
        "dapp_address": {
          "hash": "0xafa081C766383bAbdAC47AE46394423541606561",
          "implementation_name": null,
          "is_contract": false,
          "is_verified": null,
          "name": null,
          "private_tags": [],
          "public_tags": [],
          "watchlist_names": []
        },
        "dapp_fee": "0",
        "token": {
          "address": "0xDc2B93f3291030F3F7a6D9363ac37757f7AD5C43",
          "circulating_market_cap": null,
          "decimals": "18",
          "exchange_rate": null,
          "holders": "10",
          "icon_url": null,
          "name": "Stability Gas",
          "symbol": "GAS",
          "total_supply": "10000000000000000000000000",
          "type": "ERC-20"
        },
        "total_fee": "0",
        "validator_address": {
          "hash": "0x59024dD6932bbbBCEAb416873874d733D5B3A84C",
          "implementation_name": null,
          "is_contract": false,
          "is_verified": null,
          "name": null,
          "private_tags": [],
          "public_tags": [],
          "watchlist_names": []
        },
        "validator_fee": "0"
      }
```
## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2023-10-24 10:25 UTC, sl1depengwyn requested changes

2023-10-24 10:25 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex
>  end
I suggest to put this logic (except `maybe_put_stability_fee`) somewhere to Explorer app, maybe Transaction module

2023-10-24 10:25 UTC, sl1depengwyn commented on apps/block_scout_web/test/block_scout_web/controllers/api/v2/transaction_controller_test.exs
> +  describe "stability fees" do
I think we can factor out env substitution to setup and put it under describe

2023-10-24 13:41 UTC, nikitosing commented on apps/block_scout_web/test/block_scout_web/controllers/api/v2/transaction_controller_test.exs
> +  describe "stability fees" do
No, the main point why all the env substitutions are not factored out is that we need to keep old env value and return it back after test execution

2023-10-25 13:02 UTC, sl1depengwyn approved these changes

2023-10-26 09:33 UTC, vbaranov approved these changes

2023-10-26 09:33 UTC, merged