Add OP withdrawal status to transaction page in API
blockscout/blockscout pull request #8702
Opened 2023-10-25 11:13 UTC by varasev

Closes https://github.com/blockscout/blockscout/issues/8598.

## Motivation

We need to display Withdrawal status on transaction page.

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [x] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [x] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [x] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2023-10-25 11:55 UTC, vbaranov approved these changes

2023-10-25 13:10 UTC, sl1depengwyn requested changes

2023-10-25 13:10 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/views/api/v2/optimism_view.ex
> +  end
Let's move such logic in `Explorer` application, and try to keep only web related code in `BlockScoutWeb` application

2023-10-26 07:59 UTC, varasev commented on apps/block_scout_web/lib/block_scout_web/views/api/v2/optimism_view.ex
> +  end
Done in https://github.com/blockscout/blockscout/pull/8702/commits/ca60783f7595bc28e7753d233baafcd38902eecd. I moved that to `Explorer.Chain` yet, but in the future those functions will be moved to a separate file in the scope of https://github.com/blockscout/blockscout/issues/8704

2023-10-26 11:21 UTC, sl1depengwyn approved these changes

2023-10-27 15:18 UTC, vbaranov commented on apps/explorer/lib/explorer/chain.ex
> +  @doc """
@varasev let's move new functions to another module from Chain (since we agreed with plan do disband it).

2023-10-27 15:40 UTC, merged