Smart-contract proxy detection refactoring
blockscout/blockscout pull request #8807
Opened 2023-11-10 15:45 UTC by vbaranov

https://github.com/blockscout/blockscout/issues/8758

## Motivation

*Why we should merge these changes.  If using GitHub keywords to close [issues](https://github.com/poanetwork/blockscout/issues), this is optional as the motivation can be read on the issue page.*

## Changelog

### Enhancements
*Things you added that don't break anything.  Regression tests for Bug Fixes count as Enhancements.*

### Bug Fixes
*Things you changed that fix bugs.  If a fixes a bug, but in so doing adds a new requirement, removes code, or requires a database reset and reindex, the breaking part of the change should be added to Incompatible Changes below also.*

### Incompatible Changes
*Things you broke while doing Enhancements and Bug Fixes.  Breaking changes include (1) adding new requirements and (2) removing code.  Renaming counts as (2) because a rename is a removal followed by an add.*

## Upgrading

*If you have any Incompatible Changes in the above Changelog, outline how users of prior versions can upgrade once this PR lands or when reviewers are testing locally.  A common upgrading step is "Database reset and re-index required".*

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2023-11-13 21:20 UTC, sl1depengwyn requested changes

2023-11-13 21:20 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/smart_contract.ex
> +  def check_and_update_constructor_args(other), do: other
Could you please add spec and doc for these functions?

2023-11-13 21:20 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/smart_contract_additional_sources.ex
> +  end
It seems from function body that `smart_contract` may be `nil`, shouldn't it be reflected in the spec?

2023-11-13 21:20 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/smart_contract.ex
> +  @spec add_twin_info_to_contract(map(), Chain.Hash.t(), Chain.Hash.t()) :: map()
It seems that second argument can be nil

2023-11-13 21:20 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/smart_contract.ex
> +  @spec create_smart_contract(map()) :: {:ok, __MODULE__.t()} | {:error, Ecto.Changeset.t()}
Maybe we need to add here `external_libraries` and `secondary_sources` arguments as well?

2023-11-13 21:20 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/smart_contract.ex
> +  @spec update_smart_contract(map()) :: {:ok, __MODULE__.t()} | {:error, Ecto.Changeset.t()}
Maybe we need to add here external_libraries and secondary_sources arguments as well?

2023-11-13 21:20 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/smart_contract.ex
> +  @spec verified_with_full_match?(any()) :: boolean()
Shouldn't be here `Hash.Address.t() | String.t()`?

2023-11-13 21:20 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/smart_contract.ex
> +  @spec verified?(any()) :: boolean()
Shouldn't be here `Hash.Address.t() | String.t()?`

2023-11-13 21:20 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/smart_contract.ex
> +  @spec get_smart_contract_abi(any(), any()) :: any()
First argument type should be `String.t()` I think

2023-11-14 08:56 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/block/reward.ex
> +  @burn_address_hash_string "0x0000000000000000000000000000000000000000"
This
```
Compilation failed because of a deadlock between files.
The following files depended on the following modules:

             lib/explorer/account/notifier/forbidden_address.ex => Explorer.Chain.SmartContract
  lib/explorer/token_instance_owner_address_migration/helper.ex => Explorer.Chain.SmartContract
                    lib/explorer/chain/address/token_balance.ex => Explorer.Chain.SmartContract
                         lib/explorer/chain/address/counters.ex => Explorer.Chain
                        lib/explorer/account/notifier/notify.ex => Explorer.Chain
            lib/explorer/chain/address/current_token_balance.ex => Explorer.Chain.SmartContract
                                          lib/explorer/chain.ex => Explorer.Chain.Block.Reward
        lib/explorer/chain/smart_contract_additional_sources.ex => Explorer.Chain
                           lib/explorer/chain/smart_contract.ex => Explorer.Chain.SmartContractAdditionalSource
            lib/explorer/chain/smart_contract/proxy/eip_1967.ex => Explorer.Chain.SmartContract
         lib/explorer/chain/smart_contract/proxy/master_copy.ex => Explorer.Chain.SmartContract
                     lib/explorer/chain/smart_contract/proxy.ex => Explorer.Chain
                             lib/explorer/chain/block/reward.ex => Explorer.Chain.SmartContract

Ensure there are no compile-time dependencies between those files and that the modules they reference exist and are correctly named
```

2023-11-15 11:42 UTC, nikitosing requested changes

2023-11-15 11:42 UTC, nikitosing commented on apps/explorer/lib/explorer/chain/smart_contract/proxy/basic.ex
> +  @spec get_implementation_address(any(), binary(), any()) :: nil | binary()
I suggest to imrpove spec: `get_implementation_address(binary, binary, SmartContract.abi) :: nil | binary`

2023-11-15 11:42 UTC, nikitosing commented on apps/explorer/lib/explorer/chain/smart_contract/proxy/eip_1822.ex
> +  @spec get_implementation_address(Hash.Address.t()) :: SmartContract.t() | nil
It won't return SmartContract, as I see. Please fix spec. Also it's strange that dialyzer did not produce error because of wrong return type in this function.

2023-11-15 11:42 UTC, nikitosing commented on apps/explorer/lib/explorer/chain/smart_contract/proxy.ex
> +          EIP1167.get_implementation_address(proxy_address_hash) ||
This function will return SmartContract. I'm not sure if we can handle it, moreover function is supposed to return string (`get_implementation_address_hash_string`). I suggest to cast returns of all proxy getter to common denominator.

2023-11-15 11:42 UTC, nikitosing commented on apps/explorer/lib/explorer/chain/smart_contract/proxy/eip_930.ex
> +  @spec get_implementation_address(any(), binary(), any()) :: nil | binary()
I suggest to imrpove spec: `get_implementation_address(binary, binary, SmartContract.abi) :: nil | binary`

2023-11-15 11:42 UTC, nikitosing commented on apps/explorer/lib/explorer/chain/smart_contract/proxy/eip_1967.ex
> +  @spec get_implementation_address(Hash.Address.t()) :: SmartContract.t() | nil
The same as above, wrong return type

2023-11-15 11:42 UTC, nikitosing commented on apps/explorer/lib/explorer/chain/smart_contract/proxy/eip_1967.ex
> +
mb join function calls here with `||` in order to utilize lazy evaluation?

```
    implementation_address_hash_string =
      Proxy.get_implementation_from_storage(
        proxy_address_hash,
        @storage_slot_logic_contract_address,
        json_rpc_named_arguments
      ) || 
      fetch_beacon_proxy_implementation(proxy_address_hash, json_rpc_named_arguments) ||
      Proxy.get_implementation_from_storage(
        proxy_address_hash,
        @storage_slot_openzeppelin_contract_address,
        json_rpc_named_arguments
      )
```

2023-11-15 11:42 UTC, nikitosing commented on apps/explorer/lib/explorer/chain/smart_contract/proxy/master_copy.ex
> +  @spec get_implementation_address(Hash.Address.t()) :: SmartContract.t() | nil
Same as above, wrong return type

2023-11-15 11:51 UTC, vbaranov commented on apps/explorer/lib/explorer/chain.ex
> +  def verified_contracts_top(limit) do
I didn't touch because of @sl1depengwyn sorting PR may affect this as well. I'd keep it here for now and return with a new PR.

2023-11-15 13:21 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/address/name.ex
> +    )
I left it as is since the suggested change cause issue:
```
     ** (Ecto.QueryError) `update_all` allows only `with_cte`, `where` and `join` expressions. You can exclude unwanted expressions from a query by using Ecto.Query.exclude/2. Error found in query:

     from n0 in Explorer.Chain.Address.Name,
       where: n0.address_hash ==
       ^%Explorer.Chain.Hash{byte_count: 20, bytes: <<15, 149, 250, 155, 192, 56, 62, 105, 147, 37, 242, 101, 141, 4, 232, 217, 109, 135, 185, 12>>},
       where: n0.primary == true,
       order_by: [asc: n0.address_hash, asc: n0.name],
       lock: "FOR NO KEY UPDATE",
       update: [set: [primary: ^false]]
```

2023-11-16 09:22 UTC, nikitosing commented on apps/explorer/lib/explorer/chain/smart_contract.ex
> +      when is_burn_signature_extended(empty_address_hash_string) do
Shouldn't we union these 2 caluses to:
```
def save_implementation_data(empty_address_hash_string, proxy_address_hash, metadata_from_verified_twin, options)
      when is_burn_signature_extended(empty_address_hash_string) or is_nil(empty_address_hash_string) do
```
It will allow us to save `implementation_fetched_at` for nil cases

2023-11-16 09:36 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/smart_contract.ex
> +      when is_burn_signature_extended(empty_address_hash_string) do
I'd suggest doing this in frame of a separate PR. Currently, I have doubts to implement this in suggested maneer. Anyways, changes in this PR don't touch this logic and targeted to solve other (not performance) problems. Please, create an issue for the case you're reffering to.

2023-11-16 16:07 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/block/reward.ex
> +  @burn_address_hash_string "0x0000000000000000000000000000000000000000"
Worked when change to aliasing instead of importing

2023-11-16 16:41 UTC, sl1depengwyn approved these changes

2023-11-16 17:12 UTC, merged