Enhance method decoding by candidates from DB
blockscout/blockscout pull request #8898
Opened 2023-11-27 20:26 UTC by vbaranov

Resolves https://github.com/blockscout/blockscout/issues/8892

## Motivation

Methods decoding doesn't work properly, if there are 3 conditions are satisifed:
- contract emitted event is proxy contract
- Blockscout didn't recognize it as a proxy
- Implementation is verfied

## Changelog

Find method candidates from the DB, if no ABI for such selector in the contract or/and sig-provider microservice is disabled.

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [x] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [x] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [x] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2023-11-28 09:21 UTC, varasev approved these changes

2023-12-04 10:45 UTC, Qwerty5Uiop approved these changes

2023-12-04 11:00 UTC, nikitosing commented on apps/explorer/lib/explorer/chain/log.ex
> +          Proxy.combine_proxy_implementation_abi(smart_contract, options)
Why did you decided to ignore contracts accumulator here and in other places?

2023-12-04 15:14 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/log.ex
> +          Proxy.combine_proxy_implementation_abi(smart_contract, options)
This test is failing, if to leave accumulator:
```
1) test decode/2 that a contract call transaction that has a verified contract returns the decoded input data (Explorer.Chain.LogTest)
     test/explorer/chain/log_test.exs:66
     match (=) failed
     code:  assert {{:ok, "eb9b3c4c", "WantsPets(string indexed _from_human, uint256 _number, bool indexed _belly)",
              [
                {"_from_human", "string", true,
                 {:dynamic,
                  <<56, 228, 122, 123, 113, 157, 206, 99, 102, 42, 234, 244, 52, 64, 50, 111, 85, 27, 138,
                    126, 225, 152, 206, 227, 92, 181, 213, 23, 242, 210, 150, 162>>}},
                {"_number", "uint256", false, 0},
                {"_belly", "bool", true, true}
              ]}, _} = Log.decode(log, transaction, [], false)
     left:  {
              {
                :ok,
                "eb9b3c4c",
                "WantsPets(string indexed _from_human, uint256 _number, bool indexed _belly)",
                [
                  {
                    "_from_human",
                    "string",
                    true,
                    {
                      :dynamic,
                      <<56, 228, 122, 123, 113, 157, 206, 99, 102, 42, 234, 244, 52, 64, 50, 111, 85, 27, 138, 126, 225,
  152, 206, 227, 92, 181, 213, 23, 242, 210, 150, 162>>
                    }
                  },
                  {"_number", "uint256", false, 0},
                  {"_belly", "bool", true, true}
                ]
              },
              _
            }
     right: {{:error, :could_not_decode}, %{<<235, 155, 60, 76>> => {:error, :contract_not_verified, []}}}
     stacktrace:
       test/explorer/chain/log_test.exs:111: (test)
```

2023-12-05 09:54 UTC, nikitosing requested changes

2023-12-05 09:54 UTC, nikitosing commented on apps/explorer/lib/explorer/chain/log.ex
> +          case find_method_candidates(log, transaction, options, events_acc) do
We shouldn't call this function here, I think. Because `find_method_candidates` calls `find_method_candidates_from_db` which can call `decode_event_via_sig_provider`, and it will possibly cause infinity loop

2023-12-05 16:05 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/log.ex
> +          case find_method_candidates(log, transaction, options, events_acc) do
The all "salt" is actually that we using this fallback here. But I agree, this shouldn't cause infinity loop of calls. Taking this in mind I added `skip_sig_provider` function argument and set to `true` for the fallback lookup of decoding candidates. Implemented here https://github.com/blockscout/blockscout/pull/8898/commits/4ee95ea40c5b8201a755db33909f547eeb2ccb1e.

2023-12-05 18:53 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/log.ex
> +          case find_method_candidates(log, transaction, options, events_acc) do
Finally resolved in https://github.com/blockscout/blockscout/pull/8898/commits/7727d93d64396f4c83a69dd28a91b7ec231e5303. (Change in eex template is just to fix formatting)

2023-12-06 07:12 UTC, merged