Solidityscan report API endpoint
blockscout/blockscout pull request #8908
Opened 2023-11-29 12:28 UTC by vbaranov

Resolves https://github.com/blockscout/blockscout/issues/8907

## Motivation

Adding API V2 endpoint for proxying request of Solidityscan report.

## Changelog

New API v2 endpoint added:
```
api/v2/smart-contracts/#{contract_address_hash}/solidityscan-report
```

Sample success response:
```
{
    "scan_report": {
        "contract_address": "0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B",
        "contract_chain": "eth",
        "contract_platform": "blockscout",
        "contract_url": "https://eth.blockscout.com/address/0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B",
        "contractname": "Unitroller",
        "node_reference_id": null,
        "scan_status": "scan_done",
        "scan_summary": {
            "issue_severity_distribution": {
                "critical": 0,
                "gas": 95,
                "high": 1,
                "informational": 18,
                "low": 31,
                "medium": 1
            },
            "lines_analyzed_count": 2449,
            "scan_time_taken": 6,
            "score": "4.63",
            "score_v2": "92.57",
            "threat_score": "88.89"
        },
        "scanner_reference_url": "https://solidityscan.com/quickscan/0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B/blockscout/eth?ref=blockscout"
    },
    "status": "success"
}
```

Sample failed response:
```
{
    "message": "...",
    "status": "error"
}
```

## Checklist for your Pull Request (PR)

  - [x] I added an entry to `CHANGELOG.md` with this PR https://github.com/blockscout/docs/pull/200
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [x] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [x] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [x] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2023-11-30 05:43 UTC, varasev commented on apps/explorer/lib/explorer/account/notifier/forbidden_address.ex
> +    end
Previously, the `is_contract` function returned non-boolean value, but now it will always be boolean. Doesn't it affect backend logic in other code somehow?

2023-11-30 05:53 UTC, varasev commented on apps/explorer/lib/explorer/third_party_integrations/solidityscan.ex
> +        Helper.decode_json(body)
`Helper.decode_json` here can return encoded body (in case of invalid json). Is it expected behaviour?

2023-12-04 18:05 UTC, nikitosing requested changes

2023-12-04 18:05 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex
> +
In API v2 we usually state all mismatched with patters in BlockScoutWeb.API.V2.FallbackController. Most likely all of the patterns you stated, already exist in FallbackController

2023-12-04 18:25 UTC, vbaranov commented on apps/explorer/lib/explorer/third_party_integrations/solidityscan.ex
> +  defp base_url(address_hash_string) do
What is the purpose? What if they change the api path? I'd say we shouldn't depend on this naming in intertnal namings.

2023-12-04 18:30 UTC, vbaranov commented on apps/explorer/lib/explorer/third_party_integrations/solidityscan.ex
> +  @recv_timeout 60_000
I'd say this suggestion would be opposite to consistency:

![Screenshot 2023-12-04 at 21 27 03](https://github.com/blockscout/blockscout/assets/4341812/ac6050b8-7064-44b7-8f30-1c26f9b344c6)

We should change it consistently in the whole application. I'd move this change outside of this PR. Since the change in the PR doesn't bring any inconsistency.

2023-12-04 18:44 UTC, vbaranov commented on apps/explorer/lib/explorer/account/notifier/forbidden_address.ex
> +    end
Btw `Address.is_smart_contract(address)` still can return nil
in this case https://github.com/blockscout/blockscout/blob/14a6089d98d0a2f68245ca4226cf3f6370a7254b/apps/explorer/lib/explorer/chain/address.ex#L342

Thus, `is_contract`, seems, can return `nil` in some circumstances.

And `is_contract` function is private and it is used only here afaics
https://github.com/blockscout/blockscout/blob/14a6089d98d0a2f68245ca4226cf3f6370a7254b/apps/explorer/lib/explorer/account/notifier/forbidden_address.ex#L34

so, we check only for true value. Thus, I suppose it is safe change.

2023-12-04 19:47 UTC, vbaranov commented on apps/explorer/lib/explorer/smart_contract/compiler_version.ex
> -  end
This is a valid point. It actually affects. I generalized decode_json behavious over the whole application here https://github.com/blockscout/blockscout/pull/8908/commits/ffa4f8c6fc8df1fd2f34a2b543b684fff15e6251. It should properly handle mentioned case now.

2023-12-04 19:47 UTC, vbaranov commented on apps/explorer/lib/explorer/third_party_integrations/solidityscan.ex
> +        Helper.decode_json(body)
Handled in https://github.com/blockscout/blockscout/commit/ffa4f8c6fc8df1fd2f34a2b543b684fff15e6251

2023-12-04 19:47 UTC, vbaranov commented on apps/explorer/lib/explorer/helper.ex
> +  rescue
Done in https://github.com/blockscout/blockscout/commit/ffa4f8c6fc8df1fd2f34a2b543b684fff15e6251

2023-12-04 20:43 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex
> +
Ok, extended fallback controller with new responses in https://github.com/blockscout/blockscout/pull/8908/commits/381a6ebdbbd0aaf718f2e45f3005ccfbfc30af98

2023-12-05 09:17 UTC, sl1depengwyn requested changes

2023-12-05 09:17 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/smart_contract/compiler_version.ex
>      if RustVerifierInterface.enabled?() do
Maybe we will pass function instead of list to not to execute request if rust verifier is disabled?
Like this
```elixir
  defp fetch_solc_versions do
    fetch_compiler_versions(&RustVerifierInterface.get_versions_list/0, :solc)
  end

  defp fetch_vyper_versions do
    fetch_compiler_versions(&RustVerifierInterface.vyper_get_versions_list/0, :vyper)
  end

  defp fetch_compiler_versions(compiler_list_fn, compiler_type) do
    if RustVerifierInterface.enabled?() do
      compiler_list_fn.()
    else
      headers = [{"Content-Type", "application/json"}]

      case HTTPoison.get(source_url(compiler_type), headers) do
        {:ok, %{status_code: 200, body: body}} ->
          {:ok, format_data(body, compiler_type)}

        {:ok, %{status_code: _status_code, body: body}} ->
          {:error, Helper.decode_json(body)["error"]}

        {:error, %{reason: reason}} ->
          {:error, reason}
      end
    end
  end
```

2023-12-05 09:17 UTC, sl1depengwyn commented on .dialyzer-ignore
> +lib/explorer/exchange_rates/source.ex:137
What do you think about these dialyzer warnings? It seems that `HTTPoison.get` may return only `%Response{}` or `%Error{}` indeed, maybe we can remove this clauses https://github.com/blockscout/blockscout/blob/vb-solidityscan-support/apps/explorer/lib/explorer/exchange_rates/source.ex#L134-L138?

2023-12-05 09:58 UTC, vbaranov commented on .dialyzer-ignore
> +lib/explorer/exchange_rates/source.ex:137
I agree. Implemented in https://github.com/blockscout/blockscout/pull/8908/commits/48ac39660df8958f51c1adbf87ac37c3611569c5

2023-12-05 09:58 UTC, vbaranov commented on apps/explorer/lib/explorer/smart_contract/compiler_version.ex
>      if RustVerifierInterface.enabled?() do
Makes sense. Applied in https://github.com/blockscout/blockscout/pull/8908/commits/48ac39660df8958f51c1adbf87ac37c3611569c5

2023-12-05 10:44 UTC, varasev commented on apps/explorer/lib/explorer/third_party_integrations/sourcify.ex
>        {:error, body_json["error"]}
Since `decode_json` can return `%{error: data}`, here will be `{:error, nil}` in that case

2023-12-05 10:58 UTC, vbaranov commented on apps/explorer/lib/explorer/third_party_integrations/sourcify.ex
>        {:error, body_json["error"]}
It looks like this will not cause issue, because:
```
iex(2)> res = nil
nil
iex(3)> res["error"]
nil
```
Or do I missed your point?

2023-12-05 11:05 UTC, sl1depengwyn approved these changes

2023-12-05 12:06 UTC, varasev commented on apps/explorer/lib/explorer/third_party_integrations/sourcify.ex
>        {:error, body_json["error"]}
I meant the case when `is_map(body_json)` is true, but `body_json` is invalid json. In this case `%{error: data}` is returned, but `parse_http_error_response` will return `{:error, nil}`

2023-12-05 15:19 UTC, vbaranov commented on apps/explorer/lib/explorer/third_party_integrations/sourcify.ex
>        {:error, body_json["error"]}
Related commit https://github.com/blockscout/blockscout/pull/8908/commits/91d583bede36bee56ad22691d59774f9de63331a.

2023-12-06 06:13 UTC, varasev approved these changes

2023-12-06 06:16 UTC, merged