BENS integration
blockscout/blockscout pull request #8972
Opened 2023-12-10 11:54 UTC by nikitosing

Close #8901 

## Changelog

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2023-12-14 20:00 UTC, vbaranov reviewed
api/v2/transactions/0xcc26f0091a48bed21a0438d93cd308168724d02d06819b6df4a2379ee032dd5e

On ETH Goerli
returns
```
    "to": {
        "ens_domain_name": null,
        "hash": "0xFD50b031E778fAb33DfD2Fc3Ca66a1EeF0652165", 
```

should vitalik.eth be resolved here?

2023-12-18 10:04 UTC, vbaranov approved these changes

2023-12-19 18:17 UTC, sl1depengwyn requested changes

2023-12-19 18:17 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/microservice_interfaces/bens.ex
> +      end)
Is it okay that we may send the same address hashes? Does the service handle it well or maybe it's better to collect address hashes here to `MapSet`?

2023-12-19 18:17 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/microservice_interfaces/bens.ex
> +        acc ++ item_to_address_hash_strings(item)
If we keep this way of things, let's swap `acc` and `item_to_address_hash_strings(item)` since the complexity of a ++ b is proportional to length(a) and `item_to_address_hash_strings(item)` is at most two elements

2023-12-19 18:17 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/microservice_interfaces/bens.ex
> +        Map.put(search_result, :ens_info, ens_info)
Maybe it makes sense here to utilize batch request to eliminate round trip time of each request?

2023-12-19 18:17 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/microservice_interfaces/bens.ex
> +  end
Just a nitpick, maybe we can avoid some wordiness by merging this two clauses like this:
```elixir
  defp item_to_address_hash_strings(%Transaction{
         to_address_hash: to_address_hash,
         created_contract_address_hash: created_contract_address_hash,
         from_address_hash: from_address_hash
       }) do
    [to_string(to_address_hash || created_contract_address_hash), to_string(from_address_hash)]
  end
```
If you found it's much less readable let's leave it as it is

2023-12-19 18:17 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/microservice_interfaces/bens.ex
> +  end
Just to make sure, wouldn't it cause any issues in cases when we pattern match the address and expect it to be, for instance either `%Address{}` or `%NotLoaded{}` or `nil`, and in this case we can get only `%{ens_domain_name: String.t()}`, may we for instance mix it up with `%Address{}` and try to access some field that is not present in this map via dot-syntax?

2023-12-19 19:08 UTC, nikitosing commented on apps/explorer/lib/explorer/microservice_interfaces/bens.ex
> +      end)
Yes, bens filters duplicates by it's own

2023-12-19 19:14 UTC, nikitosing commented on apps/explorer/lib/explorer/microservice_interfaces/bens.ex
> +        Map.put(search_result, :ens_info, ens_info)
Strictly speaking, the maximum amount of addresses in the search response is 1. So there are no necessity to utilize batch request. Moreover, in search we need full ens info, which is provided by lookup endpoint, which is not batch.

2023-12-19 19:22 UTC, nikitosing commented on apps/explorer/lib/explorer/microservice_interfaces/bens.ex
> +  end
Usually data from controller is going to be processed via view direclty. I added special clause for it, so this shouldn't be a problem https://github.com/blockscout/blockscout/blob/00ec9775cc6ed601e225a3a6167d908875d14456/apps/block_scout_web/lib/block_scout_web/views/api/v2/helper.ex#L62

2023-12-19 19:23 UTC, nikitosing commented on apps/explorer/lib/explorer/microservice_interfaces/bens.ex
> +  end
I'd prefer to leave it as is. It's good suggestion really, but I think initial variant is more readable

2023-12-19 20:36 UTC, sl1depengwyn approved these changes

2023-12-19 21:25 UTC, merged