Change log topic type in the DB to bytea
blockscout/blockscout pull request #9000
Opened 2023-12-13 17:36 UTC by vbaranov

## Motivation

To save storage space for `logs` table (which is in top 3 by storage occupied) we can migrate log topics from `character varying(255)` to `bytea`.

## Changelog

Change type `character varying(255)` to `bytea` for the  next columns in `logs` table:
- `first_topic`
- `second_topic`
- `third_topic`
- `fourth_topic`

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2023-12-15 11:04 UTC, Qwerty5Uiop approved these changes

2023-12-15 12:51 UTC, sl1depengwyn requested changes

2023-12-15 12:51 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/log.ex
>           {number, ""} <- Integer.parse(hex_part, 16) do
It seems that 
```elixir
hex_part <- Base.encode16(log.first_topic.bytes, case: :lower),
{number, ""} <- Integer.parse(hex_part, 16)
```
is redundant here
we can get method id directly:
```elixir
<<method_id::binary-size(4), _rest::binary>> = log.first_topic.bytes
```

2023-12-17 12:07 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/log.ex
>           {number, ""} <- Integer.parse(hex_part, 16) do
Nice catch. Fixed in https://github.com/blockscout/blockscout/pull/9000/commits/f294506f18119f8085e07e8b7b24dcbb8a1c2972.

2023-12-18 11:10 UTC, nikitosing requested changes
Error while trying to fetch logs
```
2023-12-18T14:08:08.341 [error] #PID<0.3873.0> running BlockScoutWeb.Endpoint (connection #PID<0.3075.0>, stream id 11) terminated
Server: localhost:4000 (http)
Request: GET /tx/0xc949173ffbe230758ac816784865a9c4c4994a4a63a45fd729f910d7ba8c46ca/logs?type=JSON
** (exit) an exception was raised:
    ** (Jason.EncodeError) invalid byte 0xDD in <<60, 100, 105, 118, 32, 100, 97, 116, 97, 45, 116, 101, 115, 116, 61, 34, 116, 114, 97, 110, 115, 97, 99, 116, 105, 111, 110, 95, 108, 111, 103, 34, 32, 99, 108, 97, 115, 115, 61, 34, 116, 105, 108, 101, 32, 116, 105, 108, 101, 45, ...>>
        (jason 1.4.1) lib/jason.ex:213: Jason.encode_to_iodata!/2
        (phoenix 1.5.14) lib/phoenix/controller.ex:284: Phoenix.Controller.json/2
        (block_scout_web 5.3.3) lib/block_scout_web/controllers/transaction_log_controller.ex:1: BlockScoutWeb.TransactionLogController.action/2
        (block_scout_web 5.3.3) lib/block_scout_web/controllers/transaction_log_controller.ex:1: BlockScoutWeb.TransactionLogController.phoenix_controller_pipeline/2
        (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (phoenix 1.5.14) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
        (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (block_scout_web 5.3.3) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2
        (block_scout_web 5.3.3) /Users/nikitosing/work/blockscout/blockscout/deps/plug/lib/plug/debugger.ex:136: BlockScoutWeb.Endpoint."call (overridable 3)"/2
        (block_scout_web 5.3.3) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint."call (overridable 4)"/2
        (block_scout_web 5.3.3) /Users/nikitosing/work/blockscout/blockscout/deps/spandex_phoenix/lib/spandex_phoenix.ex:151: BlockScoutWeb.Endpoint.call/2
        (phoenix 1.5.14) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.10.0) /Users/nikitosing/work/blockscout/blockscout/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.10.0) /Users/nikitosing/work/blockscout/blockscout/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.10.0) /Users/nikitosing/work/blockscout/blockscout/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```
![image](https://github.com/blockscout/blockscout/assets/32202610/57167871-cb60-4965-96b6-5f4cf271f206)

```
2023-12-18T14:09:08.993 [error] #PID<0.4383.0> running BlockScoutWeb.Endpoint (connection #PID<0.4382.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /api/v2/transactions/0xc949173ffbe230758ac816784865a9c4c4994a4a63a45fd729f910d7ba8c46ca/logs
** (exit) an exception was raised:
    ** (Jason.EncodeError) invalid byte 0xDD in <<221, 242, 82, 173, 27, 226, 200, 155, 105, 194, 176, 104, 252, 55, 141, 170, 149, 43, 167, 241, 99, 196, 161, 22, 40, 245, 90, 77, 245, 35, 179, 239>>
        (jason 1.4.1) lib/jason.ex:213: Jason.encode_to_iodata!/2
        (phoenix 1.5.14) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4
        (block_scout_web 5.3.3) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:1: BlockScoutWeb.API.V2.TransactionController.action/2
        (block_scout_web 5.3.3) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:1: BlockScoutWeb.API.V2.TransactionController.phoenix_controller_pipeline/2
        (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (phoenix 1.5.14) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
        (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (block_scout_web 5.3.3) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2
        (block_scout_web 5.3.3) /Users/nikitosing/work/blockscout/blockscout/deps/plug/lib/plug/debugger.ex:136: BlockScoutWeb.Endpoint."call (overridable 3)"/2
        (block_scout_web 5.3.3) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint."call (overridable 4)"/2
        (block_scout_web 5.3.3) /Users/nikitosing/work/blockscout/blockscout/deps/spandex_phoenix/lib/spandex_phoenix.ex:151: BlockScoutWeb.Endpoint.call/2
        (phoenix 1.5.14) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.10.0) /Users/nikitosing/work/blockscout/blockscout/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.10.0) /Users/nikitosing/work/blockscout/blockscout/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.10.0) /Users/nikitosing/work/blockscout/blockscout/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```
![image](https://github.com/blockscout/blockscout/assets/32202610/582b2968-cf0a-4ab3-8cc9-1d86cb3b2ca7)

2023-12-19 10:15 UTC, sl1depengwyn requested changes

2023-12-19 11:09 UTC, sl1depengwyn approved these changes

2023-12-19 11:38 UTC, vbaranov commented
> Error while trying to fetch logs
> 
> ```
> 2023-12-18T14:08:08.341 [error] #PID<0.3873.0> running BlockScoutWeb.Endpoint (connection #PID<0.3075.0>, stream id 11) terminated
> Server: localhost:4000 (http)
> Request: GET /tx/0xc949173ffbe230758ac816784865a9c4c4994a4a63a45fd729f910d7ba8c46ca/logs?type=JSON
> ** (exit) an exception was raised:
>     ** (Jason.EncodeError) invalid byte 0xDD in <<60, 100, 105, 118, 32, 100, 97, 116, 97, 45, 116, 101, 115, 116, 61, 34, 116, 114, 97, 110, 115, 97, 99, 116, 105, 111, 110, 95, 108, 111, 103, 34, 32, 99, 108, 97, 115, 115, 61, 34, 116, 105, 108, 101, 32, 116, 105, 108, 101, 45, ...>>
>         (jason 1.4.1) lib/jason.ex:213: Jason.encode_to_iodata!/2
>         (phoenix 1.5.14) lib/phoenix/controller.ex:284: Phoenix.Controller.json/2
>         (block_scout_web 5.3.3) lib/block_scout_web/controllers/transaction_log_controller.ex:1: BlockScoutWeb.TransactionLogController.action/2
>         (block_scout_web 5.3.3) lib/block_scout_web/controllers/transaction_log_controller.ex:1: BlockScoutWeb.TransactionLogController.phoenix_controller_pipeline/2
>         (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
>         (phoenix 1.5.14) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
>         (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
>         (block_scout_web 5.3.3) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2
>         (block_scout_web 5.3.3) /Users/nikitosing/work/blockscout/blockscout/deps/plug/lib/plug/debugger.ex:136: BlockScoutWeb.Endpoint."call (overridable 3)"/2
>         (block_scout_web 5.3.3) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint."call (overridable 4)"/2
>         (block_scout_web 5.3.3) /Users/nikitosing/work/blockscout/blockscout/deps/spandex_phoenix/lib/spandex_phoenix.ex:151: BlockScoutWeb.Endpoint.call/2
>         (phoenix 1.5.14) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
>         (cowboy 2.10.0) /Users/nikitosing/work/blockscout/blockscout/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
>         (cowboy 2.10.0) /Users/nikitosing/work/blockscout/blockscout/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
>         (cowboy 2.10.0) /Users/nikitosing/work/blockscout/blockscout/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
>         (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/32202610/291260791-57167871-cb60-4965-96b6-5f4cf271f206.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODYxMzUsIm5iZiI6MTcwMjk4NTgzNSwicGF0aCI6Ii8zMjIwMjYxMC8yOTEyNjA3OTEtNTcxNjc4NzEtY2I2MC00OTY1LTk2YjYtNWY0Y2YyNzFmMjA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDExMzcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YTY3ZDIxODgyNTZmZTA5MzBhZDZmMDFhZjQxOTIwNWE1MjBmODM1YjYyNGNlZTc4MmJiNTk4MTZhZmU3Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jyNpgKkRjfKvB6Ngqju5hL38GOWt2y2GFGSL6vx1Qn8)
> 
> ```
> 2023-12-18T14:09:08.993 [error] #PID<0.4383.0> running BlockScoutWeb.Endpoint (connection #PID<0.4382.0>, stream id 1) terminated
> Server: localhost:4000 (http)
> Request: GET /api/v2/transactions/0xc949173ffbe230758ac816784865a9c4c4994a4a63a45fd729f910d7ba8c46ca/logs
> ** (exit) an exception was raised:
>     ** (Jason.EncodeError) invalid byte 0xDD in <<221, 242, 82, 173, 27, 226, 200, 155, 105, 194, 176, 104, 252, 55, 141, 170, 149, 43, 167, 241, 99, 196, 161, 22, 40, 245, 90, 77, 245, 35, 179, 239>>
>         (jason 1.4.1) lib/jason.ex:213: Jason.encode_to_iodata!/2
>         (phoenix 1.5.14) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4
>         (block_scout_web 5.3.3) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:1: BlockScoutWeb.API.V2.TransactionController.action/2
>         (block_scout_web 5.3.3) lib/block_scout_web/controllers/api/v2/transaction_controller.ex:1: BlockScoutWeb.API.V2.TransactionController.phoenix_controller_pipeline/2
>         (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
>         (phoenix 1.5.14) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
>         (phoenix 1.5.14) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
>         (block_scout_web 5.3.3) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint.plug_builder_call/2
>         (block_scout_web 5.3.3) /Users/nikitosing/work/blockscout/blockscout/deps/plug/lib/plug/debugger.ex:136: BlockScoutWeb.Endpoint."call (overridable 3)"/2
>         (block_scout_web 5.3.3) lib/block_scout_web/endpoint.ex:1: BlockScoutWeb.Endpoint."call (overridable 4)"/2
>         (block_scout_web 5.3.3) /Users/nikitosing/work/blockscout/blockscout/deps/spandex_phoenix/lib/spandex_phoenix.ex:151: BlockScoutWeb.Endpoint.call/2
>         (phoenix 1.5.14) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
>         (cowboy 2.10.0) /Users/nikitosing/work/blockscout/blockscout/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
>         (cowboy 2.10.0) /Users/nikitosing/work/blockscout/blockscout/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
>         (cowboy 2.10.0) /Users/nikitosing/work/blockscout/blockscout/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
>         (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/32202610/291260928-582b2968-cf0a-4ab3-8cc9-1d86cb3b2ca7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODYxMzUsIm5iZiI6MTcwMjk4NTgzNSwicGF0aCI6Ii8zMjIwMjYxMC8yOTEyNjA5MjgtNTgyYjI5NjgtY2YwYS00YWIzLThjYzktMWQ4NmNiM2IyY2E3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDExMzcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3M2RhNzMwMjdhYjRjNTQ2NmRmOTlmYTdhYzAzYzg3MGFjZGNhZTc4MTlmNzJiMGQ1MTk0YjZmMTVkZmM2ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eqtIVkhI7UYOdscis6TxnjUDjVrD63IySnWuXMkDPKg)

@nikitosing please let me know how to reproduce the issue? I tried random Goerli transactions - API and UI works fone for them.

2023-12-19 17:42 UTC, nikitosing commented
@vbaranov Seems that I had some problems with data in DB. Tried with newly created DB, everything work fine

2023-12-19 17:42 UTC, nikitosing approved these changes

2023-12-19 17:55 UTC, nikitosing approved these changes

2023-12-21 08:14 UTC, varasev commented
Please, don't merge it yet. I need to check tx actions module as it may break down

2023-12-21 10:58 UTC, varasev approved these changes
I added small changes related to TransactionAction and PolygonEdge modules to support the new log type: https://github.com/blockscout/blockscout/pull/9000/commits/dd440fefb8f5beb071f3f415b6fae8ae4a738187

2023-12-21 14:02 UTC, merged