Optimize NFT owner preload
blockscout/blockscout pull request #9015
Opened 2023-12-17 18:34 UTC by nikitosing

Closes #8995 

## Changelog
- Optimize NFT owner preload

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2023-12-21 13:22 UTC, sl1depengwyn requested changes

2023-12-21 13:22 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/token/instance.ex
> +          is_unique: bool()
Please, add `| nil`

2023-12-21 13:22 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain.ex
> +    owner_address_hash =
Why we can't use `owner_address_hash` from instance?

2023-12-21 14:27 UTC, nikitosing commented on apps/explorer/lib/explorer/chain.ex
> +    owner_address_hash =
`owner_address_hash` for ERC-1155 is nil

2023-12-21 18:59 UTC, sl1depengwyn approved these changes

2023-12-22 13:48 UTC, vbaranov approved these changes

2023-12-22 13:54 UTC, merged