Handle Postgrex errors on NFT import
blockscout/blockscout pull request #9035
Opened 2023-12-20 12:59 UTC by nikitosing

Closes #8385 
Closes #7655

## Changelog
- Handle Postgrex errors on NFT import

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2023-12-21 13:12 UTC, sl1depengwyn requested changes

2023-12-21 13:12 UTC, sl1depengwyn commented on apps/indexer/lib/indexer/fetcher/token_instance/helper.ex
> +      if retry? do
Aren't the clauses mixed up?

2023-12-22 07:54 UTC, nikitosing commented on apps/indexer/lib/indexer/fetcher/token_instance/helper.ex
> +      if retry? do
What do you mean?

2023-12-22 08:14 UTC, sl1depengwyn approved these changes

2023-12-22 13:47 UTC, vbaranov approved these changes

2023-12-22 14:07 UTC, merged