Fix tx input decoding in tx summary microservice request
blockscout/blockscout pull request #9039
Opened 2023-12-21 08:44 UTC by nikitosing

## Motivation

- `decoded_input` was missed in tx summary request for unverified contracts 

## Changelog
- Fix tx input decoding in tx summary microservice request

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2023-12-21 13:03 UTC, sl1depengwyn requested changes

2023-12-21 13:03 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain/transaction.ex
>    def decoded_input_data(tx, skip_sig_provider? \\ false, options, full_abi_acc \\ %{}, methods_acc \\ %{})
I suggest to change spec to something like this:
```suggestion
  @spec decoded_input_data(
          %NotLoaded{} | Transaction.t(),
          boolean(),
          [Chain.api?()],
          full_abi_acc,
          methods_acc
        ) ::
          {error_type | success_type, full_abi_acc, methods_acc}
        when full_abi_acc: map(),
             methods_acc: map(),
             error_type: {:error, any()} | {:error, :contract_not_verified | :contract_verified, list()},
             success_type: {:ok | binary(), any()} | {:ok, binary(), binary(), list()}
  def decoded_input_data(tx, skip_sig_provider? \\ false, options, full_abi_acc \\ %{}, methods_acc \\ %{})
```

It's not only brings more type information that makes this function safer, but it's more readable in my opinion

2023-12-21 19:01 UTC, sl1depengwyn approved these changes

2023-12-22 12:45 UTC, vbaranov approved these changes

2023-12-22 12:47 UTC, merged