Noves.fi API proxy
blockscout/blockscout pull request #9056
Opened 2023-12-25 15:55 UTC by vbaranov

## Motivation

Proxy [Noves.fi API endpoints](https://blockscout.noves.fi/swagger/index.html):
```
/evm/{chain}/tx/{txHash}
/evm/{chain}/describeTx/{txHash}
/evm/{chain}/txs/{accountAddress}
```

## Changelog

New API v2 endpoints are added:
- `api/v2/proxy/noves-fi/transactions/${th_hash}` (proxy for `/evm/{chain}/tx/{txHash}`)
- `api/v2/proxy/noves-fi/transactions/${tx_hash}/describe` (proxy for /evm/{chain}/describeTx/{txHash})
- `api/v2/proxy/noves-fi/addresses/${address_hash}/transactions` (proxy for /evm/{chain}/txs/{accountAddress})

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2024-01-04 14:10 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex
> +  @spec validate_address(String.t(), any(), list()) :: {:ok, Hash.Address.t(), Address.t()}
```suggestion
  @spec validate_address(String.t(), any(), Keyword.t()) ::
          {:format, :error}
          | {:not_found, {:error, :not_found}}
          | {:restricted_access, true}
          | {:ok, Hash.t(), Address.t()}
```

2024-01-04 14:10 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
> +  @spec validate_transaction(String.t(), any(), list()) :: {:ok, Transaction.t(), Hash.t()}
```suggestion
  @spec validate_transaction(String.t(), any(), Keyword.t()) ::
          {:format, :error}
          | {:not_found, {:error, :not_found}}
          | {:restricted_access, true}
          | {:ok, Transaction.t(), Hash.t()}
```

2024-01-09 23:09 UTC, nikitosing requested changes

2024-01-09 23:09 UTC, nikitosing commented on apps/explorer/lib/explorer/third_party_integrations/noves_fi.ex
> +  @spec noves_fi_api_request(String.t(), Plug.Conn.t()) :: any()
My suggestion for this spec:
`@spec noves_fi_api_request(String.t(), Plug.Conn.t()) :: {any(), integer()} | nil`

2024-01-10 12:17 UTC, vbaranov commented on apps/explorer/lib/explorer/third_party_integrations/noves_fi.ex
> +  end
It makes sense. Done in https://github.com/blockscout/blockscout/pull/9056/commits/1ae07eaa20e0450b7f2858543b9d1bde1986f66c.

2024-01-10 12:18 UTC, vbaranov commented on apps/explorer/lib/explorer/third_party_integrations/noves_fi.ex
> +  @spec noves_fi_api_request(String.t(), Plug.Conn.t()) :: any()
Done in https://github.com/blockscout/blockscout/pull/9056/commits/1ae07eaa20e0450b7f2858543b9d1bde1986f66c except nil is removed from the possible response since the logic of the function changed a bit.

2024-01-11 10:36 UTC, nikitosing approved these changes

2024-01-12 05:38 UTC, merged