Polygon zkEVM Bridge indexer and API v2 extension
blockscout/blockscout pull request #9098
Opened 2024-01-04 07:22 UTC by varasev

Closes https://github.com/blockscout/blockscout/issues/8268.

## Motivation

This PR adds an indexer for Polygon zkEVM Bridge operations (Deposits and Withdrawals) and extends API v2 for the corresponding views on UI.

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [x] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2024-01-08 20:41 UTC, akolotov commented on apps/indexer/lib/indexer/fetcher/zkevm/transaction_batch.ex
> +      if System.get_env("CHAIN_TYPE") == "polygon_zkevm" do
Personally I don't like this approach since this check will be executed every time during runtime. Is it possible to consider to utilise the module attribute `@dialyzer` to avoid errors?
For example `Chain.import` can be moved in a separate functions e.g. `import_to_db` and this new function can be decorated with:
```
  @dialyzer {:no_return, [import_to_db: 1]}
  @dialyzer {:no_fail_call, [import_to_db: 1]}
```

2024-01-08 20:55 UTC, akolotov commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge_l1.ex
> +  defp get_last_l1_item do
Does it make sense to move this call to `Explorer.Chain.Zkevm.Reader`?

2024-01-08 20:55 UTC, akolotov commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge_l2.ex
> +  defp get_last_l2_item do
Does it make sense to move it to `Explorer.Chain.Zkevm.Reader`?

2024-01-08 20:55 UTC, akolotov commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge_l2.ex
> +        "As L2 reorg was detected, some withdrawals with block_number >= #{reorg_block} were removed from zkevm_bridge table. Number of removed rows: #{deleted_count}."
Please clarify if reorgs are possible in Polygon zkEVM rollups?

2024-01-08 22:43 UTC, akolotov requested changes

2024-01-08 22:43 UTC, akolotov commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge_l1.ex
> +  defp reorg_queue_get(table_name) do
Looks like code duplication with `Indexer.Fetcher.PolygonEdge`. Does it make sense to introduce a library for this?

2024-01-08 23:13 UTC, akolotov commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge_l1.ex
> +        max(block_check_interval - Timex.diff(Timex.now(), time_before, :milliseconds), 0)
Is the following description of the implemented actions is correct?

1. Let's assume `start_block` and `end_block` has the same value. E.g. 5
2. We receive all the logs in the blocks range `5..5`.
3. `new_start_block` is 6 after that
4. Whereas `new_end_block` could be still 5. It is possible since block_check_interval is twice less than time difference between two consequent L1 blocks.
5. It means that for the next iteration `start_block` is 6 and `end_block` is 5. 

If my understanding correct, `eth_getLogs` will return 0 logs for such request. And it means that some `getLogs` requests are useless.

So, does it make sense to check that `end_block` is equal or greater than `start_block` to avoid sending useless RPC calls?

2024-01-12 07:12 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/zkevm/transaction_batch.ex
> +      if System.get_env("CHAIN_TYPE") == "polygon_zkevm" do
Yes, we do this using `.dialyzer-ignore` file, but we aim to reduce this file as far as possible. For that reason you see that workaround. The explicit check of CHAIN_TYPE shouldn't take much time during runtime, so I think it doesn't affect anything (except code readability in a small piece)

2024-01-12 07:20 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge_l1.ex
> +        max(block_check_interval - Timex.diff(Timex.now(), time_before, :milliseconds), 0)
Yes, it's checked here: https://github.com/blockscout/blockscout/blob/425a43dd5db7bcd952f86d76dae16ba78b4de828/apps/indexer/lib/indexer/fetcher/zkevm/bridge_l1.ex#L166

2024-01-12 07:39 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge_l1.ex
> +  defp get_last_l1_item do
Yes, done in https://github.com/blockscout/blockscout/commit/1877b04c6019f641fda8a96c25ae37bed0401604

2024-01-12 07:39 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge_l2.ex
> +  defp get_last_l2_item do
Yes, done in https://github.com/blockscout/blockscout/commit/1877b04c6019f641fda8a96c25ae37bed0401604

2024-01-12 07:59 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge_l2.ex
> +        "As L2 reorg was detected, some withdrawals with block_number >= #{reorg_block} were removed from zkevm_bridge table. Number of removed rows: #{deleted_count}."
I guess, yes, because its RPC has `safe` in `eth_getBlockByNumber`. Also, L2 reorgs are mentioned on https://github.com/0xPolygonHermez/zkevm-node?tab=readme-ov-file#readme

2024-01-12 08:13 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge_l1.ex
> +  defp reorg_queue_get(table_name) do
Polygon Edge is not supported anymore by Polygon team and Blockscout doesn't have such instances. We are going to remove Polygon Edge modules from Blockscout soon, so I'd leave it as it is for now

2024-01-21 22:43 UTC, akolotov commented on apps/indexer/lib/indexer/fetcher/zkevm/transaction_batch.ex
> +      if System.get_env("CHAIN_TYPE") == "polygon_zkevm" do
I have prepared another solution for the problem: https://github.com/blockscout/blockscout/compare/f52763b...4565a42

2024-01-23 07:31 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/zkevm/transaction_batch.ex
> +      if System.get_env("CHAIN_TYPE") == "polygon_zkevm" do
Thanks, I added the same changes in the commit https://github.com/blockscout/blockscout/pull/9098/commits/667ddb1eecd47be5cf3ff048d9e1d2513bbadc09

2024-01-24 09:39 UTC, vbaranov reviewed
@varasev please rebase to master branch. After merging #8929 there are multiple conflicts.

2024-01-24 21:40 UTC, akolotov commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge_l1.ex
> +  defp reorg_queue_get(table_name) do
Is my initial comment still applicable because we have now Shibarium related code?

2024-01-24 22:21 UTC, akolotov commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge_l1.ex
> +  defp reorg_queue_get(table_name) do
Moreover similar code exists in Optimism branch. Does it make sense to make a framework of re-orgs handling re-usable in all L2-chains?

2024-01-25 06:50 UTC, varasev commented
@vbaranov Rebased

2024-01-25 07:05 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge_l1.ex
> +  defp reorg_queue_get(table_name) do
Yes, I will move these functions in a separate module

2024-01-25 21:45 UTC, akolotov requested changes
Please provide `@doc` comments for every public function introduced. If a changed public function does not have `@doc` comments it will be great if you add it there as well.

2024-01-25 21:45 UTC, akolotov commented on apps/indexer/lib/indexer/block/fetcher.ex
> +             do: ZkevmBridge.parse(blocks, logs),
Since this call could make lots of RPC calls, it could delay the block importing, which could cause latency in the new block appearance on UI side. Consider to move logic of getting blocks timestamps and token data (both from DB and RPC) to an async worker (see `async_import_remaining_block_data` of the realtime fetcher).

2024-01-25 21:45 UTC, akolotov commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge.ex
> +    |> Repo.all(timeout: :infinity)
Does it make sense to move this to the Reader module?

2024-01-25 21:45 UTC, akolotov commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge.ex
> +      |> Repo.all()
Does it make sense to move this to the Reader module?

2024-01-25 21:45 UTC, akolotov commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge.ex
> +        Enum.map(["95d89b41", "313ce567"], fn method_id ->
Does it make sense to define the methods selectors as the module attributes?

2024-01-25 21:45 UTC, akolotov commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge.ex
> +        address = String.downcase(request.contract_address)
There is a function `address_hash_to_string` in `Indexer.Helper`

2024-01-25 21:45 UTC, akolotov commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge.ex
> +        token_address = String.downcase(Hash.to_string(address))
There is a function `address_hash_to_string` in `Indexer.Helper`

2024-01-25 21:45 UTC, akolotov commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge.ex
> +    |> Enum.reduce(%{}, fn t, acc -> Map.put(acc, Hash.to_string(t.address), t.id) end)
Is `Hash.to_string(<address>)` equal `Helper.address_hash_to_string(<address>, false)`?

2024-01-25 21:45 UTC, akolotov commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge.ex
> +        Enum.any?(tokens_inserted, fn inserted -> token.address == Hash.to_string(inserted.address) end)
Is `Hash.to_string(<address>)` equal `Helper.address_hash_to_string(<address>, false)`?

2024-01-25 21:45 UTC, akolotov commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge.ex
> +      if System.get_env("CHAIN_TYPE") == "polygon_zkevm" do
Does this still make sense?

2024-01-31 12:58 UTC, varasev commented on apps/indexer/lib/indexer/block/fetcher.ex
> +             do: ZkevmBridge.parse(blocks, logs),
Yes, done this in https://github.com/blockscout/blockscout/pull/9098/commits/affe983ed3986908c54538688040656e7c03206c

2024-02-01 10:22 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge.ex
> +    |> Repo.all(timeout: :infinity)
Yes, moved in https://github.com/blockscout/blockscout/commit/f4f68ea3880ee724093c5d80c4cc7c9e63718b99

2024-02-01 10:22 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge.ex
> +      |> Repo.all()
Yes, moved in https://github.com/blockscout/blockscout/commit/f4f68ea3880ee724093c5d80c4cc7c9e63718b99

2024-02-01 10:23 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge.ex
> +        Enum.map(["95d89b41", "313ce567"], fn method_id ->
Yes, done in https://github.com/blockscout/blockscout/commit/f4f68ea3880ee724093c5d80c4cc7c9e63718b99

2024-02-01 10:23 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge.ex
> +        token_address = String.downcase(Hash.to_string(address))
Refactored in https://github.com/blockscout/blockscout/commit/f4f68ea3880ee724093c5d80c4cc7c9e63718b99

2024-02-01 10:23 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge.ex
> +    |> Enum.reduce(%{}, fn t, acc -> Map.put(acc, Hash.to_string(t.address), t.id) end)
Yes, refactored in https://github.com/blockscout/blockscout/commit/f4f68ea3880ee724093c5d80c4cc7c9e63718b99

2024-02-01 10:24 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge.ex
> +        Enum.any?(tokens_inserted, fn inserted -> token.address == Hash.to_string(inserted.address) end)
Yes, refactored in https://github.com/blockscout/blockscout/commit/f4f68ea3880ee724093c5d80c4cc7c9e63718b99

2024-02-01 15:03 UTC, akolotov commented
@varasev, a general question about the approach to execute L1 RPC requests during the block fetcher job asynchronously. My understanding is that initiating bridge L1 messages happens first, and the corresponding L2 messages appear after some 'finalization' time, correct? So, if we have an independent fetcher (`Indexer.Fetcher.Zkevm.BridgeL1`?) that looks for L1 messages first, then handling L2 messages will be quite fast during the block fetcher job, without the necessity to make RPC calls to the L1 endpoint.

2024-02-02 07:31 UTC, varasev commented
> Please provide `@doc` comments for every public function introduced. If a changed public function does not have `@doc` comments it will be great if you add it there as well.

Done

2024-02-02 07:59 UTC, varasev commented
> My understanding is that initiating bridge L1 messages happens first, and the corresponding L2 messages appear after some 'finalization' time, correct?

@akolotov Yes, if you mean Deposit operation. For Withdrawals it's vice versa: L2 message first, then L1 one.

For realtime case on L1:

- If it's Deposit operation (L1 -> L2), `Indexer.Fetcher.Zkevm.BridgeL1` catches `BridgeEvent` and initiates separate requests to RPC node (to get block timestamp and token data from L1).

- If it's Withdrawal operation (L2 -> L1), `Indexer.Fetcher.Zkevm.BridgeL1` catches `ClaimEvent`, but doesn't send separate requests to RPC as they only needed for `BridgeEvent`.

For realtime case on L2:

`Indexer.Fetcher.Zkevm.BridgeL2` is only responsible for finding historical operations, so in real time it's off.

For the realtime we have `Indexer.Transform.Zkevm.Bridge` instead of `Indexer.Fetcher.Zkevm.BridgeL2`. The transformer catches `BridgeEvent` and `ClaimEvent` events without sending RPC requests to L1 for getting block timestamp (as they are already sent by the block fetcher). But for getting L1 token data we still need to send separate RPC requests on L1 for `BridgeEvent` only. They are now sent asynchronously through `Indexer.Fetcher.Zkevm.BridgeL1Tokens`, so they don't affect the block fetcher.

These token data RPC requests are not sent by `Indexer.Fetcher.Zkevm.BridgeL1Tokens` if the token data is already in the database (it could be written there earlier by `Indexer.Fetcher.Zkevm.BridgeL1` which works in real time, separately and asynchronously).

2024-02-05 12:19 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge_l1.ex
> +  defp reorg_queue_get(table_name) do
Done this in https://github.com/blockscout/blockscout/pull/9098/commits/9888f59066731de4be5bbaec7676ebafc4e8d935

2024-02-07 21:38 UTC, akolotov requested changes

2024-02-07 21:38 UTC, akolotov commented on apps/indexer/lib/indexer/fetcher/zkevm/bridge.ex
> +      {:ok, timestamp} = DateTime.from_unix(quantity_to_integer(Map.get(block, "timestamp")))
Consider to use `EthereumJSONRPC.timestamp_to_datetime` here.

2024-02-08 11:37 UTC, varasev commented on apps/indexer/lib/indexer/helper.ex
> +  def get_blocks_by_events(events, json_rpc_named_arguments, retries) do
Yes, added chunks in https://github.com/blockscout/blockscout/commit/95e522be147f92a33b4e682e3b54b45279e0c84a

2024-02-13 13:19 UTC, vbaranov reviewed
Now, since we have `INDEXER_POLYGON_EDGE_` and `INDEXER_POLYGON_ZKEVM_` envs set families I would suggest change the structure of folders. It would be natural if everywhere instead `polygon_edge` and `zkevm` folders we'd have:
```
polygon
  edge
  zkevm
```

And I'd rename corresponging modules to have `Polygon.Edge`, `Polygon.Zkevm`.

2024-02-13 13:19 UTC, vbaranov commented on CHANGELOG.md
> +- [#9098](https://github.com/blockscout/blockscout/pull/9098) - Polygon zkEVM Bridge indexer and API v2 extension
@varasev please move CHANGELOG record to the Current section.

2024-02-14 07:03 UTC, varasev commented on CHANGELOG.md
> +- [#9098](https://github.com/blockscout/blockscout/pull/9098) - Polygon zkEVM Bridge indexer and API v2 extension
Done

2024-02-14 11:00 UTC, varasev commented
> Now, since we have `INDEXER_POLYGON_EDGE_` and `INDEXER_POLYGON_ZKEVM_` envs set families I would suggest change the structure of folders. It would be natural if everywhere instead `polygon_edge` and `zkevm` folders we'd have:
> 
> ```
> polygon
>   edge
>   zkevm
> ```
> 
> And I'd rename corresponging modules to have `Polygon.Edge`, `Polygon.Zkevm`.

I renamed Zkevm to PolygonZkevm: https://github.com/blockscout/blockscout/pull/9098/commits/d8fd9b2d20bf2a6813ca94223b12ebea9d11ca73

As PolygonEdge will be removed soon, I left it as it is

2024-02-14 12:12 UTC, vbaranov approved these changes

2024-02-14 15:42 UTC, merged