EIP-1167 display multiple sources of bytecode twin
blockscout/blockscout pull request #9124
Opened 2024-01-09 09:13 UTC by vbaranov

Resolves https://github.com/blockscout/blockscout/issues/9045

## Motivation

Smart-contract page and API don't return additional source codes of verified bytecode twin.

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2024-01-09 16:26 UTC, nikitosing requested changes
@vbaranov Let's add regression test for the fixed bug?

2024-01-09 16:26 UTC, nikitosing commented on apps/explorer/lib/explorer/chain/smart_contract/proxy/eip_1167.ex
> +    |> Repo.preload([:smart_contract_additional_sources])
Similar question, why `necessity_by_association` is not enough?

2024-01-10 13:19 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex
> +        [smart_contract: :smart_contract_additional_sources] => :optional
Yes, seems redundant. Remove in https://github.com/blockscout/blockscout/pull/9124/commits/fd67e8a3cf4a757735d6248ce150221e2110a1d5.

2024-01-10 13:19 UTC, vbaranov commented on apps/explorer/lib/explorer/chain.ex
> +      |> Repo.preload(smart_contract: :smart_contract_additional_sources)
Indeed, we don't need. Remove in https://github.com/blockscout/blockscout/pull/9124/commits/fd67e8a3cf4a757735d6248ce150221e2110a1d5.

2024-01-10 13:19 UTC, vbaranov commented on apps/explorer/lib/explorer/chain/smart_contract/proxy/eip_1167.ex
> +    |> Repo.preload([:smart_contract_additional_sources])
Done in https://github.com/blockscout/blockscout/pull/9124/commits/fd67e8a3cf4a757735d6248ce150221e2110a1d5.

2024-01-10 15:34 UTC, vbaranov commented
> @vbaranov Let's add regression test for the fixed bug?

@nikitosing regress test added in https://github.com/blockscout/blockscout/pull/9124/commits/1f927c199837f13e6899533cd5b401d6d9d21ba4.

2024-01-11 12:07 UTC, nikitosing approved these changes

2024-01-19 13:08 UTC, Qwerty5Uiop approved these changes

2024-01-19 13:10 UTC, merged