Fix getblockreward; Add getblockcountdown actions
blockscout/blockscout pull request #9185
Opened 2024-01-18 07:06 UTC by sl1depengwyn

*[GitHub keywords to close any associated issues](https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/)*

## Motivation

*Why we should merge these changes.  If using GitHub keywords to close [issues](https://github.com/poanetwork/blockscout/issues), this is optional as the motivation can be read on the issue page.*

## Changelog

### Enhancements
*Things you added that don't break anything.  Regression tests for Bug Fixes count as Enhancements.*

### Bug Fixes
*Things you changed that fix bugs.  If a fixes a bug, but in so doing adds a new requirement, removes code, or requires a database reset and reindex, the breaking part of the change should be added to Incompatible Changes below also.*

### Incompatible Changes
*Things you broke while doing Enhancements and Bug Fixes.  Breaking changes include (1) adding new requirements and (2) removing code.  Renaming counts as (2) because a rename is a removal followed by an add.*

## Upgrading

*If you have any Incompatible Changes in the above Changelog, outline how users of prior versions can upgrade once this PR lands or when reviewers are testing locally.  A common upgrading step is "Database reset and re-index required".*

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2024-01-22 09:16 UTC, vbaranov reviewed
@sl1depengwyn Please add a PR with descriptions of the new API methods to the https://docs.blockscout.com/for-users/api/rpc-endpoints

2024-01-22 09:16 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/block_controller.ex
> +  def getblockcountdown(conn, params) do
Please add doc for this function

2024-01-24 10:13 UTC, nikitosing requested changes

2024-01-24 10:13 UTC, nikitosing commented on apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex
> +  def ethprice(conn, params), do: coinprice(conn, params)
It'll return:
```
  %{
        "coin_btc" => rates.btc_value && to_string(rates.btc_value),
        "coin_btc_timestamp" => timestamp,
        "coin_usd" => rates.usd_value && to_string(rates.usd_value),
        "coin_usd_timestamp" => timestamp
    }
```
Instead of:
```
  {
      "ethbtc": ...,
      "ethbtc_timestamp": ...,
      "ethusd": ...,
      "ethusd_timestamp": ...
   }
   
```

2024-01-24 10:13 UTC, nikitosing commented on apps/explorer/lib/explorer/chain.ex
> -  @spec block_reward(Block.block_number()) :: Wei.t()
Why did u decided to delete it?

2024-01-26 10:11 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/chain.ex
> -  @spec block_reward(Block.block_number()) :: Wei.t()
It was used only by `getblockreward` action and as it does not use it anymore it's not needed

2024-01-26 11:12 UTC, sl1depengwyn commented
> @sl1depengwyn Please add a PR with descriptions of the new API methods to the https://docs.blockscout.com/for-users/api/rpc-endpoints

https://github.com/blockscout/docs/pull/234

2024-01-26 11:13 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/block_controller.ex
> +  def getblockcountdown(conn, params) do
Done in https://github.com/blockscout/blockscout/pull/9185/commits/3eaddd16ab14739a5adc253f2d0c60cec6bbf13f with general doc update for this module

2024-01-26 11:13 UTC, sl1depengwyn commented on apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex
> +  def ethprice(conn, params), do: coinprice(conn, params)
Nice catch! Fixed in https://github.com/blockscout/blockscout/pull/9185/commits/3eaddd16ab14739a5adc253f2d0c60cec6bbf13f

2024-01-26 11:16 UTC, vbaranov approved these changes

2024-01-26 11:20 UTC, nikitosing approved these changes

2024-01-26 11:30 UTC, merged