Support the 2nd version of L2<->L1 Polygon zkEVM Bridge
blockscout/blockscout pull request #9637
Opened 2024-03-14 11:25 UTC by varasev

Extends https://github.com/blockscout/blockscout/pull/9098. Closes https://github.com/blockscout/blockscout/issues/9577.

## Motivation

Polygon zkEVM introduced the [second version](https://github.com/0xPolygonHermez/zkevm-contracts/blob/feature/v2ForkID5/contracts/v2/PolygonZkEVMBridgeV2.sol) of the bridge smart contract. This PR adds its support. The changes are backward compatible with the previous bridge implementation and tested for Polygon zkEVM and Astar zkEVM as Layer-2 and Ethereum Mainnet as Layer-1.

Note that for now only L2<->L1 is supported. For L2<->L2 communications the module will need to be changed (or the new module will be designed).

## Upgrading

When restarting Blockscout instance with these changes, we must additionally define the following env variables:
- INDEXER_POLYGON_ZKEVM_L1_BRIDGE_NETWORK_ID
- INDEXER_POLYGON_ZKEVM_L1_BRIDGE_ROLLUP_INDEX (not defined if L1 is Ethereum Mainnet)
- INDEXER_POLYGON_ZKEVM_L2_BRIDGE_NETWORK_ID
- INDEXER_POLYGON_ZKEVM_L2_BRIDGE_ROLLUP_INDEX

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [x] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2024-03-26 07:59 UTC, vbaranov requested changes

2024-03-26 07:59 UTC, vbaranov commented on CHANGELOG.md
> +- [#9637](https://github.com/blockscout/blockscout/pull/9637) - Support the 2nd version of L2<->L1 Polygon zkEVM Bridge
Please remove changelog record. Changelog is auto-generated now.

2024-03-26 07:59 UTC, vbaranov commented on config/runtime.exs
> +  native_decimals: ConfigHelper.parse_integer_env_var("INDEXER_POLYGON_ZKEVM_L1_BRIDGE_NATIVE_DECIMALS", 18),
New env vars are missing in `docker-compose/envs/common-blockscout.env`.

2024-03-26 07:59 UTC, vbaranov commented on config/runtime.exs
> +  rollup_network_id_l1: ConfigHelper.parse_integer_or_nil_env_var("INDEXER_POLYGON_ZKEVM_L1_BRIDGE_NETWORK_ID"),
We could get network id from both l1/l2 JSON RPC endpoints in a single request and cache its value in the DB in the `constants` table. Having envs for that seems is redundant.

2024-03-26 07:59 UTC, vbaranov commented on config/runtime.exs
> +  native_decimals: ConfigHelper.parse_integer_env_var("INDEXER_POLYGON_ZKEVM_L1_BRIDGE_NATIVE_DECIMALS", 18),
We could get `decimals` from bridge contract on l1 with a single JSON RPC request and cache its value in the DB in the `constants` table.

2024-03-26 07:59 UTC, vbaranov commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +         Map.get(token, :symbol, "") == "" or Map.get(token, :decimals) > @decimals_max
We could use `sanitize_decimals` function, introduced in `Explorer.Chain.PolygonZkevm.Reader` module, for the 2nd condition.

2024-03-26 07:59 UTC, vbaranov commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +    if Map.get(new_data, :decimals, 0) <= @decimals_max do
We could use `sanitize_decimals` function, introduced in `Explorer.Chain.PolygonZkevm.Reader` module.

2024-03-26 07:59 UTC, vbaranov commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +  @decimals_max 0xFF
This will be unused once you'll re-use `sanitize_decimals` function in this module.

2024-03-26 07:59 UTC, vbaranov commented on apps/indexer/lib/indexer/fetcher/polygon_zkevm/bridge.ex
> +    rollup_index = Bitwise.band(Bitwise.bsr(global_index, 32), 0xFFFFFFFF)
`0xFFFFFFFF` is used twice. Let's define it in module attribute.

2024-03-28 10:26 UTC, varasev commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +         Map.get(token, :symbol, "") == "" or Map.get(token, :decimals) > @decimals_max
I made it intentionally for tx actions module as in this module we calculate amounts based on the decimals and write them into database. To avoid critical incorrect calculation (and probably indexer interruption), the module ignores actions with abnormal decimals.

For zkEVM module, the token decimals are only used to display amount in UI, but not used by the indexer itself, so it's possible to make abnormal decimals equal to 0, but index such an operation anyway.

2024-03-28 10:26 UTC, varasev commented on CHANGELOG.md
> +- [#9637](https://github.com/blockscout/blockscout/pull/9637) - Support the 2nd version of L2<->L1 Polygon zkEVM Bridge
Sure, removed in https://github.com/blockscout/blockscout/commit/9cf4aabcde58253488ab02055991c3fa82c42f99

2024-03-28 10:27 UTC, varasev commented on config/runtime.exs
> +  native_decimals: ConfigHelper.parse_integer_env_var("INDEXER_POLYGON_ZKEVM_L1_BRIDGE_NATIVE_DECIMALS", 18),
Added in https://github.com/blockscout/blockscout/commit/9cf4aabcde58253488ab02055991c3fa82c42f99

2024-03-28 10:29 UTC, varasev commented on apps/indexer/lib/indexer/fetcher/polygon_zkevm/bridge.ex
> +    rollup_index = Bitwise.band(Bitwise.bsr(global_index, 32), 0xFFFFFFFF)
This is just a bitmask to get 4 bytes integer after the bignumber shifting. I'd propose to assign it to a variable as it's done in https://github.com/blockscout/blockscout/commit/9cf4aabcde58253488ab02055991c3fa82c42f99 (but I'm not sure that it doesn't degrade code readability).

2024-03-28 10:36 UTC, varasev commented on config/runtime.exs
> +  rollup_network_id_l1: ConfigHelper.parse_integer_or_nil_env_var("INDEXER_POLYGON_ZKEVM_L1_BRIDGE_NETWORK_ID"),
These ids are not network ids in the usual sense (like 1 = Ethereum Mainnet or 10 = Optimism Mainnet), but the internal ids in terms of zkEVM bridge (0 = Ethereum Mainnet, 1 = Polygon zkEVM, 2 = Astar zkEVM, etc.). We need this param to filter bridge operations for exact `L1<->L2` bundle in LXLX bridge which, for example, uses the same smart contract on L1 for different rollups.

2024-03-28 10:46 UTC, varasev commented on config/runtime.exs
> +  native_decimals: ConfigHelper.parse_integer_env_var("INDEXER_POLYGON_ZKEVM_L1_BRIDGE_NATIVE_DECIMALS", 18),
Do you mean using `getTokenMetadata` getter of the `PolygonZkEVMBridgeV2` contract which returns decimals equal to 18 for WETH token? I'm not sure that would be correct as the native token theoretically can be different from ETH and we wouldn't have metadata for this case. By default I set `symbol = ETH` and `decimals = 18` for those optional envs, but not sure when we see the case for token other than ETH (should be some time later when there are more different bridges for zkEVM).

2024-03-28 10:50 UTC, varasev commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +    if Map.get(new_data, :decimals, 0) <= @decimals_max do
This relates to the comment https://github.com/blockscout/blockscout/pull/9637#discussion_r1542666046

2024-03-28 10:50 UTC, varasev commented on apps/indexer/lib/indexer/transform/transaction_actions.ex
> +  @decimals_max 0xFF
This relates to the comment https://github.com/blockscout/blockscout/pull/9637#discussion_r1542666046

2024-04-02 08:51 UTC, vbaranov commented on config/runtime.exs
> +  rollup_network_id_l1: ConfigHelper.parse_integer_or_nil_env_var("INDEXER_POLYGON_ZKEVM_L1_BRIDGE_NETWORK_ID"),
Gotcha, thanks for explanation.

2024-04-02 08:57 UTC, vbaranov commented on config/runtime.exs
> +  native_decimals: ConfigHelper.parse_integer_env_var("INDEXER_POLYGON_ZKEVM_L1_BRIDGE_NATIVE_DECIMALS", 18),
Hopefully in most cases we shouldn't set at least this variable at all.

2024-04-02 08:57 UTC, vbaranov approved these changes

2024-04-02 09:00 UTC, merged