refactor Enum.count to Enum.empty?.
blockscout/blockscout pull request #9666
Opened 2024-03-18 14:55 UTC by mohammedzeglam-pg

## Motivation

Enhance Enum usage could gain performance hits for example `!Enum.empty?(list)` has a constant time.

## Changelog

### Enhancements
Improve Enum usage

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2024-03-19 11:01 UTC, fedor-ivn requested changes
Thanks for the PR. Please, add an entry to `CHANGELOG.md`.

2024-03-19 11:09 UTC, fedor-ivn commented on apps/block_scout_web/lib/block_scout_web/notifier.ex
> +    if !Enum.empty?(transactions) do
I would suggest using `not` instead of `!`

2024-03-19 12:00 UTC, mohammedzeglam-pg commented on apps/block_scout_web/lib/block_scout_web/notifier.ex
> +    if !Enum.empty?(transactions) do
Thanks i updated

2024-03-19 13:20 UTC, mohammedzeglam-pg commented
> Please fix [these](https://github.com/blockscout/blockscout/actions/runs/8342550957/job/22831118754#step:5:1) warnings (see refactoring opportunities). I guess it would involve just swapping the if branches and removing the negation in the condition statement.

Yes you are correct.

2024-03-19 13:29 UTC, fedor-ivn commented on apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
> +            <%= if not Enum.empty?(test_nets) do %>
I guess it makes sense to also refactor such `not Enum.empty?(...)` conditions in the templates.

2024-03-19 13:31 UTC, mohammedzeglam-pg commented on apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
> +            <%= if not Enum.empty?(test_nets) do %>
you mean use `unless`

2024-03-19 13:51 UTC, fedor-ivn commented on apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
> +            <%= if not Enum.empty?(test_nets) do %>
This also an option

2024-03-19 13:53 UTC, mohammedzeglam-pg commented on apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
> +            <%= if not Enum.empty?(test_nets) do %>
in template i refactor it to use `unless`

2024-03-20 19:34 UTC, fedor-ivn approved these changes

2024-03-20 19:39 UTC, sl1depengwyn approved these changes

2024-03-21 15:29 UTC, vbaranov commented on CHANGELOG.md
> +- [#9666](https://github.com/blockscout/blockscout/pull/9666) - Improved performance by replacing `Enum.count(list) == 0` with `Enum.empty?(list)` for better readability and efficiency.
Sorry, for making a request about changelog again. Could you please remove CHANGELOG record? We recently migrated to semi-auto generation of changelog.

2024-03-21 15:54 UTC, mohammedzeglam-pg commented on CHANGELOG.md
> +- [#9666](https://github.com/blockscout/blockscout/pull/9666) - Improved performance by replacing `Enum.count(list) == 0` with `Enum.empty?(list)` for better readability and efficiency.
done

2024-03-21 19:31 UTC, merged