Allow for custom base_url for fetching prices
blockscout/blockscout pull request #9679
Opened 2024-03-19 21:29 UTC by mergd

## Motivation

We run multiple instances of Blockscout, and each instance fetches price data from a price provider. However, it's more performant to cache these queries.

This PR introduces overrides for the BASE_URL env vars for CoinMarketCap and Coingecko.

## Changelog

## Checklist for your Pull Request (PR)

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2024-03-21 19:21 UTC, vbaranov requested changes

2024-03-21 19:21 UTC, vbaranov commented on CHANGELOG.md
> +- [#9679](https://github.com/blockscout/blockscout/pull/9679) - Add custom base_url for price providers
Please remove any changes from CHANGELOG. Changelog currently is semi-auto generated.

2024-03-21 19:21 UTC, vbaranov commented on config/runtime.exs
> +
This line is unnecessary

2024-03-21 19:21 UTC, vbaranov commented on config/runtime.exs
> +  base_url: System.get_env("EXCHANGE_RATES_COINGECKO_BASE_URL"),
New env vars should be added to https://github.com/blockscout/blockscout/blob/master/docker-compose/envs/common-blockscout.env

2024-03-22 09:01 UTC, fedor-ivn commented
Please, resolve conflicts

2024-03-22 09:11 UTC, fedor-ivn commented on CHANGELOG.md
It would be better if the linting updates to the CHANGELOG file were not included in this PR, since otherwise we mix functional changes with linting updates. Could you please remove the CHANGELOG updates from this PR? We can address the linting updates in a separate PR.

2024-04-03 07:29 UTC, merged