feat: Contract code on-demand fetcher
blockscout/blockscout pull request #9708
Opened 2024-03-22 16:48 UTC by vbaranov

*[GitHub keywords to close any associated issues](https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/)*

## Motivation

*Why we should merge these changes.  If using GitHub keywords to close [issues](https://github.com/poanetwork/blockscout/issues), this is optional as the motivation can be read on the issue page.*

## Changelog

### Enhancements
*Things you added that don't break anything.  Regression tests for Bug Fixes count as Enhancements.*

### Bug Fixes
*Things you changed that fix bugs.  If a fixes a bug, but in so doing adds a new requirement, removes code, or requires a database reset and reindex, the breaking part of the change should be added to Incompatible Changes below also.*

### Incompatible Changes
*Things you broke while doing Enhancements and Bug Fixes.  Breaking changes include (1) adding new requirements and (2) removing code.  Renaming counts as (2) because a rename is a removal followed by an add.*

## Upgrading

*If you have any Incompatible Changes in the above Changelog, outline how users of prior versions can upgrade once this PR lands or when reviewers are testing locally.  A common upgrading step is "Database reset and re-index required".*

## Checklist for your Pull Request (PR)

  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so by submitting a PR to https://github.com/blockscout/docs
  - [ ] If I added/changed/removed ENV var, I submitted a PR to https://github.com/blockscout/docs to update the list of env vars at https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md and I updated the version to `master` in the Version column. Changes will be reflected in this table: https://docs.blockscout.com/for-developers/information-and-settings/env-variables. 
  - [ ] If I add new indices into DB, I checked, that they are not redundant with PGHero or other tools

2024-03-25 13:27 UTC, k1rill-fedoseev requested changes

2024-03-25 13:27 UTC, k1rill-fedoseev commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex
> +        ContractCode.trigger_fetch(address_hash)
I don't like that we'll re-request contract code each time someone opens a page of a regular EOA. I think at least it makes sense to skip addresses that are 100% EOA (e.g. have nonce > 0). EVM also stores non-zero nonces for contracts, but I think Blockscout only tracks them for EOAs.

2024-03-25 13:27 UTC, k1rill-fedoseev commented on apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex
> +            Helper.current_time() - updated_at_ms > min(:math.pow(update_threshold(), retries_number), @max_delay)} do
What's the expected delay sequence for 5s threshold?

I don't think `5s ** 2 = 5000ms ** 2 = 25000000ms = 25000 seconds` for the second retry is the correct delay?

2024-03-25 13:27 UTC, k1rill-fedoseev commented on apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex
> +         true <- contract_code_object.code !== "0x" do
Why do we reject empty bytecodes here? If the RPC node tells us the address is not a contract, I don't think we should retry this request.

2024-03-25 13:46 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
> +  ContractCode
Unintentional artefact. Removed.

2024-03-25 13:48 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
> +        ContractCode.trigger_fetch(address_hash)
I added aliases with `OnDemand` suffix in all places, including this in order to eliminate ambiguity.

2024-03-25 13:49 UTC, vbaranov commented on apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex
> +         true <- contract_code_object.code !== "0x" do
The address may become contract in the future.

2024-03-25 15:16 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex
> +        ContractCode.trigger_fetch(address_hash)
Good point. Nonce check implemented in https://github.com/blockscout/blockscout/pull/9708/commits/08533059195a3995e0b73bef4477331dc42dac5b.

2024-03-25 17:29 UTC, k1rill-fedoseev commented on apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex
> +            Helper.current_time() - updated_at_ms > min(:math.pow(update_threshold(), retries_number), @max_delay)} do
I think the best approach here would be to use something like: `5 * 2**n` instead of `5**n`. I don't think that initial value of threshold should change how fast the next timeouts will grow.

2024-03-25 17:54 UTC, vbaranov commented on apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex
> +            Helper.current_time() - updated_at_ms > min(:math.pow(update_threshold(), retries_number), @max_delay)} do
Nice catch! Processed in https://github.com/blockscout/blockscout/pull/9708/commits/0f06f4566d6b4926d72bdf3fd5f59932cca6cdfe.

2024-03-26 08:39 UTC, k1rill-fedoseev commented on apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
> +      if is_nil(address.contract_code) do
Does it make sense to also move this check inside `trigger_check` as with nonce?

2024-03-26 08:39 UTC, k1rill-fedoseev commented on apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex
> +         true <- contract_code_object.code !== "0x" do
So, opening a page with not-yet-deployed contract multiple times prior to its deployment will increase the delay after which it can be fetched after an actual deployment. I guess that's fine, don't see a better solution.

Also, treating such un-deployed contracts with empty code and JSON RPC errors from the node in the same way does not seem right to me. If the node is unavailable for some time, it will unfavorably skew the retries counters in the DB. Maybe we shouldn't increase the retry counter on HTTP/WS/JSON RPC errors at all?

2024-03-26 08:39 UTC, k1rill-fedoseev commented on apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex
> +  def handle_cast({:fetch, address}, state) do
Just curious, what'll happen with this and similar fetchers if there are too many events coming into GenServer faster than it's processing them? Is there some limit after which elixir will stop putting them into the queue, or an application will just run out of memory at some point? Is there a way to monitor these queue sizes somehow?

2024-03-29 16:59 UTC, vbaranov commented on apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
> +      if is_nil(address.contract_code) do
Thanks. Processed in https://github.com/blockscout/blockscout/pull/9708/commits/2e481a891742981ba64e43d41c5e94df6ffcab2e.

2024-03-29 17:10 UTC, vbaranov commented on apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex
> +         true <- contract_code_object.code !== "0x" do
I agree with you, this is worthwhile refinement for the sake of fetcher robustness. Implemented in https://github.com/blockscout/blockscout/pull/9708/commits/c488e61ca063e809de5ae5ab94e583505ba83d15.

2024-03-31 06:54 UTC, k1rill-fedoseev approved these changes

2024-04-02 10:31 UTC, nikitosing commented on apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex
> +    with {:empty_nonce, true} <- {:empty_nonce, is_nil(address.nonce)},
Shouldn't we accept zero nonce also?

2024-04-02 10:57 UTC, vbaranov commented on apps/indexer/lib/indexer/fetcher/on_demand/contract_code.ex
> +    with {:empty_nonce, true} <- {:empty_nonce, is_nil(address.nonce)},
I suppose, no. Zero nonce seems applied only to EOA.

2024-04-02 13:03 UTC, nikitosing approved these changes

2024-04-02 13:53 UTC, merged