Feat/adding mobula
blockscout/blockscout pull request #9971
Opened 2024-04-28 19:09 UTC by xyeuu

## Motivation

Integrating Mobula as a data provider significantly enhances Blockscout's market data capabilities, offering users access to a broader range of accurate and real-time data. Mobula's comprehensive dataset supports improved transparency and user experience.

## Changelog

### Enhancements
- Added Mobula as a data provider for exchanges rates.
- Improved market data accuracy and refresh rates with Mobula's real-time data feeds.
- Expanded data offering to include new tokens and pairs tracked by Mobula.

2024-04-30 09:26 UTC, vbaranov requested changes
@xyeuu 

Please run locally in order to fix some issues in CI:
1. `mix format` to fix formatting issues
2. `mix credo` - it will show you what to improve in the code style
3. `mix dialyzer` - the same as above
4. add `Mobula` to `cspell.json` https://github.com/blockscout/blockscout/actions/runs/8869796333/job/24416300917?pr=9971

2024-04-30 10:17 UTC, vbaranov reviewed
Dialyzer check is still failing in the `Explorer.ExchangeRates.Source.Mobula` module.

Exchange rates config should be extended to use Mobula source as well https://github.com/blockscout/blockscout/blob/master/config/config_helper.exs#L168-L184.

2024-05-14 10:55 UTC, vbaranov commented
@xyeuu there is a compilation error:
```
** (BadBooleanError) expected a boolean on left-side of "or", got: Explorer.ExchangeRates.Source.Mobula
    config/config_helper.exs:171: ConfigHelper.exchange_rates_source/0
```

2024-05-14 13:07 UTC, vbaranov commented on config/config_helper.exs
> +      end
I'd suggest to not override default fallback to CoinGecko fo now. Let's keep integration with Mobula source explicitly via setting corresponding envs.

2024-05-14 13:16 UTC, xyeuu commented on config/config_helper.exs
> +      end
Sure no problem, I remove it

2024-05-20 13:04 UTC, fedor-ivn commented on apps/explorer/lib/explorer/exchange_rates/source/mobula.ex
> +    )
Can we rewrite it as follows, what do you think?

```suggestion
    Logger.info(fn ->
      [
        "Fetching price history from Mobula: #{history_source_url()} for the last #{previous_days} days. ",
        "Timestamp: #{timestamp_ms} ms. ",
        "Now: #{DateTime.to_unix(now)} ms. ",
        "Date days ago: #{DateTime.to_unix(date_days_ago)} ms."
      ]
    end)
```

2024-05-20 13:09 UTC, fedor-ivn commented on apps/explorer/lib/explorer/exchange_rates/source/mobula.ex
> +    end
nitpick: I might be missing something, but can't we rewrite it like this? Just to lower cyclomatic complexity.

```suggestion
    Source.http_request(url, headers())
    |> case do
      {:ok, %{"price" => current_price}} ->
        {:ok, current_price}
    
      resp ->
        resp
    end
```

2024-05-20 16:53 UTC, xyeuu commented on apps/explorer/lib/explorer/exchange_rates/source/mobula.ex
> +    )
Hey, we can just remove the log I think

2024-05-20 20:22 UTC, fedor-ivn commented on apps/explorer/lib/explorer/exchange_rates/source/mobula.ex
> +    )
Yeah, sure. Lowering log level to `debug` also might be an option.

2024-05-20 20:33 UTC, fedor-ivn approved these changes

2024-05-28 11:45 UTC, sl1depengwyn requested changes

2024-05-28 11:45 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/exchange_rates/source/mobula.ex
> +    config(:api_key) || nil
In order to be able to configure `api_key` it should be defined in `runtime.exs` simmilar to other sources

2024-05-28 11:45 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/exchange_rates/source/mobula.ex
> +  end
Secodnary coin concept is used to have histroric data for two coins on the chain, so here we should be able to get history for both secondary and the main coin deepending of the function argument

2024-05-28 11:45 UTC, sl1depengwyn commented on apps/explorer/lib/explorer/market/history/source/price/mobula.ex
> +  end
Secondary coin argument should affect not only `secondary_coin` field in the result, but actual data, i.e. you should pass it to `history_url` function

2024-05-31 11:49 UTC, sl1depengwyn requested changes
Also, please add envs to https://github.com/blockscout/docs/blob/master/for-developers/information-and-settings/env-variables.md Everything else looks good to me

2024-05-31 11:49 UTC, sl1depengwyn commented on config/runtime.exs
> +  secondary_coin_id: cg_secondary_coin_id
I think a separate ENV value for Mobula secondary coin id is needed

2024-06-03 12:10 UTC, vbaranov reviewed
Please fix mix credo issue:
```
┃ [F] → Pipe chain should start with a raw value.
┃       apps/explorer/lib/explorer/exchange_rates/source/mobula.ex:166 #(Explorer.ExchangeRates.Source.Mobula.get_btc_price)
```

2024-06-05 11:41 UTC, fedor-ivn requested changes

2024-06-05 11:41 UTC, fedor-ivn commented on config/runtime.exs
> +mobula_secondary_coin_id = System.get_env("EXCHANGE_RATES_MOBULA_SECONDARY_COIN_ID")
Can we put this under `config :explorer, Explorer.ExchangeRates.Source.Mobula,`?

2024-06-05 11:41 UTC, fedor-ivn commented on apps/explorer/lib/explorer/exchange_rates/source/mobula.ex
> +      [{"Authorization", "#{api_key()}"}]
I believe it might be more readable to avoid creating a separate getter function here. Since it is very simple and used only once, it can be inlined.

```suggestion
    api_key = config(:api_key)
    if api_key do
      [{"Authorization", "#{api_key}"}]
```

2024-06-05 11:41 UTC, fedor-ivn commented on apps/explorer/lib/explorer/exchange_rates/source/mobula.ex
> +  end
It's more common in our codebase to put the defaults in `runtime.exs`, like this:

```ex
config :explorer, Explorer.ExchangeRates.Source.Mobula,
...
  base_url: System.get_env("EXCHANGE_RATES_MOBULA_BASE_URL", "https://api.mobula.io/api/1"),
...
```

2024-06-05 11:41 UTC, fedor-ivn commented on apps/explorer/lib/explorer/exchange_rates/source/mobula.ex
> +    config(:chain_id) || "ethereum"
I might be missing something, but I couldn't find the `:chain_id` key in the config defined in `runtime.exs`. Is it possible that you confused it with `:platform`?

2024-06-05 11:41 UTC, fedor-ivn commented on apps/explorer/lib/explorer/exchange_rates/source/mobula.ex
> +    config(:chain_id) || "ethereum"
btw, this getter could be inlined as well.

2024-06-05 13:11 UTC, sl1depengwyn approved these changes

2024-06-07 12:51 UTC, vbaranov approved these changes

2024-06-07 13:29 UTC, fedor-ivn approved these changes

2024-06-07 13:30 UTC, merged